### ISSUE TITLE
Allow last 'N' messages (delta offset)

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-streaming-server#10]
This is directly analogous to `TimeDeltaStart` vs. `StartTime`.  The user doesn't know (or care) what the current sequence number is, but wants the last, say, 1000 messages in order to prime e.g. a moving-window time series display. Right now there is no way to do that.

Ideally the user could just enter a negative offset, but that won't work because StartSequence is defined as uint64. Therefore I propose we just add DeltaOffset or OffsetDelta as another option and do the math in the server.

**Comment by foobargeez** [comment]
Hello,
I have a similar requirement.  More specifically, I am looking for the consumers to just receive the last message in a subscribed channel/topic.  I would have ideally preferred to just set the maximum number of messages in a given channel/topic to 1 but, per my understanding of the docs so far, per-channel max msg configuration isn't a possibility (please correct me if that is wrong).

Thanks!

**Comment by kozlovic** [comment]
@foobargeez You can have your subscriber receive messages starting with the last message in the channel. It is an option when creating the subscription. For example, in Go it would be:
```
sc.Subscribe(foo, cb, stan. StartWithLastReceived())
```
As for your question about overriding a specific channel limit, yes you can. Please check [this](https://github.com/nats-io/nats-streaming-server#store-limits).

**Comment by miroshnik** [comment]
Is it possible to implement a subscription which would allow to receive messages based on given _from_ and _to_ sequence indexes as params with two special values - _LastReceived_ for _from_ and _to_ params and _Last_ for _to_ param?
Also, it would be great, if it can be initialized with _auto-unsubscribe_ flag which tells subscription to unsubscribe when all _from_ _to_ messages would be received.

**Comment by kshvakov** [comment]
@kozlovic  I think @mcqueary  means functionality like Kafka group offsets. It's a very important feature for some customers. For example: if I had a broken logic in my soft, I want to replay all messages from X time point and restore my data.

**Comment by mcqueary** [comment]
@kshvakov Frankly, my original proposal was rooted in an (at that time) incomplete understanding of both Kafka *and* of the implementation challenges you face in using a partitioned log/channel scheme. NATS Streaming [durable subscriptions](https://github.com/nats-io/go-nats-streaming#durable-subscriptions) offers roughly the behavior you're familiar with vis-a-vis Kafka consumer group offsets. There are several differences in the way the two technologies work, but the basic capability to replay data from a point in the past is common to both.
