### ISSUE TITLE
Best practices when scaling down clients in a durable queue group

### ISSUE THREAD

**Issue by cwoolum** [nats-io/nats-streaming-server#1001]
I am using NATS streaming and am working with some autoscale functionality using [Keda](https://github.com/kedacore/keda) so that based on the number of queued messages, my clients will scale as well to match demand. 

In my initial implementation, when the clients would scale down, they would also unsubscribe since there was no longer any need for them to receive messages due to the reduced load. All of these clients are in the same durable group and queue group. The problem with this is that the subscription is destroyed when the we run out of messages and the last client unsubscribes and we are no longer able to track the last message received. 

The next approach was to close the connections but not unsubscribe but I think this causes messages to get lost. I have not been able to confirm this yet though.

Should clients in durable queue groups unsubscribe in a scale down event?

**Comment by aricart** [comment]
A few things:

You want a _durable_ and _queue subscription_. The durable portion will allow you to resume the subscription. For this to work, ensure that the durable name and the queue group name are the same in all the clients you want to treat as a group.

When scaling down, you want to call `close` on the subscription before you call `close` on the connection. You *never* want to call `unsubscribe` unless you want to destroy the durable itself.

Take a look at: 
https://docs.nats.io/nats-streaming-concepts/channels/subscriptions
https://github.com/nats-io/stan.go#queue-groups
https://github.com/nats-io/stan.go#durable-queue-groups
