### ISSUE TITLE
Tests failing on my machine, ubuntu amd64

### ISSUE THREAD

**Issue by StarpTech** [nats-io/nats-streaming-server#1002]
Hi, I run the tests from https://github.com/nats-io/nats-streaming-server/commit/d884137af1d03aa1ea3d553ccdf20819e1c7a5f6 and I got following error:

```
=== RUN   TestSignalTrapsSIGTERM
--- FAIL: TestSignalTrapsSIGTERM (2.01s)
    server_test.go:188: process not started yet
        1 - /mnt/ssd/repositories/nats-streaming-server/server/server_test.go:187
        2 - /mnt/ssd/repositories/nats-streaming-server/server/server_test.go:301
        3 - /mnt/ssd/repositories/nats-streaming-server/server/signal_test.go:140
        4 - /usr/local/go/src/testing/testing.go:909
        5 - /usr/local/go/src/runtime/asm_amd64.s:1357
=== RUN   TestTimeoutReader
```

I run it as documented [here](https://docs.nats.io/nats-streaming-server/install#installing-from-the-source)

```
go test -v -p=1 ./... -sql=false
```

I tried it multiple without success

**Comment by kozlovic** [comment]
@StarpTech Sorry about that. I have PR #1003 to update the test error message. This test starts the server as a separate process in order to send it the SIGTERM signal. So it requires that the server first be installed (`go install`).

**Comment by StarpTech** [comment]
Hi @kozlovic thanks for the quick response. I will test it asap.

**Comment by StarpTech** [comment]
Works :+1:
