### ISSUE TITLE
Clients receiving history

### ISSUE THREAD

**Issue by SkinnySackboy** [nats-io/nats-streaming-server#1005]
We've got a use case where connecting clients need to be able to know when the messages they are receiving are now "live", because they need to be able to be able to bulk process all the historical messages for performance reasons, before processing all newly received messages individually.

Ideally each received message would have an attribute which would indicate a history/live flag to us per client, but the workaround we have found for this is by enable monitoring and having the client query the NATS Streaming Server for each stream sequence number. We then use the sequence number to know whether a message being received is historical/live, with MaxInFlight=1. The only bit that feels weird about this is having all clients access a monitoring web endpoint, but otherwise it works. 

Does anyone know if there is a better solution to this?

Thanks in advance.

**Comment by kozlovic** [comment]
If your clients are "durable" then they don't need to know that since the server will resend only the unacknowledged (redelivered flag should be set) and/or the new messages that this client has not yet received.
Could you describe how is your application handling "old" versus "new" messages?

**Comment by SkinnySackboy** [comment]
Our clients are intentionally not durable as we cannot predict how many users will launch a UI, on how many machines or how many instances. So effectively these clients are intentionally not using durable connections, as every time they connect they need certain data from scratch.

The reason the clients need to know however about the sequence ID of the latest "old" message, is so that from message 0 to <last old message> we can process these in bulk, to avoid spamming the UI with individual updates when the user opens the UI for the first time. This is purely for performance reasons. Any messages after that will simply be processed individually in real time.

Does this make sense, or is there a better technique than having clients query the monitoring web API endpoint to check the sequence number before subscribing? Please do let me know if I haven't explained something clearly.

**Comment by kozlovic** [comment]
Understood. I guess using the endpoint is fine, but if you can't or don't want to, you can always use the `StartWithLastReceived()` start position to know the last sequence in the channel.
The idea is that you could make an helper function that returns you the highest sequence in the channel, or 0 if channel is empty. Such function would do this (in Golang):
```
	ch := make(chan uint64, 1)
	sub, err := sc.Subscribe(channelName,
		func(m *stan.Msg) {
			m.Sub.Unsubscribe()
			ch <- m.Sequence
		},
		stan.StartWithLastReceived(), stan.MaxInflight(1))
	if err != nil {
		sc.Close()
		log.Fatal(err)
	}
	var lastOldestSeq uint64
	select {
	case lastOldestSeq = <-ch:
	case <-time.After(2 * time.Second):
		sub.Unsubscribe()
	}
	// At this point lastOldestSeq is either 0 (there was no message)
	// or the sequence of the last message in the channel at that time.
```
As you can see, we create a subscription with the `StartWithLastReceived()` start position and tell the server to send only 1 message at a time. When this message is received, the subscription is unsubscribed in the callback to avoid repeated invocations (if new message arrive right away) and we put the sequence into a go channel. Then we receive on that channel to get this value, but if there was no message, the call would block there until a message arrives. We use a timeout of 2 seconds (and unsubscribe this helper subscription).
Let me know if this helps.

**Comment by SkinnySackboy** [comment]
Thank you very much @kozlovic that's precisely what I was after.
