### ISSUE TITLE
github.com/nats-io/nats-streaming-server/server.RunServer uses flag.CommandLine

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats-streaming-server#1007]
I have a tiny Go application (single  `main` package) which uses NATS Streaming. I have a very small system test that starts an in-process STAN server using `github.com/nats-io/nats-streaming-server/server.RunServer(...)`. Problem is that my application is using the `flag` package which conflicts with `github.com/nats-io/nats-streaming-server/server`. You can find a condensed test that breaks here: https://gist.github.com/JensRantil/41e0665fafdc7619b786f10ce3577033 The output is
```sh
$ go test .
flag provided but not defined: -test.testlogfile
Usage of /var/folders/jk/zh2vp9qj5n5bpzrgb7t_6p700000gn/T/go-build491094738/b001/yo.test:
FAIL	github.com/JensRantil/yo	0.283s
FAIL
```

I think the possibility of starting an in-process STAN in a Go test is really really nice (and I'm 99% sure my test passed a little less than a year ago). Is it too much to ask that you don't rely on [the global `CommandLine` variable](https://devdocs.io/go/flag/index#pkg-variables) but instead instantiate a [`FlagSet`](https://devdocs.io/go/flag/index#FlagSet)?

In case anyone else is hitting this there are two workarounds for this issue:
 * Move the test to a separate package which isn't relying on `flag.CommandLine`.
 * I, and everyone else depending on `github.com/nats-io/nats-streaming-server/server`, start using `flag.FlagSet` myself.

**Comment by kozlovic** [comment]
Closing since there were no new update for a long time.
