### ISSUE TITLE
Error in K8s Nats streaming

### ISSUE THREAD

**Issue by SidGrundfos** [nats-io/nats-streaming-server#1016]
Hello, When below -
string url = "nats://wwncx1azwe-nats-cluster:4222";
string subject = "foo";
string clientID = "sidd";
string clusterID = "wwncx1azwe-stan-cluster";

I am getting error in
ar c = new StanConnectionFactory().CreateConnection(clusterID, clientID, cOpts)
STAN.Client.StanConnectionException: Invalid connection. ---> NATS.Client.NATSNoServersException: Unable to connect to a server.
Can you please help?

**Comment by kozlovic** [comment]
I will echo this comment: https://github.com/nats-io/nats-operator/issues/126#issuecomment-579836714. It seems that your cluster may not be healthy.
The other thing you need to check is that the `clusterID` must match what you are using when running the NATS Streaming servers.

**Comment by SidGrundfos** [comment]
My scenario is as detailed below -
A function (openfaas)
![image](https://user-images.githubusercontent.com/53938860/73430517-92507080-433e-11ea-9837-428ece00f394.png)

Namespace scoped installation
![image](https://user-images.githubusercontent.com/53938860/73430553-9da39c00-433e-11ea-9041-69a79df12558.png)
![image](https://user-images.githubusercontent.com/53938860/73430560-a300e680-433e-11ea-82f0-79b03b55caf0.png)
![image](https://user-images.githubusercontent.com/53938860/73430569-a85e3100-433e-11ea-8619-d4253c1cc3a0.png)
 am getting the error -
![image](https://user-images.githubusercontent.com/53938860/73430584-b01dd580-433e-11ea-860e-2e63e03df4d6.png)

**Comment by SidGrundfos** [comment]
Its works fine now, it seems I had to add the namespace to the nats url. But now how do I monitor the foo channel or check the messages I am sending?

**Comment by kozlovic** [comment]
To monitor a channel from an administration perspective (not see the content of messages), you can use monitoring endpoint: https://docs.nats.io/nats-streaming-concepts/monitoring.

Otherwise, simply create a non durable subscription starting at the sequence/time you desire for this channel and you should receive the message(s): https://docs.nats.io/developing-with-nats-streaming/receiving

**Comment by SidGrundfos** [comment]
Thanks for the info!
