### ISSUE TITLE
namespaces again

### ISSUE THREAD

**Issue by biskit** [nats-io/nats-streaming-server#1020]
Hi,
Like hear an opinion on how to achieve this without namespaces.

I like to have two environments (say dev/test) operate with the same NATS streaming server (as it's managed by someone else) and not change the application, and they remain logically separate.
As its the same app with the same queuenames, messages cross. 
If I could open a connection with a namespace prefix all messages sent and received with same connection prefix will have that partition of data.

Is there any other way short of prefixing my queues' to achieve this?

thx

**Comment by kozlovic** [comment]
To be honest, you should really have two different clusters, dev and test. They can be running on the same physical server though. In that case, the "separation" comes from the Connect() with a different cluster ID.

Short of that, you can create a thin layer of API that prepends your prefix in the publish and subscribe calls. But although your API will look like they publish on "foo", the real subject would be "prefix.foo", which means that messages presented to the callback would have a subject of "prefix.foo", not "foo".

**Comment by biskit** [comment]
Thanks @kozlovic. Cluster ID should be able to provide me the partition I need!

**Comment by kozlovic** [comment]
> Cluster ID should be able to provide me the partition I need!

But I hope you understand that I wrote that in the context of having two different NATS Streaming clusters, one for dev and one for prod.

**Comment by biskit** [comment]
I think I closed it before reading documentation... Cluster is set at the server level, not at the client level... Means two nats-streaming-servers, different ports (if on same host) etc...

It may not be what I'm looking for as I thought something along these lines...
`stan.Connect("cluster1", "client1", "nats://localhost:4222)`
and
`stan.Connect("cluster2", "client1", "nats://localhost:4222)`

would give me two different clusters. I don't think thats the correct assumption.

**Comment by kozlovic** [comment]
Again, you could have 2 different NATS Streaming clusters (or standalone server to simplify the explanation) running on the same physical machine. The Streaming servers can connect to the same NATS Server if you want to use the same port for all envs.

I would recommend that you read the doc about the concepts, etc of NATS Streaming in relation to core NATS: https://docs.nats.io/nats-streaming-concepts/intro

But back to the original question: if you want the *same* NATS Streaming server/cluster to handle both dev and prod data, you have no choice but to use different channel names. So it means that each channel to have their own prefix. But it really means that the channel names are not the same, so if your applications "hardcode" the subject as "foo" and you want to run against dev or prod, that would not work. I really think that the best approach is 2 different Streaming server/clusters.

**Comment by biskit** [comment]
Thanks @kozlovic. I have come to the same conclusion to soft partition from the client side by setting the equivalent of a namespace in some init() call. That prefixes the channels and the application has to "ask" for a channel. Most of my standard channels are asked by `enum` so the caller does not care what it is.
The rest are temporary channels that have unique names anyways.
