### ISSUE TITLE
GORM implementation for SQL Store

### ISSUE THREAD

**Issue by reidlai** [nats-io/nats-streaming-server#1037]
Is there any plan to migrate NATS streaming sql store to use GORM instead of native sql statement?

**Comment by kozlovic** [comment]
There is no plan at the moment. Looking at GORM, it does adds the sqlite and mssql dialects to the two (postgres and mysql) that NATS Streaming already support "natively". There is quite a limited number of SQL statements and for performance reasons, it is probably easier just to ensure that the statements are correct for a given DB. That being said, there is also no plan to add another SQL database, but it could change.
The only statement that seem to be a bit more difficult to have support for is the "SELECT FOR UPDATE" statement. This is used only in the case where NATS Streaming is running in Fault Tolerant mode.
