### ISSUE TITLE
Whats the largest in production system that uses nats?

### ISSUE THREAD

**Issue by dioptre** [nats-io/nats-streaming-server#1041]
I use nats for work and we've tested load on clients/servers up to 1M transactions per second. I'm interested in streaming and jetstream and want to know how large I can get, and what systems do get in the wild. I hope this will interest others too.

**Comment by kozlovic** [comment]
I am not sure if you are going to get answers here. Maybe slack (https://natsio.slack.com/#/) would be a better avenue since you can reach the community that have experience in using/deploying the products?

**Comment by kozlovic** [comment]
Closing since there were no new update for a long time.
