### ISSUE TITLE
Possible to disable all form of encryption?

### ISSUE THREAD

**Issue by creinholdsson** [nats-io/nats-streaming-server#1045]
I am running nats-streaming-server on startup in an embedded system with low entropy and are experiencing slow startup, due to 
`crypto/rand: blocked for 60 seconds waiting to read random data from the kernel`.

I am running with file store, `--tls=false -secure=false --encrypt=false`.
Is there something else that I am missing disabling related to crypto/rand?

**Comment by kozlovic** [comment]
Unfortunately no, because we use some generation of unique id that uses crypto/rand.  

Looking for that error message, it seems like you would have to install some tools on your host:
https://github.com/DNSCrypt/dnscrypt-proxy/issues/760#issuecomment-472860289
