### ISSUE TITLE
Channelz monitoring - in_msgs & out_msgs

### ISSUE THREAD

**Issue by kmfk** [nats-io/nats-streaming-server#1046]
Similar to #976, I just ran into the issue where I was using `total_msgs` from the `channelz` endpoint to record messages per second per channel, pushing the values to CloudWatch and using a RATE aggregate.

I was really confused today when the channel I was pushing events through to test flatlined in the cloudwatch dashboard, then discovered that `total_msgs` was the count in the store - so there was no more rate of change once it hit its message cap (5mil).

Are you open to adding the same ephemeral in & out metrics for channels?

**Comment by kozlovic** [comment]
You mean `msgs`? There is no `total_msgs` in `channelsz`. You could use `last_seq`, this one will keep increasing. It is true that with limits the `msgs` count will flatline, but last_seq somehow corresponds to the number of messages actually stored in the channel, not counting the ones that have been removed. Let me know if that makes sense.

**Comment by kmfk** [comment]
Ah, yeah, correct, `msgs` from the `channelsz` endpoint - I was looking at #976 and not my code, so just assumed they were the same.

Yeah, I thought about `last_seq` - which I am currently pushing into cloudwatch, I'll give that a go

**Comment by kmfk** [comment]
Confirming - `last_seq` looks like its enough to do what I need. Thanks!
