### ISSUE TITLE
Active Server - Monitoring

### ISSUE THREAD

**Issue by iliesh** [nats-io/nats-streaming-server#1050]
By having multiple nats-streaming-servers in FT configuration would be nice to know from the monitoring page which server is active at the moment.

**Comment by kozlovic** [comment]
This may help you: https://github.com/nats-io/nats-streaming-server/pull/1024
It is in master but not released yet. I may do a release soon, but there has been a report of a defect that I want to fix before next release.

**Comment by kozlovic** [comment]
(note the defect is not related to the isFTActive endpoint)

**Comment by iliesh** [comment]
Perfect, waiting for the next release then.
Thank you.
