### ISSUE TITLE
STAN with db store is dropping connections @58000 subscriptions 

### ISSUE THREAD

**Issue by wutkemtt** [nats-io/nats-streaming-server#1055]
Two days ago we had a failure in our productive NATS-Cluster, running with a STAN node in FT mode. Due to some older misconfigurations in some of the NATS clients we had nearly 58000 subscriptions in the Postgres db store, when the STAN began to drop all the client connections because of heartbeat timeouts, as the log said. The clients tried to reconnect but with no success.
It took us some hours to figure out the cause for the problem. First we thought about some network related latencies or high workloads on the cluster nodes. But in the end there seems to be a magic limit at nearly 58000 subscriptions, because when we deleted some of them manually in the database, client connections could be established again. Finally we decided to restart the whole system based on an empty database and unsurprisingly everything worked.
![NATS_cluster_metrics_1](https://user-images.githubusercontent.com/45697328/83854314-d43b5a00-a716-11ea-9e3c-8e77d2c89288.png)
![NATS_cluster_metrics_2](https://user-images.githubusercontent.com/45697328/83854330-db626800-a716-11ea-9581-ebec55967186.png)
![NATS_cluster_metrics_3](https://user-images.githubusercontent.com/45697328/83854340-ddc4c200-a716-11ea-878a-86264975e86f.png)
![NATS_cluster_metrics_4](https://user-images.githubusercontent.com/45697328/83854344-e0271c00-a716-11ea-8754-99b78da364b0.png)
These screenshots from our metrics dashboard show some very high loads regarding CPU, memory and network, but I don't think, that this the primary reason for the drops.

Below an excerpt of the STAN log at the time of failure.
[stan.log](https://github.com/nats-io/nats-streaming-server/files/4734824/stan.log)

Are there any recommendations regarding size or optimization of a Postgres db store?
Our db store is unlimited at the moment.
If you wish, we could provide a backup of the original database, but it is about 15GB large so I don't know how to share this file.

**Comment by kozlovic** [comment]
So I created a test where I had 6 connections, each one creating 10,000 subscriptions, for a total of 60,000 subscriptions. At first, each app would have its own channel name (so 10,000 per channel) and all 10,000 subscriptions would be a member of the same durable queue group. So when sending a message on "foo", only one of the 10,000 members of the group for channel "foo" would receive it.
I then replace this test with actually 10,000 regular - non durable, non queue - subscriptions on each of the channel. So now when publishing a message on "foo", 10,000 subscriptions receive it.
It was still working, and I ran another app with 10,000 more subscriptions, for a total of 70,000 subscriptions and still work.

Could it be that you have a max subscriptions limit set? (default is 1000, so I had to bump that limit for my test).
Is the number of subscriptions in your case all attached to the same application? Could it be that the application was running our of memory and "crashed", which server would then detect only after timeout HB?

Happy to look at your DB (assuming that I find the way to import it). You can send me an email at "ivan at nats.io" or if you are on Slack, DM me at "Ivan Kozlovic" to figure out a way to transfer/access the DB backup.

**Comment by kozlovic** [comment]
Note that in the test where I have many subscriptions (not queue subs) that all receive the same messages, starting all those clients with each 10,000 subscriptions and server starts deliver those messages, there are so many subscriptions and so many messages sent that the system slow downs and new subscriptions are created very slowly, possibly even time out. Too much contention between looking up messages, delivering, updating subspending, creating subs, etc..
Not sure if this applies to what you have observed or not (that is many subscriptions on the same channel(s)).

**Comment by wutkemtt** [comment]
Thanks for the tests so far. Many of our subscriptions are for the same channel, so yes, this could have influenced the problem.
I am back in the office next week and will contact you for the database backup and transfer possibilities.

**Comment by kozlovic** [comment]
@wutkemtt Ok thanks. But was this situation the result of some misconfiguration or are you planning to have north of 60,000 plain (non queue) subscriptions on the same channel?

**Comment by wutkemtt** [comment]
It's more a kind of client misconfiguration. The normal number of subscriptions per channel is around 50 at the moment.

**Comment by kozlovic** [comment]
From our discussion, after a change in your team's applications, you are now running at a stable ~200 subscriptions and did not suffer any new outage. I am closing this issue for now. Thanks!
