### ISSUE TITLE
Does nats-streaming-server support super clusters like gateways?

### ISSUE THREAD

**Issue by linyuan0** [nats-io/nats-streaming-server#1072]
Gateways can associate the cluster into a super cluster, can nats-stream-server also play such a role?

**Comment by ripienaar** [comment]
Streaming Server uses NATS for communication, so it works on whatever NATS provide. If you have a super cluster, streaming server will work with it.

**Comment by linyuan0** [comment]
@ripienaar thanks.

**Comment by kozlovic** [comment]
I would caution you on what you are trying to do with Streaming across clusters though. It may not be a good idea to have Streaming node from the same cluster spread across clusters.
