### ISSUE TITLE
NATS streaming cluster with ft mode failed to obtain store lock

### ISSUE THREAD

**Issue by demelvin** [nats-io/nats-streaming-server#1074]
Hello Everyone 👋 

I'm currently running [NATS Streaming Cluster with FT Mode](https://docs.nats.io/nats-on-kubernetes/stan-ft-k8s-aws) with [Postgres SQL Store](https://docs.nats.io/nats-streaming-server/configuring/persistence/sql_store) in production. Today I received an alert about the nats streaming pods within the k8s cluster and saw the following errors within their logs:

```
[ERR] STREAM: ft: error attempting to get the store lock: ft: fatal error getting the store lock: sql: error executing "SELECT id, tick from StoreLock FOR UPDATE": read tcp 10.244.0.216:49150->10.244.0.238:5432: i/o timeout
```

Then eventually this...

```
[ERR] STREAM: ft: error attempting to get the store lock: ft: fatal error getting the store lock: pq: sorry, too many clients already
```

I've added the `readTimeout=5s` | `writeTimeout=5s` | `max_connections` as suggested [here](https://docs.nats.io/nats-streaming-server/configuring/persistence/sql_store#read-and-write-timeouts) in hopes this will help prevent this from happening again. **I'm just curious if any else has ever encountered this problem and if so how did you resolve it?**

Thanks in advance for your time.

**Nats Streaming Version**
Docker Image nats-streaming:latest
Embedded Nats Server

**Postgres 12**

**Comment by kozlovic** [comment]
To me it looks like this server was clearly network partitioned: it lost heartbeats from the FT active server and therefore tried to take the active role by updating the SQL `StoreLock` table and failed with an i/o timeout, which means that it was also not able to reach the SQL server, further indicating a network reachability issue.

**Comment by demelvin** [comment]
Thanks for the quick reply. 

I should have mentioned this was happening on all the ft NATS streaming servers. All 3 of them were unable to obtain the lock so none of them could become the leader and take the active role. Killing them and letting them retry did not work either and produced the same errors mentioned in my original post.

All 3 ft nats streaming servers and the Postgres db exist on the same internal network within the k8s cluster and there are no connection restrictions. Only NATS connects to this database store so no external factors at play here. The i/o timeout is a bit misleading because it would seem like a network issue however, I believe these were hanging NATS queries in Postgres. Ultimately this would be a Postgres issue and not NATS streaming issue and those hanging queries should be handled within Postgres by terminating them and removing any table locks.

I just wanted to see if anybody else has experienced this problem and how they handled it.
