### ISSUE TITLE
Super cluster with gateways sending multiple copies

### ISSUE THREAD

**Issue by wilstoff** [nats-io/nats-streaming-server#1083]
Currently we have a super cluster setup with 3 data centers each with 3 nodes each.
Each data center cluster is configured as a cluster within the data center and has gateway configurations for the other data center nodes.
When we have this configuration every stan publish is heard 3 times by subscribers.  If we only have a single cluster with 3 nodes we get the expected behavior of 1 message per publish.  These aren't replayed messages, but it seems like multiple clusters are trying to send the message to the subscriber at the same time.  First off is this a valid configuration or are we using it incorrectly?  What is the recommended configuration for a 3 data center 3 node cluster per data center?  Do we have to do a full mesh cluster?  Note we embed nats and it does not duplicate the message when we publish.
e.g.
```
listen: hostA:4222
http_port: 8222
debug: True
trace: False
max_pending: 268435456
max_payload: 10000000
write_deadline: 5s
cluster: {
  listen: hostA:5222
  routes: [nats-route://hostA:5222, nats-route://hostB:5222, nats-route://hostC:5222]
}
streaming: {
  cluster_id: belvedere_streaming
  store: file
  dir: /var/cache/nats1
  store_limits: {
    ...
    }
  }
  cluster: {
      node_id: A
      peers: [B, C]
      log_path: /var/cache/nats_stream1
  }
}
gateway: {
  name: DATACENTER1
  listen: hostA:7222
  gateways: [{name: "DATACENTER2", urls: ["nats:/hostD:7222", "nats://hostE:7222", "nats://hostF:7222"]}, {name: "DATACENTER3", urls: ["nats://hostG:7222", "nats://hostH:7222", "nats://hostI:7222"]}]
  reject_unknown: True

}
```

may be related to https://github.com/nats-io/nats-streaming-server/issues/1054

**Comment by kozlovic** [comment]
@wilstoff 

>  If it were to monitor the store for additions

Well right now there is no notification from NATS Streaming that channels are added or removed (if using max inactivity). You *can* use monitoring endpoints to get the list of channels and figure out that, but may not be ideal.

> Ideally in a 3 node cluster we'd have one of these replicators on each node, within a common queue group and durable subscriptions. We have a sort of Hub and spoke model, where DC2 connects to DC3 and DC1 directly so we'd need only 3 in DC1/DC3 and 6 in DC2. We'd have to be careful not to duplicate message back though

That's the problem. When a message is say replicated from DC2 to DC1, but in DC1 you have a replicator that replicates to DC2 and DC3, then you would have to be careful to only replicate messages that originated from DC1. That means that you would need some kind of information in each message to include the origin of the cluster - as to suppress replication.

To be clear, often users that use nats replicator is in the context of replicating data from the active cluster to a disaster recovery one, not replicating back and forth from "active/live" clusters.

> Does this seem reasonable to you?

See above. If really those are active clusters and they are meant to be global, then it really looks like this should be a single big cluster, but with the drawbacks that were previously mentioned: RAFT is chatty and sensitive to latency, which is therefore not ideal in WAN networks. If going this way, I would then reduce the cluster size to 3, one on each DC, but the other point is that Streaming cluster works in a way that only the leader handles client messages, which means that producers/consumers that are not in the DC where the leader is running would suffer from having messages sent/received from another DC.

Finally, not sure if you are aware, but we are working on a Streaming 2.0 if you will, that is called JetStream. It is in tech preview stage (single server) and the team is working on clustering at the moment. Depending on how far you are in your design, and what is your deadline, you could have a look at it.

**Comment by wilstoff** [comment]
I haven't looked at jetstream in detail, but plan on doing so once it has clustering support.

So we came to the same conclusion on having to add information about the origin cluster to the topic name, after looking at this article that describes the same issue but within the kafka world: https://www.altoros.com/blog/multi-cluster-deployment-options-for-apache-kafka-pros-and-cons/  With the Active-active configuration all we need to do is prepend the data center's cluster id to any topic published (which is easy because we wrapped the STAN and NATS api with our own).  And then also change the subscription of any topic to subscribe to multiple topics (1 for for each data center prepended with cluster id).

We plan on then figuring out how to dynamically spin up the replicators (easy can watch the cache folder or monitoring endpoints), as well as spin down (harder because max_inactivity won't delete the topic if a replicator still has a subscription to it) when there are no messages.

Ideally if we could hide all of this within nats streaming it would be great.  Basically have some kind of **SuperCluster** mode.
This would hide all the topic differences and present to each subscriber/publisher the topic without clusterid prepended.  It would also allow configuration to point the direction you want the replication to go.  Currently we have a Hub and Spoke model which one data center is the central and the other point inward.  But others may want a more direct connection depending on location of those data center.

Hub and spoke config
```
{
    ClusterId: "dc1"
    SuperClusterMode: on
    Replication: ["dc1->dc2"]
}
{
    ClusterId: "dc2"
    SuperClusterMode: on
    Replication: ["dc2->dc1", "dc2->dc3", "dc1->dc3", "dc3->dc1"]
}
{
    ClusterId: "dc3"
    SuperClusterMode: on
    Replication: ["dc3->dc2"]
}
```

**Comment by kozlovic** [comment]
Hub-and-spoke is not really meant for super-clusters. The design of gateways is for it to form a "full mesh". So if DC1 knows about DC2 and DC2 knows about DC3, then DC1 would try to connect to DC3. I understand that you use "reject unknown", but again, that was not the intent of this boolean: it was meant to prevent unconfigured GW to connect, not to "shape" a desired topology.
For Hub-and-spoke, you may want to look at leafnodes instead.

If you had full mesh gateways, I would have each DC responsible to replicate to the 2 other clusters instead of having DC2 being responsible to replicate DC1 messages down to DC3 and vice-versa.

And there is no plan to add the replicator as part of the streaming server. Not to say that we won't be adding any new feature (outside of bug fixes) to NATS Streaming server, but most of our efforts will go to JetStream.

Anyway, I am closing this issue now since it is understood why the multiple messages came from.

**Comment by wilstoff** [comment]
Ah yes sorry i forgot to mention we'd remove the gateway configuration, and separate the nats server processes from the nats streaming processes.  That way we can configure nats with gateways into a full mesh and perhaps nats streaming into a different model with no connection between clusters outside of these replicators.  But that is a good point on how we are using gateways nats and we should revisit that configuration, although it is working for us now.
