### ISSUE TITLE
MacOS Hostname issue with STAN Container

### ISSUE THREAD

**Issue by ZiQiLN** [nats-io/nats-streaming-server#1089]
I'm starting to experiment with `nats` and there I found (maybe) issue because when I'm running my application on a local machine which connects to `stan` on Docker, there is an issue with my machine hostname, MacOS has a schema like `username.local` and `stan` server disallows using `.` in a hostname.

```
[1] 2020/09/16 03:45:16.998003 [ERR] STREAM: [Client:jay.local-7350] Invalid ClientID, only alphanumeric and `-` or `_` characters allowed
```

What should I do in such a situation? Somebody has a similar issue before?

**Comment by kozlovic** [comment]
You don't have to use the machine hostname for the application's client ID. Please select a client ID that only contains alphanumeric and `-` or `_` characters. If you want to use the hostname to pass as the client ID, then have a little function that replaces all non alpha, `-` and `_` by, say `_`?

**Comment by kozlovic** [comment]
To be clear, this is not an issue in the nats-streaming-server, it is your application selecting a client ID (in the Connect() call) that does not follow the naming rule of only alpha, '-' or '_'.

**Comment by ZiQiLN** [comment]
Thanks, @kozlovic for the informations I think the issue can be closed now since I've resolved the issue, `moleculer` (framework of my application) was automatically setting the hostname as `clientID` and I was wondering what is wrong with that, Issue can be closed actually - thanks for your attention.
