### ISSUE TITLE
Impossible to use bcrypted passwords

### ISSUE THREAD

**Issue by cemremengu** [nats-io/nats-streaming-server#1094]
Whatever I do, I am failing to start servers/use bcrypted passwords. I always get authorization validation error during the startup of the server followed by a shutdown.

Here is my config below:

```
port: 4222
cluster {
  listen: 0.0.0.0:6222
  routes: ["nats://admin:GCWUYepoZ3QFB7daiyID6H@xxxxxx:6222", "nats://admin:GCWUYepoZ3QFB7daiyID6H@xxxxxx:6222"]
}
streaming {
  id: my-cluster
  store: file
  dir: /opt/data
  cluster {
    node_id: "xx01"
    peers: ["xx02", "xx03"]
  }
}
authorization {
  user: admin
  password: $2a$11$akH6gDJ2QZ0GdTev7T5HmeeS8HubDv4orLOX3jviSviID5jdjmTC2
}
```
I use plain text passwords for routes and bcrypted password for the auth section. However, it fails everytime. If I use plain text password in the auth section, it works fine.

```
[1] 2020/10/05 13:55:34.267900 [TRC] 127.0.0.1:48180 - cid:1 - ->> [-ERR Authorization Violation]
[1] 2020/10/05 13:55:34.268312 [DBG] 127.0.0.1:48180 - cid:1 - Client connection closed: Authentication Failure
[1] 2020/10/05 13:55:34.268844 [INF] STREAM: Shutting down.
[1] 2020/10/05 13:55:34.269172 [INF] Initiating Shutdown...
[1] 2020/10/05 13:55:34.269441 [DBG] Router accept loop exiting..
```

What am I doing wrong?

**Comment by kozlovic** [comment]
Cluster has its own authorization. The fact that you specify the authorization block outside of `cluster{}` means that this is authorization for the clients. NATS Streaming server is a client with regard to NATS Server, so this is why the streaming server fails to start because it does not provide the appropriate password (use command line `-user admin -pass GCWUYepoZ3QFB7daiyID6H`.
If you don't want client/streaming server auth, but just routes, you would need to move the `authorization{}` block inside the top-level `cluster{}` block.

Here are several pointers to authentication in NATS Server/Streaming:
https://docs.nats.io/nats-server/configuration/securing_nats/auth_intro
https://docs.nats.io/nats-server/configuration/clustering/cluster_config
https://docs.nats.io/nats-streaming-server/configuring/tls#authenticating-users

**Comment by cemremengu** [comment]
Thank you so much for the quick reply! You are correct I was doing it wrong. Apologies if this sounds stupid however I still don't understand the effect of the outermost `authorization` block since it doesnt work the way I expect. When should we use the outermost (streaming) authorization  block?

For example:

this works

```js
port: 4222
cluster {
  listen: 0.0.0.0:6222
  routes: ["nats://admin:GCWUYepoZ3QFB7daiyID6H@xxxxxx:6222", "nats://admin:GCWUYepoZ3QFB7daiyID6H@xxxxxx:6222"]
  authorization {
     user: admin
     password: $2a$11$akH6gDJ2QZ0GdTev7T5HmeeS8HubDv4orLOX3jviSviID5jdjmTC2
  }
}
streaming {
  id: my-cluster
  store: file
  dir: /opt/data
  cluster {
    node_id: "xx01"
    peers: ["xx02", "xx03"]
  }
}
```

this also works

```js
port: 4222
cluster {
  listen: 0.0.0.0:6222
  routes: ["nats://admin:GCWUYepoZ3QFB7daiyID6H@xxxxxx:6222", "nats://admin:GCWUYepoZ3QFB7daiyID6H@xxxxxx:6222"]
  authorization {
     user: admin
     password: $2a$11$akH6gDJ2QZ0GdTev7T5HmeeS8HubDv4orLOX3jviSviID5jdjmTC2
  }
}
streaming {
  id: my-cluster
  store: file
  dir: /opt/data
  cluster {
    node_id: "xx01"
    peers: ["xx02", "xx03"]
  }
}
authorization {
     user: admin
     password: random plaintext password here
  }
```
this also works

```js
port: 4222
cluster {
  listen: 0.0.0.0:6222
  routes: ["nats://admin:GCWUYepoZ3QFB7daiyID6H@xxxxxx:6222", "nats://admin:GCWUYepoZ3QFB7daiyID6H@xxxxxx:6222"]
  authorization {
     user: admin
     password: $2a$11$akH6gDJ2QZ0GdTev7T5HmeeS8HubDv4orLOX3jviSviID5jdjmTC2
  }
}
streaming {
  id: my-cluster
  store: file
  dir: /opt/data
  cluster {
    node_id: "xx01"
    peers: ["xx02", "xx03"]
  }
}
authorization {
     user: admin
     password: GCWUYepoZ3QFB7daiyID6H
  }

this DOESNT work, why? It accepts omitting the streaming auth part, it accepts random plain text (incorrect) password but fails to auth on bcrypt:

```js
port: 4222
cluster {
  listen: 0.0.0.0:6222
  routes: ["nats://admin:GCWUYepoZ3QFB7daiyID6H@xxxxxx:6222", "nats://admin:GCWUYepoZ3QFB7daiyID6H@xxxxxx:6222"]
  authorization {
     user: admin
     password: $2a$11$akH6gDJ2QZ0GdTev7T5HmeeS8HubDv4orLOX3jviSviID5jdjmTC2
  }
}
streaming {
  id: my-cluster
  store: file
  dir: /opt/data
  cluster {
    node_id: "xx01"
    peers: ["xx02", "xx03"]
  }
}
authorization {
     user: admin
     password: bcrypt password (same as cluster password or any other bcrypt pass)
  }

**Comment by kozlovic** [comment]
See below, but really all depend what you are passing as a command line argument to start the streaming server:

1. this works (not sure why)

There is no authorization block defined, except for cluster/routes. So you can start the streaming server that will be able to create a connection to the NATS Server (no auth).

2. this also works (not sure why)

The streaming server uses the user/password in the `authorization{}` block to form its URL to connect to the embedded server. In other word, it is going to internally create a connection to: `nats://admin:<plain text password>@localhost:4222`.

3. this also works (I get this)

This is for same reason that 2. You are actually not using bcrypt here, you are defining a user "admin" with password "GCWUYepoZ3QFB7daiyID6H" that the streaming server uses to connect to the NATS server (see point 2. above).

3. this DOESNT work, why? It accepts omitting the streaming auth part, it accepts random plain text (incorrect) password but fails to auth on bcrypt:

See all above and previous answer: you need to add `-user admin -pass GCWUYepoZ3QFB7daiyID6H` to the command line when starting the streaming server.

**Comment by cemremengu** [comment]
Alright now I understand. Looks like the logic behind this mechanism was above my engineering skills so it took me some time 😄 Thank you for your patience!
