### ISSUE TITLE
STAN authentication problem when connecting with NKeys

### ISSUE THREAD

**Issue by SimonVHB** [nats-io/nats-streaming-server#1095]
Hello!

We're setting up a NATS and STAN cluster. The STAN cluster needs to connect to our NATS cluster, obviously. But now I'm having trouble to authenticate, when connecting the STAN cluster to the NATS cluster.

We are using NKeys for authentication, but I can't seem to figure out how to configure STAN correctly.

The NATS auth configuration looks like this:
```
authorization: {

  ...

  STAN: {
    publish: ">"
    subscribe: ">"
  }

  users: [
    ...
    //STAN-SERVER
    {nkey: UDNBXF3RNSPSZZIACU42AQDV7XF6ZLKUSADUGEH3F2HQW3E2PEWN6JIK, permissions: $STAN}
   ...
  ]
}
```

And the STAN config:
```
streaming {
      ...
      credentials: /etc/stan-creds/stan.creds
      ...
    }
```

The file stan.creds contains the NKey seed, corresponding to the user public key for above. I tried various formats, for example
```
SUAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

OR
```
-----BEGIN USER NKEY SEED-----
SUAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
------END USER NKEY SEED------
```

In STAN I get the following (obvious) error:
```
[1] 2020/10/05 15:50:51.725194 [FTL] STREAM: Failed to start: nats: Authorization Violation
```
And in NATS (just the empty quotes after Nkey):
```
[6] 2020/10/05 15:52:24.788799 [ERR] 10.244.0.99:50458 - cid:145 - authentication error - Nkey "" 
```

Is STAN not supporting NKey authentication or am I doing something wrong?

Thanks in advance

**Comment by kozlovic** [comment]
No, simple NKeys are not supported by the NATS Streaming server. If you were to run the NATS Server with operator mode and JWT, you would be able to use the credentials file (that must contain both the JWT and NKey seed).

Simple NKey and JWT are mutually exclusive, that is, the connection to the NATS Server will send a JWT and sign the nonce sent by the server when using the credentials file. To do just NKey we would need a new option that uses the NATS client's NKey() option, where the NKey public key is provided along with a signature that signs the received nonce based on the NKey's private key.

**Comment by SimonVHB** [comment]
Okay thanks! I'll look into doing that then.
Will you ever be looking into supporting NKeys?

**Comment by kozlovic** [comment]
@SimonVHB This would be really easy to add. We would need say "nkey" option in `streaming{}` block. The trick is that we need the private key (the seed). How do we get this in the server is the question: either we do like for user credentials: provide a file name and have it loaded to get the seed but then wipe from memory after we have used to sign.

**Comment by SimonVHB** [comment]
@kozlovic awesome. If I have some free time in the near future, I would maybe look into doing that.
