### ISSUE TITLE
User deletion from nsc

### ISSUE THREAD

**Issue by mixmind** [nats-io/nats-streaming-server#1103]
Hi,

After user deletion via nsc NATS still works with this user, also after restart.
I have nats configured with nats-account-server.
```
# Client port of 4222 on all interfaces
port: 4222

# HTTP monitoring port
monitor_port: 8222

operator: /nsc/accounts/nats/O/O.jwt
resolver: URL(http://nats-account-server:9090/jwt/v1/accounts/)

cluster {
	  listen: 0.0.0.0:6222
	  connect_retries: 10
	  authorization: {
		user: admin
		password: changeit
		timeout: 0
	  }
	  routes = [
		nats://admin:changeit@nats-streaming-2:6222
		nats://admin:changeit@nats-streaming-3:6222
	  ]
}

streaming {
	  id: cluster
	  store: file
	  dir: /data/store
	  credentials: /nsc/nkeys/creds/O/A/U.creds
	  cluster {
		  node_id: "nats_1"
		  bootstrap: true
		  raft_logging: true
		  peers: ["nats_2","nats_3"]
		  log_path: /data/logs
	  }
	  store_limits: {
		  max_age: "336h"
	  }
	  hb_interval: "5s"
	  hb_timeout: "2s"
	  hb_fail_count: 2
	  tls {
		  client_cert: "/data/cert/server-cert.pem"
		  client_key:  "/data/cert/server-key.pem"
		  client_ca: "/data/cert/rootCA.pem"
		  insecure: true
	  }
}

tls {
	  cert_file: "/data/cert/server-cert.pem"
	  key_file:  "/data/cert/server-key.pem"
	  ca_file: "/data/cert/rootCA.pem"
	  insecure: true
}
```
Account server config:
```
nats: {
	  Servers: ["nats-streaming-1:4222","nats-streaming-2:4222","nats-streaming-3:4222"],
      ConnectTimeout: 5000,
	  MaxReconnects: 5,
	  ReconnectWait: 5000,
	  TLS {
		  cert: "/data/cert/server-cert.pem"
		  key:  "/data/cert/server-key.pem"
		  root: "/data/cert/rootCA.pem"
      }
	  UserCredentials: /nsc/nkeys/creds/O/A/U.creds
}
OperatorJWTPath: /nsc/accounts/nats/O/O.jwt
store: {
      nsc: /nsc/accounts/nats/O
	  readonly: false,
	  shard: false
}
http: {
	  host: "0.0.0.0",
	  port: 9090
}
```
It's normal behavior?

**Comment by kozlovic** [comment]
@mixmind To be clear, which user did you remove? User 'U' (the one used by the streaming server?)

I am not too familiar with nsc/account-server, so asking for @aricart here for some help. It is true that trying to mimic what you have done, the nsc user is removed and its jwt no longer found in my ".ngs" subdirectories, however, the creds file in the ".nkeys" are still there (but my env may not be setup properly ;-)). Let's see what he has to say.

**Comment by aricart** [comment]
@mixmind the nats-account-server does not keep track of users. Deleting an user simply removes from from the disk.
To prevent a user from connecting, you need to revoke the user in the account, that will update the account, and allow the server to reject the specified user.

See `nsc revocations add_user -h` for more information.

**Comment by aricart** [comment]
If you want to delete and revoke you can do `nsc delete user --revoke <username>`

**Comment by mixmind** [comment]
> @mixmind To be clear, which user did you remove? User 'U' (the one used by the streaming server?)
> 
> I am not too familiar with nsc/account-server, so asking for @aricart here for some help. It is true that trying to mimic what you have done, the nsc user is removed and its jwt no longer found in my ".ngs" subdirectories, however, the creds file in the ".nkeys" are still there (but my env may not be setup properly ;-)). Let's see what he has to say.

No, another user that i had created for test purpose only. But it's exactly the same behavior like you had(only creds file still alive)

> If you want to delete and revoke you can do `nsc delete user --revoke <username>`

Thanks, I had looked in that sight too=). Just thought maybe there is another way to disable user. Thanks a lot

**Comment by aricart** [comment]
@mixmind actually there is - if your account has signing keys, and you remove the signing key from the account, you'll invalidate all users that were issued with that key. That becomes an easy way to bulk revoke, especially if you rotate keys.

**Comment by kozlovic** [comment]
To circle back, with help from colleagues, I setup all that a bit differently and get the expected behavior.
First, add a system account, with the account's public key of your user's U.creds for instance:
```
operator: /nsc/accounts/nats/O/O.jwt
resolver: URL(http://nats-account-server:9090/jwt/v1/accounts/)
system_account: A...<public key>
```
I then replaced the store definition with something local to the account server:
```
store: {
  dir: "store"
  readonly: false
}
```
Then when after executing the `nsc delete user --revoke -i` command and select the user than a streaming client was using to connect to the server, and pushing the changes: `nsc push -a A -u http://<host>:9090/jwt/v1/`, I could see the update received in the NATS Server and the client getting disconnected.

**Comment by mixmind** [comment]
> To circle back, with help from colleagues, I setup all that a bit differently and get the expected behavior.
> First, add a system account, with the account's public key of your user's U.creds for instance:
> 
> ```
> operator: /nsc/accounts/nats/O/O.jwt
> resolver: URL(http://nats-account-server:9090/jwt/v1/accounts/)
> system_account: A...<public key>
> ```
> 
> I then replaced the store definition with something local to the account server:
> 
> ```
> store: {
>   dir: "store"
>   readonly: false
> }
> ```
> 
> Then when after executing the `nsc delete user --revoke -i` command and select the user than a streaming client was using to connect to the server, and pushing the changes: `nsc push -a A -u http://<host>:9090/jwt/v1/`, I could see the update received in the NATS Server and the client getting disconnected.

Thanks.
Will check it too=)
