### ISSUE TITLE
Question: Rust client

### ISSUE THREAD

**Issue by delucca** [nats-io/nats-streaming-server#1104]
Hey,

I'm reading a lot of good reviews regarding NATS and NATS Streaming. I'm building an event sourcing infrastructure right now, but our main stack is written in Rust.

I was not able to find any NATS Streaming client for Rust. There isn't any?

Any advices in using it? :)

Thanks!

**Comment by wallyqs** [comment]
Hi! As you found out the official Rust client (https://github.com/nats-io/nats.rs) does not have support for it, but there is a community driven one that has support for NATS Streaming (aka STAN) here: https://github.com/mnetship/ratsio.

**Comment by kozlovic** [comment]
As Wally mentioned, we have a RUST client for NATS core and we don't plan to add an official RUST client for NATS Streaming. You can use the community-provided one, or, if you are just starting with NATS Streaming, maybe look at JetStream that will be core-NATS so you may not need a new client for that.

**Comment by delucca** [comment]
@wallyqs thanks for your reply!

@kozlovic thanks for your reply. Just a follow-up question: yes, I'm indeed starting at NATS. I've never heard about JetStream. I've took a look at the main JetStream repository, and it seems like a good alternative. Do you have any benchmark between JetStream and traditional Pubsub alternatives (like Kafka and event NATS Streaming)?

**Comment by kozlovic** [comment]
We don't publish numbers, instead, we try to provide basic benchmark tools that you can use in your own environment. The `nats` executable (from the `jetstream` repository) has a `bench` option. We also have bench tool in almost each of the NATS core/streaming libraries that we support. Rust has one too if I am not mistaken.

**Comment by wallyqs** [comment]
@delucca np, you can find more info about JetStream here: https://github.com/nats-io/jetstream it is the next iteration for NATS Streaming and would not need a NATS Streaming client. This snippet is a bit old but to give you an idea of how it looks when using it from Rust: https://gist.github.com/wallyqs/05516d550b756e8b453394be0e9cbf24#file-jetstream-hello-world-rs

**Comment by delucca** [comment]
Excellent, thanks guys! I'm going to take a look at JetStream. It seems really promissing!

Imwirh JetStream I can publish stream of events, as well as common queue of messages?

**Comment by wallyqs** [comment]
Yes, you can have both push based consumers and pull based consumers.
