### ISSUE TITLE
Nack for events which their process take long time to run

### ISSUE THREAD

**Issue by mehran-prs** [nats-io/nats-streaming-server#1108]
Let's say we set `ack wait` to `5 seconds`(because our handler needs to about 5 seconds to handle that event), so for each event if our handler failed, NATS server should wait for 5 seconds to redeliver it (while our event handler can be failed in the first milliseconds), so all other events in that channel need to wait for 5 seconds (but with `Nack` feature they can wait for just milliseconds), How can we address this issue?

One possible solution can be "push that task into a task queue and return ack immediately" but to do that, we need to a task queue (:

Do you have any solution for that?

Note: my event handler returns ack if the redelivery count is 3 or more.

**Comment by kozlovic** [comment]
For now, as you have noticed, there is no "NAck" feature. I am thinking of adding one. See https://github.com/nats-io/stan.go/issues/167. Will keep this opened for now and hopefully will implement this feature "soon".

I have to mentioned that JetStream has it and also the concept of work-queue that NATS Streaming does not have. So again, if you are just starting with NATS Streaming, you may want to focus on JetStream instead.

**Comment by mehran-prs** [comment]
Thanks,
I saw JetStream and I have three questions: 
- It is not stable yet, can I trust it?
- Can I use it to store all events in all microservices(about 20 microservices, each microservices about 40 event types)?
- Does it is a replacement for NATS streaming?

**Comment by kozlovic** [comment]
> It is not stable yet, can I trust it?

It is available from the main branch or nightly builds and is in tech preview at the moment. Supposed to be officially released by end of this year.

> Can I use it to store all events in all microservices(about 20 microservices, each microservices about 40 event types)?

Not sure what the question is about. But I think that if your use-case worked with NATS Streaming, then it should work with JetStream.

> Does it is a replacement for NATS streaming?

NATS Streaming will still be available and maintained. But the things that users were looking for in Streaming that are missing are in JetStream: worker-queues, part of core NATS and use of 2.0 account/security features (for the last part, it is possible to use account and 2.0 security features with streaming, but it was designed before that and it is a bit more challenging in some cases to add permissions/etc.. with streaming).

**Comment by kozlovic** [comment]
Right. In JetStream you need to pre-create streams, but you have the option to create templates. Check this to see if that satisfies your requirements: https://github.com/nats-io/jetstream#stream-templates

**Comment by ripienaar** [comment]
JetStream also support wildcards so its possible that you might combine many related microservices into one stream - but still be able to access just service specific data by filtering.

Templates as @kozlovic shows is probably best, also note you don't have to pre-create your streams, you can create them on demand first time a service starts by using the API.

**Comment by mehran-prs** [comment]
So thanks, Yes templates are what we need. 
But another question: stream with subject options `{microservice}.*` is a bad practice?
How about just one stream for all of the microservices (steam with subjects option equal to `myproject.*`)?

**Comment by mehran-prs** [comment]
Thanks, I got what I needed.
