### ISSUE TITLE
NATS Streaming Server with FIPS 140-2 Support

### ISSUE THREAD

**Issue by jfathman** [nats-io/nats-streaming-server#1111]
Is there any possibility of NATS Streaming Server with FIPS 140-2 (140-3) support?

That is hard to do since NATS Streaming Server is written in Go, and TLS and crypto is embedded within Go lang, not dynamically linked OpenSSL, etc.

But government and healthcare are requiring FIPS more and more, so NATS may need a FIPS story for design wins in that space.

Since FIPS certification is costly, this could be a revenue opportunity for Synadia.  Customers would pay a reasonable license fee for a NATS FIPS solution.

Is FIPS support on the NATS radar?

Are there known clever ways to proxy NATS Streaming Server traffic so it can be externally transported via FIPS certified TLS?

Thanks for NATS.  Great technology.

**Comment by kozlovic** [comment]
Thank you. Looping @ColinSullivan1 and @derekcollison for their feedback.

**Comment by derekcollison** [comment]
We have worked with other users and customers on how they could utilize ciphers etc not directly supported by NATS or the client implementations. 

We do not have any current plans to add FIPS to the opensource project but I would tend to agree that the ability to possibly produce a version with it may be interesting from a business perspective.

**Comment by kitplummer** [comment]
> We do not have any current plans to add FIPS to the opensource project but I would tend to agree that the ability to possibly produce a version with it may be interesting from a business perspective.

FYSA - Confluent has FIPS 140-2 in/for Kafka.  That reason alone is getting them into conversations.  Seems like its an easy justification from a BD perspective (with peeps that care about FIPS 140-2 :))

**Comment by derekcollison** [comment]
It is something we are considering at Synadia. Will not be part of OSS offering most likely..
