### ISSUE TITLE
Is it possible to use SQL Server as DB Store for NATS streaming server?

### ISSUE THREAD

**Issue by hanxinimm** [nats-io/nats-streaming-server#1113]
.NET developing is better to use SQL Server DB

**Comment by kozlovic** [comment]
The Streaming server uses Postgres ("github.com/lib/pq") and MySQL ("github.com/go-sql-driver/mysql") drivers to connect to SQL databases. You can't use a SQL Server that does not support any of those drivers.
You can try to add the library for a specific SQL server in `nats-streaming-server.go` and `stores/sqlstore_test.go` and see if all SQL tests pass:

**Comment by kozlovic** [comment]
But it is unlikely that you can simply add a driver without adding/modifying rest of the code. So it either works with current drivers (for instance some DB work with mysql or postgres drivers) or it does not.

**Comment by kozlovic** [comment]
Closing this issue for now.
