### ISSUE TITLE
Migration between persistence options (File Store and SQL Store)

### ISSUE THREAD

**Issue by peteychuk** [nats-io/nats-streaming-server#1115]
Hey,

Is it possible to migrate from File Store to SQL Store or backward without losing any data?

Thank you in advance.

**Comment by kozlovic** [comment]
@peteychuk Unfortunately there is no tool (that I am aware of) to do that.

**Comment by PBug90** [comment]
Is it possible to spin up a new node that has SQL store configured, join the cluster, and step by step add more SQL nodes until file store nodes are no longer needed?

**Comment by kozlovic** [comment]
@PBug90 Since with latest releases there is a way to add/remove nodes with system admin messages, it may be a way to do that! Now, keep in mind that in cluster mode, we still need file storage for the RAFT logs (these have not been implemented to be backed by SQL), so usually users don't go the cluster-mode with SQL.
But if that limitation is not an issue for you, your approach seem promising, although I have not tested it.

**Comment by PBug90** [comment]
Do you have plans on implementing SQL as a persistence layer for RAFT messages aswell or are there major caveats that would render it inefficient?

**Comment by kozlovic** [comment]
@PBug90 There is no plan at the moment. Note that JetStream is our new persistence product, and that's where most of new dev will go, not to say that we won't add new features to NATS Streaming, but this is not the priority.
However, JetStream is also RAFT based but does not have SQL support at all at the moment (either for RAFT or NATS messages).

**Comment by apuatcfbd** [comment]
hi, is there any reason behind the decision not to use SQL for persistence? I like to use SQL (and)or Redis to persist data.

**Comment by kozlovic** [comment]
@apuatcfbd Is this question related to NATS Streaming server or you mean JetStream? If the former, the project is no longer supported. If the latter, then please open the question in the NATS Server repository. But in short, and as far as I know, there is no plan, or at least no immediate plan to support SQL for data persistence.
