### ISSUE TITLE
how to achieve "at least once delivery" ?

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-streaming-server#1120]
nats streaming save messages say in a file store and replay msgs at a later moment.
what if SPOF(single point of failure) happens, and file lost ?

**Comment by kozlovic** [comment]
Run a cluster with data replication. A cluster of 3 nodes allow for 1 node to be lost and still continue. Restarting the node that failed (without any state) would work and data would be recovered from the rest of the cluster. See https://docs.nats.io/nats-streaming-concepts/clustering.

Note that running in cluster mode is slower than standalone and/or FT. Keep the number of nodes small, such as 3 or at most 5.
