### ISSUE TITLE
can channle be handled in more than one server ?

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-streaming-server#1124]
hello, in Partitioning mode, can channle be handled in more than one server ?
if can, when publishing a message to the channel, only one server receive the message, or all servers handling the channel receive same copy of the message ?

thanks.

**Comment by kozlovic** [comment]
No, the point of partitioning is to separate the responsibilities of a server to handle only a subset of channels. So for instance you can configure server to handle "foo" and "bar" and another to handle "baz". The first server will only "listen" to messages sent on "foo" and "bar" while the second will listen to "baz". From the client perspective, it does not matter. The messages will be routed to proper streaming servers (of course it means that the 2 streaming servers would be connected through NATS).
