### ISSUE TITLE
stan: invalid subject 

### ISSUE THREAD

**Issue by Ssabuwala** [nats-io/nats-streaming-server#1129]
My Requirement is the subject name is start with "/"(forward slash) but every time I got this error.
can you tell me should we use the subject name to start with "/"(forward slash)?
subject name : /hi
Python version: 3.7
nats-streaming-server version 0.18.0, nats-server: v2.1.7

Traceback (most recent call last):
File "nats_testing.py", line 45, in
loop.run_until_complete(run(loop))
File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
return future.result()
File "nats_testing.py", line 31, in run
sub = await sc.subscribe("/hi", start_at='first', cb=cb)
File "/home/shalin/.local/lib/python3.7/site-packages/stan/aio/client.py", line 510, in subscribe
raise StanError(resp.error)
stan.aio.errors.StanError: stan: invalid subject
[nats-streaming-server-Test.txt](https://github.com/nats-io/nats-streaming-server/files/5646671/nats-streaming-server-Test.txt)

**Comment by kozlovic** [comment]
NATS Streaming Server will reject any channel that contains a `/` because when using persistence, channels are stored on disk, which would not work since this is used as separator.
