### ISSUE TITLE
How to consume in batchs with nats streaming

### ISSUE THREAD

**Issue by heliusjing** [nats-io/nats-streaming-server#1130]
How to consume in batchs with nats streaming
i mean MessageHandler paramter is One Message ,Not a message list

**Comment by kozlovic** [comment]
There is no such option in any of the NATS clients (streaming or core NATS). Note that messages may already be waiting in internal queues of the client library, so although the message callback is invoking user code with one message at a time, it does not mean that the library has to fetch the next message when the callback returns. This is driven by the subscription's MaxInflight value. The default is 1024.

You can always create the subscription with manual ack mode, and in the message callback push the messages to a queue/array that is then processed as a batch in your own go routine/thread.

There is no current plan to add a new message callback with a list/array of messages.
