### ISSUE TITLE
is it true about nats streaming?

### ISSUE THREAD

**Issue by alifpay** [nats-io/nats-streaming-server#1131]
Do you agree with this comparison?

https://softwaremill.com/mqperf/

Will performance of Jetstream be like kafka?

**Comment by kozlovic** [comment]
Difficult to say. I have checked the source code for tests, but this is using Scala, which I am not familiar with, and there are some choices that I am not sure are really helping for NATS Streaming for sure. I have created an "issue" in that repo to have some clarification about the use of the async publishers: https://github.com/softwaremill/mqperf/issues/52.

As for JetStream, no idea about the performance at this point. Clustering is in the work as I type, so until then, there would be no comparison (only single server currently).

**Comment by adamw** [comment]
I'm not familiar with JetStream, but one of the major differences comparing Kafka to NATS Streaming is that in Kafka we've got 3 active servers, while in NATS 1 active & 2 passive. Kafka has then the potential to parallelise message sends acknowledgments. Also, when receiving, in NATS we can acknowledge individual messages, while in Kafka we only have up-to-offset confirmation - which puts less load on the Kafka servers (but is a different way to do messaging)

**Comment by kozlovic** [comment]
@alifpay So, as always, you need to evaluate which messaging system best fits your needs, which may be different than other users. In some cases it could be raw performances, or features, or ease of deployment/maintenance, etc..
As for JetStream, it is too early to have any number since the clustering work has not landed yet.
