### ISSUE TITLE
sql store performance enhancement

### ISSUE THREAD

**Issue by carr123** [nats-io/nats-streaming-server#1132]
hi, i read the nats-streaming-server sql store souce code.  it seems that, a sql transaction is used (begin, preparedStmts, commit) to bulk insert messages.
but , i think this kind of bulk insertion [insert into tb values(1, 'a'),(2,'b'),(3,'c')] is more performant than the above.

**Comment by kozlovic** [comment]
I will dig deeper into it. A quick test shows about a 4x gain, which is good!

**Comment by carr123** [comment]
bulk insertion NOT within another transaction seems fastest.
hope it helps.

**Comment by kozlovic** [comment]
@carr123 Understood.
