### ISSUE TITLE
Is there a way to ensure that unconsumed messages are not discarded in storage? Even if size or age reaches the limit

### ISSUE THREAD

**Issue by GuangchaoDeng** [nats-io/nats-streaming-server#1147]
Is there a way to ensure that unconsumed messages are not discarded in storage? Even if size or age reaches the limit

**Comment by kozlovic** [comment]
Unfortunately no. If you want to make sure that messages are removed only when they have been consumed, you probably need to look at JetStream. It is on tech preview at the moment and should be GA with our NATS Server 2.2.0 release that is due sometime this or next month.
NATS Server (including JetStream): https://github.com/nats-io/nats-server
Some JetStream documentation: https://github.com/nats-io/jetstream

**Comment by GuangchaoDeng** [comment]
@kozlovic thanks
