### ISSUE TITLE
Migration of a standalone instance to a cluster

### ISSUE THREAD

**Issue by timjohncurtis** [nats-io/nats-streaming-server#1172]
our production environment currently uses a legacy standalone nats streaming instance that we need to migrate to a cluster, is there any documentation or can anyone provide any feedback or experience with this process? We would like to migrate existing channels / queues over with the subscription IDs if at all possible.

I have tried migrating the file store over from the standalone instance but am getting 
```
[11071] 2021/03/10 14:37:02.540853 [FTL] STREAM: Failed to start: stan: cannot restart server in clustered mode if it was not previously clustered
```

I am also currently looking at a replicator service as an alternative to replicate messages from the standalone node to a fresh cluster.

Any feedback would be greatly appreciated.

**Comment by kozlovic** [comment]
Sorry, but there is no automation to move from standalone to clustering. I don't think you would be able to transition and keep the subscription IDs.
You could have the standalone server, then setup a cluster, and have an application consume from standalone and push messages to the cluster.
For subscriptions, you would have to start at sequence that you want them to start (to avoid replaying everything).

But in summary, there is unfortunately no easy way to do what you want. Sorry about that.

**Comment by timjohncurtis** [comment]
Okay, thats what we thought for this case. Thank you for getting back to me, I'll close this issue off 👍
