### ISSUE TITLE
Conditional publishing depending on sequence

### ISSUE THREAD

**Issue by fanie42** [nats-io/nats-streaming-server#1173]
I would like to use NATS Streaming as an event store/bus in an event sourcing context. I think it is very well suited to the problem except for one thing: Concurrent writes/publishes to the same channel (DDD: for the same aggregate). Is there some way to specify the expected sequence of the message being published by the client and have the server reject the message if it doesn't match the next sequence in the store? That way the publisher can receive a "not acknowledged" message from the server, update the aggregate by applying the new messages/events and retry the command operation.

The big problem here is that the write to the store and sequence check needs to happen atomically and the message should only be persisted and published if the check/store operation succeeded.

**Comment by wallyqs** [comment]
Not in NATS Streaming, you would find something similar in the JS project for NATS: https://github.com/nats-io/jetstream#publish-expectations-and-constraints

**Comment by kozlovic** [comment]
As Wally suggested, this feature is present in JetStream, but not NATS Streaming.

**Comment by fanie42** [comment]
Awesome, thank you for the swift reply!
