### ISSUE TITLE
Not able to see nats subscription started/removed logs when nats connection is created

### ISSUE THREAD

**Issue by vishaltripathi24** [nats-io/nats-streaming-server#1178]
Not able to see nats subscription started/removed logs when nats connection is created/closed respectively, like I see them for nats streaming.

`[1] 2021/04/14 16:07:44.572218 [DBG] STREAM: [Client:test-1_1] Started new subscription, subject=test-1, inbox=_INBOX.k0S0LlQ9UnN6jRHcAksiUV, subid=5, sending from sequence, asked_seq=16 actual_seq=16
[1] 2021/04/14 16:08:20.767822 [DBG] STREAM: [Client:test-1_1] Removed subscription, subject=test-1, inbox=_INBOX.k0S0LlQ9UnN6jRHcAksiUV, subid=5`

Tried enabling -D option in configuration file, all I see is connection created.
`[1] 2021/04/15 12:47:38.292625 [DBG] 10.138.104.110:54478 - cid:8 - Client connection created`

**Comment by kozlovic** [comment]
@vishaltripathi24 If I understand correctly you want to see the NATS core subscriptions? In NATS, you would see the subscriptions only on with trace level `-V`. Note that if you run NATS Streaming in cluster mode, there will be lots of NATS messages exchanged (with RAFT) even if your application does not have much. So your logs will grow quickly :-)

**Comment by vishaltripathi24** [comment]
@kozlovic Yes I want to see NATS core subscriptions and I was able to see the below logs with level -V. Were you referring to the same for a subject named test?

`[1] 2021/04/15 19:44:53.337988 [TRC] 10.138.104.110:59241 - cid:6 - <<- [SUB test  1]
[1] 2021/04/15 19:45:08.422672 [TRC] 10.138.104.110:59241 - cid:6 - <-> [DELSUB 1]`

Yes that will be too many logs.
Can they be included in debug like nats streaming subscription logs, if not then is there a reason behind it?? We need these logs to automate our test cases.

Note : Nats streaming docker version 0.16.2

**Comment by kozlovic** [comment]
Note that if you subscribe on streaming to "test", streaming does NOT create a core subscription on "test", the client is actually the one creating a subscription and it will be on some "_INBOX".
There is no plan to change NATS core subscription trace level to a debug (that would be too much for debug level).
