### ISSUE TITLE
publish to multiple subject lead to slower QPS

### ISSUE THREAD

**Issue by hl3w22bupt** [nats-io/nats-streaming-server#1186]
In purpose to boost my throughput, I decided to publish messages to multiple topic like foo-1, foo-2, foo-3 to makes it work like kafka topic partition.  but it even more lower QPS. 

FYI, I used golang stan sdk, and one publish client. in my test, I found single publish() will take more and more time. that really confused me.

**Comment by kozlovic** [comment]
> I decided to publish messages to multiple topic like foo-1, foo-2, foo-3 to makes it work like kafka topic partition. but it even more lower QPS.

More lower compared to what?

>  I found single publish() will take more and more time. that really confused me.

Publish() is a request/reply, so from the same connection, the amount of publish() you can do a second will really be limited. However, there is no obvious reason why the performance of a publish() should degrade. If you could describe your configuration (server/client) maybe we could help? Has the channel more and more subscribers which would cause a published message to be delivered to more and more consumers (which would make each publish slower and slower), etc..

**Comment by hl3w22bupt** [comment]
Compared with publishing message to single topic foo, publish message to foo_1, foo_2, foo_3 in roundrobin way is slower.

There is only one subscriber which subscribes foo_1, foo_2, foo_3. 

nats streaming server config:

> server_name: stan
> host: 0.0.0.0
> port: 4222
> http_port: 8222
> 
> streaming {
>   id: stan
>   store: file
>   dir: datastore
>   store_limits: {
>     max_channels: 20
>     max_bytes: 0
>     max_msgs: 0
>     max_age: "1h"
>   }
> }

**Comment by kozlovic** [comment]
> Compared with publishing message to single topic foo, publish message to foo_1, foo_2, foo_3 in roundrobin way is slower.

I would appreciate that you show me how you are doing this and how did you measure. Here is a sample that I used to check if 1 single topic or many were different:
```
single := false

subjs := []string{"foo_1", "foo_2", "foo_3"}
max := len(subjs)
if single {
    max = 1
}
start := time.Now()
for i := 0; i < 50000; i++ {
    err = sc.Publish(subjs[i%max], msg)
    if err != nil {
        log.Fatalf("Error during publish: %v\n", err)
    }
}
log.Printf("Perf: %v", time.Since(start))
```
I run with `single := false` and then `single := true` and have virtually the same duration.
Note that on macOS, the file sync is extremely penal, so I ran with lower iterations, or with 50000 but with `-file_sync=false`.

> There is only one subscriber which subscribes foo_1, foo_2, foo_3.

One subscriber per channel you mean.

I have tried that too, when `single := true`, I run a single subscription on `foo_1`. If I run with `single := false`, I run 3 subscriptions, one on each `foo_` subject (for that test, I bump to 50001 to get an even number for each sub).

**Comment by hl3w22bupt** [comment]
@kozlovic thanks so much. I change the sync_on_flush=false, and it works well. 

when use default setting sync_on_flush=true, multiple topic works a little worse than single topic

**Comment by hl3w22bupt** [comment]
@kozlovic thanks so much. I change the sync_on_flush=false, and it works well. 

when use default setting sync_on_flush=true, multiple topic works a little worse than single topic
