### ISSUE TITLE
Unable to host Nats Streaming Server on Windows using configuration file

### ISSUE THREAD

**Issue by somnathnitb** [nats-io/nats-streaming-server#1187]
I am trying to host NATS streaming server using on windows as windows service with NATS configuration file as stan config. Service creation is success however when I try to start I get "1053: service did not start or respond to control request timely". When I run the exact same command on powershell or commandline it works fine. 
Below is my service creation command
```
sc.exe create my-data-streaming-server binPath="\"<streamingexepath>\" --stan_config <configFilePath>"
```

Stan configuration file content 
```
tls: {
        cert_file: "./certificate/data-streaming-server.crt"
        key_file: "./certificate/data-streaming-server.key"
        verify: true
        timeout: 2
    }
authorization: {
    users: [
    {
        user: "<user>"
    },
    {
        user: "<user>"
        password: "<password>"
        permissions: {
                publish: ">"
                subscribe: ">"
            }
    }
    
    ]
}

streaming: {
    cluster_id: <clustername>
    store: "file"
    dir: "<data_file_path>"
    secure: false
    user:"<serverUser>"
    tls: {
        client_cert: "./certificate/data-streaming-server.crt"
        client_key: "./certificate/data-streaming-server.key"
        server_name: "<serverName>"
        insecure: false
    }
    store_limits {
        max_msgs: 0
        max_bytes: 10GB
        max_age: "48h"
        max_inactivity: "12h"
    }

}
```

Thanks in advance.

**Comment by kozlovic** [comment]
@somnathnitb Have you checked the event log to see what error is being reported? It could be that the directories for tls certs should be fully qualified.

**Comment by somnathnitb** [comment]
Yes I have been looking into event viewer and there was not much logged there. But you are right cert directories should be fully qualified. That solved the issue. Thanks.
