### ISSUE TITLE
Publishing via EncodedConn does not persist in store (postgresql)

### ISSUE THREAD

**Issue by rammanavalan** [nats-io/nats-streaming-server#1202]
This is either an issue or an unimplemented feature. Since I did not find any documentation on this, I am raising this issue.

I followed the steps similar to what are mentioned in https://docs.nats.io/developing-with-nats/sending/structure and https://docs.nats.io/developing-with-nats/receiving/structure. 

I started my nats-server as below:
docker run -p 4222:4222 -ti nats-streaming:latest  -store SQL --sql_driver postgres  --sql_source="user=postgres password=password host=$DOCKER_BRIDGE_IP port=54320 sslmode=disable" 

Started my subscriber as below (in nats-streaming-server/vendor/src/github.com/nats-io/stan.go/examples/stan-sub):
go run main-json.go --all -c test-cluster -id myID foo

I was able to successfully publish and could see that it is received on the subscriber side (with the values getting printed in console). However, I couldnt find any new row added in the Messages table in Postgresql. Earlier, when I had not used the EncodedConn (JSON) but used the stan.Connect method to connect, I was able to see a new row added to the Messages table.

My question: Is persistence (in store - postgresql) not supported if we use EncodedConn? Or am I missing something?

Note: I skimmed through the nats-streaming source and found that EncodedConn does not use a sql driver, whereas stan.Connect does.

**Comment by kozlovic** [comment]
How did you actually publish? Using the stan connection? Streaming uses protobuf to encode messages, so EncodedConn is not supported. I am surprised that you even received the message in the first place.

**Comment by rammanavalan** [comment]
from nats-streaming-server/vendor/src/github.com/nats-io/stan.go/examples/stan-pub, I ran the command below. 
go run main.go foo

I did not sure stan.connection. I modified main.go, as per https://docs.nats.io/developing-with-nats/sending/structure:
```
nc, err := nats.Connect(URL, opts...)
sc, err := nats.NewEncodedConn(nc, nats.JSON_ENCODER)
type stock struct {
    Symbol string
    Price  int
}
err = sc.Publish(subj, &stock{Symbol: "GOOG", Price: 1200})
```
And it worked.

So, what I infer from your reply is that, if I use nats-streaming, I cannot use JSONEncoder, instead, I should stan.Connect only. If I have to send publish a json, then I should marshal (struct to []byte) on the publisher side, publish the []byte using stan.Connect Publish, and unmarshal on the subscriber side. Am I right?

**Comment by kozlovic** [comment]
This is not possible since NATS and STAN do not share the same subject space. So if you published above to "foo", then the Streaming server will not receive this message since it is listening on something like `_STAN.<cluster name>.pub.>`.

In the publisher code above, you are not using any Streaming connection at all, so there is no way this goes into NATS Streaming server and its subscriptions. I suspect that you did not also use a streaming connection to subscribe.

What you did is simply to use core NATS that happens to connect to the embedded NATS Server or the streaming server (see the pic in this page: https://docs.nats.io/nats-streaming-concepts/intro).

So to answer your question:

> So, what I infer from your reply is that, if I use nats-streaming, I cannot use JSONEncoder, instead, I should stan.Connect only. If I have to publish a json, then I should marshal (struct to []byte) on the publisher side, publish the []byte using stan.Connect Publish, and unmarshal on the subscriber side. Am I right?

Yes, you are right.

**Comment by rammanavalan** [comment]
Yes, as I had mentioned earlier, I followed the steps mentioned in https://docs.nats.io/developing-with-nats/receiving/structure on the subscriber side, which does not use STAN. Thank you for your help.
