### ISSUE TITLE
stan: connection closed Problem

### ISSUE THREAD

**Issue by Admiralkheir** [nats-io/nats-streaming-server#1216]
Hi,
We are using 2 servers as ft mode. We do not have a problem on the server side. On the application side sometimes the "stan: connection closed" problem occurred then we were deploying the application again and fixed but we do not know why this happens.

when the problem started server logs;

For Active Server: (UTC)-A
> [3355] 2021/10/16 20:02:25.943278 [INF] B:59840 - rid:3325 - Route connection created
> [3355] 2021/10/16 20:02:25.947424 [INF] B:59840 - rid:3325 - Router connection closed: Duplicate Route
> [3355] 2021/10/16 20:02:27.013641 [INF] B:59842 - rid:3326 - Route connection created
> [3355] 2021/10/16 20:02:27.013787 [INF] B:59842 - rid:3326 - Router connection closed: Duplicate Route
> [3355] 2021/10/16 20:02:28.043666 [INF] B:59844 - rid:3327 - Route connection created
> [3355] 2021/10/16 20:02:28.043829 [INF] B:59844 - rid:3327 - Router connection closed: Duplicate Route
> [3355] 2021/10/16 20:02:29.103899 [INF] B:59846 - rid:3328 - Route connection created
> [3355] 2021/10/16 20:02:29.104050 [INF] B:59846 - rid:3328 - Router connection closed: Duplicate Route
> [3355] 2021/10/16 20:02:30.172082 [INF] B:59848 - rid:3329 - Route connection created
> [3355] 2021/10/16 20:02:30.172272 [INF] B:59848 - rid:3329 - Router connection closed: Duplicate Route
> [3355] 2021/10/16 20:02:30.695276 [INF] B:47818 - rid:19 - Router connection closed: Read Error
> [3355] 2021/10/16 20:02:31.219332 [INF] B:59850 - rid:3330 - Route connection created
> [3355] 2021/10/16 20:02:31.766872 [INF] B:6222 - rid:3331 - Route connection created
> [3355] 2021/10/16 20:02:31.767333 [INF] B:6222 - rid:3331 - Router connection closed: Duplicate Route
> [3355] 2021/10/16 20:09:00.546382 [ERR] STREAM: [Client:6UD1196E0TF47S7W81OG] Timed out on heartbeats
> [3355] 2021/10/16 20:09:00.546535 [ERR] STREAM: [Client:14XM5IXUD0PH7A21FR6T] Timed out on heartbeats
> [3355] 2021/10/16 20:09:00.546569 [ERR] STREAM: [Client:DOJ0V451LDI390TRDO83] Timed out on heartbeats
> [3355] 2021/10/16 20:09:00.546581 [ERR] STREAM: [Client:CKAK8DXSOZ4F1CHLWXPB] Timed out on heartbeats
> [3355] 2021/10/16 20:09:00.556144 [ERR] STREAM: [Client:T9Z9RFBPWV5N7M245VQ0] Timed out on heartbeats
> [3355] 2021/10/16 20:09:00.556166 [ERR] STREAM: [Client:0XZPTCI758A7X8RLL946] Timed out on heartbeats
> [3355] 2021/10/16 20:09:00.556173 [ERR] STREAM: [Client:Y67DE8CAPB9K03S7W2ZU] Timed out on heartbeats
> [3355] 2021/10/16 20:09:00.556180 [ERR] STREAM: [Client:JSZ698Q5T3YLW0T5W99I] Timed out on heartbeats
> [3355] 2021/10/16 20:09:00.556190 [ERR] STREAM: [Client:M43S6XOQ4ZE61853HKKP] Timed out on heartbeats
> [3355] 2021/10/16 20:09:02.592686 [ERR] STREAM: [Client:WBSFPWVPDJ0Q652JO44V] Timed out on heartbeats
> [3355] 2021/10/16 20:09:07.149297 [ERR] STREAM: [Client:9QKRHDTD8L4X78Y3NTT9] Timed out on heartbeats
> [3355] 2021/10/16 20:09:07.157413 [ERR] STREAM: [Client:ZBWWNUKB4179UANW4F5S] Timed out on heartbeats
> [3355] 2021/10/16 20:09:07.162677 [ERR] STREAM: [Client:EHVVLSS1I4LEO3MDNINZ] Timed out on heartbeats
> [3355] 2021/10/16 20:09:11.405275 [ERR] STREAM: [Client:0FTL6N6IFBEE81H2NVD9] Timed out on heartbeats
> [3355] 2021/10/16 20:09:11.409502 [ERR] STREAM: [Client:JKU8Y5L9OM3NDU44UEGV] Timed out on heartbeats
> [3355] 2021/10/16 20:09:16.262424 [ERR] STREAM: [Client:G2Q7BR0DY6PLXW3XJIP3] Timed out on heartbeats
> [3355] 2021/10/16 20:09:16.262693 [ERR] STREAM: [Client:4EQ400VX39D33NXJZ9N7] Timed out on heartbeats
> [3355] 2021/10/16 20:09:16.267857 [ERR] STREAM: [Client:9NHHY32B45X1GW1RBPIO] Timed out on heartbeats
> [3355] 2021/10/16 20:09:28.648649 [ERR] STREAM: [Client:Z76JDB0BWCGYAR502BBQ] Timed out on heartbeats
> [3355] 2021/10/16 20:09:30.756789 [ERR] STREAM: [Client:URGQ605M7TKQ3RC6IZX4] Timed out on heartbeats
> [3355] 2021/10/16 20:09:34.203643 [ERR] STREAM: [Client:S710S6KNA0WMLCEZ5C53] Timed out on heartbeats
> [3355] 2021/10/16 20:09:34.203744 [ERR] STREAM: [Client:M9NGONGLPNRB15DG38S9] Timed out on heartbeats

For Failover Server: (UTC)-B

> [3855] 2021/10/16 20:02:01.378770 [INF] A:6222 - rid:1 - Router connection closed: Read Error
> [3855] 2021/10/16 20:02:01.883427 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
> [3855] 2021/10/16 20:02:03.013371 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
> [3855] 2021/10/16 20:02:03.398561 [ERR] Error trying to connect to route (attempt 1): dial tcp A:6222: i/o timeout
> [3855] 2021/10/16 20:02:05.275010 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
> [3855] 2021/10/16 20:02:05.400685 [ERR] Error trying to connect to route (attempt 2): dial tcp A:6222: i/o timeout
> [3855] 2021/10/16 20:02:07.402699 [ERR] Error trying to connect to route (attempt 3): dial tcp A:6222: i/o timeout
> [3855] 2021/10/16 20:02:09.403615 [ERR] Error trying to connect to route (attempt 4): dial tcp A:6222: i/o timeout
> [3855] 2021/10/16 20:02:09.798428 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
> [3855] 2021/10/16 20:02:10.407646 [INF] A:6222 - rid:3241 - Route connection created
> [3855] 2021/10/16 20:02:10.410195 [INF] A:6222 - rid:3241 - Router connection closed: Read Error
> [3855] 2021/10/16 20:02:11.476094 [INF] A:6222 - rid:3242 - Route connection created
> [3855] 2021/10/16 20:02:11.476815 [INF] A:6222 - rid:3242 - Router connection closed: Client Closed
> [3855] 2021/10/16 20:02:12.505986 [INF] A:6222 - rid:3243 - Route connection created
> [3855] 2021/10/16 20:02:12.506668 [INF] A:6222 - rid:3243 - Router connection closed: Client Closed
> [3855] 2021/10/16 20:02:13.566207 [INF] A:6222 - rid:3244 - Route connection created
> [3855] 2021/10/16 20:02:13.567110 [INF] A:6222 - rid:3244 - Router connection closed: Client Closed
> [3855] 2021/10/16 20:02:14.634213 [INF] A:6222 - rid:3245 - Route connection created
> [3855] 2021/10/16 20:02:14.635095 [INF] A:6222 - rid:3245 - Router connection closed: Client Closed
> [3855] 2021/10/16 20:02:15.681401 [INF] A:6222 - rid:3246 - Route connection created
> [3855] 2021/10/16 20:02:16.229139 [INF] A:38086 - rid:3247 - Route connection created
> [3855] 2021/10/16 20:02:16.230103 [INF] A:38086 - rid:3247 - Router connection closed: Duplicate Route

A's Config File;

> http_port: 8222
> port: 4222
> 
> debug: false
> trace: false
> logtime: true
> logfile_size_limit: 100MB
> log_file: "/srv/nats-streaming/log/nats-server.log"
> 
> cluster: {
>     port: 6222
>     routes: ["nats://B:6222"]
> }
> 
> streaming {
>         cluster_id: prod_cluster
>         store: "file"
>         dir: "/srv/nats-storage"
>         ft_group: "ftgroup1"
>         file_options {
>                 buffer_size: 32mb
>                 # sync_on_flush: false
>                 parallel_recovery: 16
>         }
>         store_limits {
>                 max_age: "48h"
>                 max_inactivity: "48h"
>         }
> }

B's Config File;

> http_port: 8222
> port: 4222
> 
> debug: false
> trace: false
> logtime: true
> logfile_size_limit: 100MB
> log_file: "/srv/nats-streaming/log/nats-server.log"
> 
> cluster: {
>     port: 6222
>     routes: ["nats://A:6222"]
> }
> 
> streaming {
>         cluster_id: prod_cluster
>         store: "file"
>         dir: "/srv/nats-storage"
>         ft_group: "ftgroup1"
>         file_options {
>                 buffer_size: 32mb
>                 # sync_on_flush: false
>                 parallel_recovery: 16
>         }
>         store_limits {
>                 max_age: "48h"
>                 max_inactivity: "48h"
>         }
> }

Error;
Publish operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
Status(StatusCode="Internal", Detail="error when publish to topic RetailCreateSalesAndInvoiceParameters in pubsub retailcreatesalesandinvoiceparameters: nats-streaming: error from publish: stan: connection closed")

Note: We are using [dapr](https://github.com/dapr/dapr) for pub/sub operations. This is implementation of our nats connection [implementation](https://github.com/dapr/components-contrib/blob/v1.0.1/pubsub/natsstreaming/natsstreaming.go)

**Comment by kozlovic** [comment]
Closing the issue since we did not get any response. Will re-open if issue still persist and you provide additional information.
