### ISSUE TITLE
java.io.IOException: stan: clientID already registered

### ISSUE THREAD

**Issue by FlightToFreedom** [nats-io/nats-streaming-server#1219]
Hello
I have a NATS client (with a static clientID) subscribed to NATS-streaming server, this client and NATS-streaming itself are running on 2 separate k8s pods on 2 different nodes.
The node where the client connected to NATS was running from needed maintenance and needed a reboot afterwards.
After rebooting, when i try to recreate the client pod, the` io.nats.streaming.StreamingConnection` object within the client throws an exception:
`java.io.IOException: stan: clientID already registered`
Apparently when the node was rebooted, in some way the client-ID of the client was not removed by NATS and its still registered.
I have naively tried to empty the 'clients.dat' file but that did not solve the issue.
How can i remove the clientID from NATS cache so that i can restart my client pod with the same clientID and register successfully?
Software version: 0.17.0
Thank you very much

**Comment by FlightToFreedom** [comment]
Solved, thx!

**Comment by kozlovic** [comment]
Well, it is more than that. The fact that you can't restart an app with the same client ID means that, not only the clientID is still registered in the server, but that the server can ping and get a response from the old client. Otherwise it would have replaced the old instance with the new one.

**Comment by kozlovic** [comment]
@FlightToFreedom I see that you just closed the issue as I was sending my response. Could you elaborate on what the issue actually was?

**Comment by FlightToFreedom** [comment]
> @FlightToFreedom I see that you just closed the issue as I was sending my response. Could you elaborate on what the issue actually was?
I have 2 namespaces with the identical set up (lets call them namespace A and B)
I was mistakenly connecting nats-streaming from namespace B to a nats server instance in namespace A, in A the exact same clientID was already up and running and connected, hence the error message.
Thx for assistance.
