### ISSUE TITLE
Leader of NATS Streaming cluster is not elected

### ISSUE THREAD

**Issue by dmitrywi** [nats-io/nats-streaming-server#1223]
I'm trying to start NATS Streaming Cluster of 3 servers with an explicit cluster configuration on the same host.
As written in this [post](https://github.com/nats-io/stan.go/issues/192#issuecomment-404549117) these lines must to appear in one of three logs
```
[INF] STREAM: server became leader, performing leader promotion actions
[INF] STREAM: finished leader promotion actions

```
but **none of the logs contains these lines**.

Environment:
- Linux
- same host for all of nodes
- no separate "NATS Server cluster" running. Only "NATS Streaming cluster"
- versions of "nats-streaming-server": 0.14.2, 0.23.1
- NATS Streaming Cluster is running by executing sh-script. If I'm launching each of three servers manually, then there is same effect.

**node_a.conf** configuration file:
```
# NATS specific configuration
port: 4242
cluster {
    name: probe
    listen: 0.0.0.0:5242
    routes: ["nats://127.0.0.1:5243", "nats://127.0.0.1:5244"]
}
# NATS Streaming specific configuration
streaming {
    id: test-cluster
    store: file
    dir: nats_dir
    cluster: {
        node_id: "a"
        peers: ["b", "c"]
    }
}
```

**node_b.conf** configuration file:
```
# NATS specific configuration
port: 4243
cluster {
    name: probe
    listen: 0.0.0.0:5243
    routes: ["nats://127.0.0.1:5242", "nats://127.0.0.1:5244"]
}

# NATS Streaming specific configuration
streaming {
    id: test-cluster
    store: file
    dir: nats_dir
    cluster: {
        node_id: "b"
        peers: ["a", "c"]
    }
}
```
**node_c.conf** configuration file:
```
# NATS specific configuration
port: 4244
cluster {
    name: probe
    listen: 0.0.0.0:5244
    routes: ["nats://127.0.0.1:5242", "nats://127.0.0.1:5243"]
}

# NATS Streaming specific configuration
streaming {
    id: test-cluster
    store: file
    dir: nats_dir
    cluster: {
        node_id: "c"
        peers: ["a", "b"]
    }
}

```
launch script:
```
nats-streaming-server -sc nats_a.conf -m 6242 -l ./nats_dir/nats_a_log.txt &
nats-streaming-server -sc nats_b.conf -m 6243 -l ./nats_dir/nats_b_log.txt &
nats-streaming-server -sc nats_c.conf -m 6244 -l ./nats_dir/nats_c_log.txt &
```

**Comment by kozlovic** [comment]
Directory must be unique per node. Since you are running all nodes on the same machine `nats_dir` is going to be the same for all nodes, which is not right. So call then `nats_dir_a`, `nats_dir_b`, `nats_dir_c` and it should be better.
