### ISSUE TITLE
Rare Channelz startup race condition "fatal error: concurrent map read and map write"

### ISSUE THREAD

**Issue by wilstoff** [nats-io/nats-streaming-server#1235]
We have a process that is monitoring all channels and their data, we regularly test bringing down and up the nats streaming server without bringing down this process.  On some rare occasions (1/5 maybe?) nats streaming server seems to crash on startup while reloading channels.  The first goroutine is listed below, but there are tons in the stack trace. I can list more if necessary.

Steps to reproduce:

Have 10k+ channels
Create channel [funChannel]
Regularly query http://[nats_host]:[nats_streaming_port]/streaming/channelsz?channel=[funChannel]
Regularly query http://[nats_host]:[nats_streaming_port]/streaming/channelsz
Bring down nats streaming
Bring up nats streaming
Sometimes can crash while loading channels

Setup:
3 node cluster
nats server version: 2.5.0
stan server version: 0.22.1

> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: fatal error: concurrent map read and map write
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: goroutine 522 [running]:
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: runtime.throw(0x1038d6f, 0x21)
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/.gimme/versions/go1.16.6.linux.amd64/src/runtime/panic.go:1117 +0x72 fp=0xc000f8f7b8 sp=0xc000f8f788 pc=0x438292
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: runtime.mapaccess1_faststr(0xec8040, 0xc00031f920, 0xc00112e081, 0x31, 0xc003275200)Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/.gimme/versions/go1.16.6.linux.amd64/src/runtime/map_faststr.go:21 +0x465 fp=0xc000f8f828 sp=0xc000f8f7b8 pc=0x413dc5
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: github.com/nats-io/nats-streaming-server/server.(*channelStore).get(0xc000322b40, 0xc00112e081, 0x31, 0xc0064b6a28)
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/server.go:288 +0x65 fp=0xc000f8f868 sp=0xc000f8f828 pc=0xd8faa5
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: github.com/nats-io/nats-streaming-server/server.(*StanServer).handleOneChannel(0xc00011fc00, 0x118b4a0, 0xc00639aa80, 0xc000d72c00, 0xc00112e081, 0x31, 0x0)
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/monitor.go:542 +0x65 fp=0xc000f8f900 sp=0xc000f8f868 pc=0xd878e5
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: github.com/nats-io/nats-streaming-server/server.(*StanServer).HandleChannelsz(0xc00011fc00, 0x118b4a0, 0xc00639aa80, 0xc000d72c00)
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/monitor.go:496 +0x9ed fp=0xc000f8fab8 sp=0xc000f8f900 pc=0xd877ad
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: github.com/nats-io/nats-streaming-server/server.(*StanServer).HandleChannelsz-fm(0x118b4a0, 0xc00639aa80, 0xc000d72c00)
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/gopath/src/github.com/nats-io/nats-streaming-server/server/monitor.go:492 +0x51 fp=0xc000f8fae8 sp=0xc000f8fab8 pc=0xdb94b1
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: net/http.HandlerFunc.ServeHTTP(0xc000312bf0, 0x118b4a0, 0xc00639aa80, 0xc000d72c00)
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/.gimme/versions/go1.16.6.linux.amd64/src/net/http/server.go:2049 +0x44
> fp=0xc000f8fb10 sp=0xc000f8fae8 pc=0x6dc0a4
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: net/http.(*ServeMux).ServeHTTP(0xc000322c00, 0x118b4a0, 0xc00639aa80, 0xc000d72c00)
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/.gimme/versions/go1.16.6.linux.amd64/src/net/http/server.go:2428 +0x1ad fp=0xc000f8fb70 sp=0xc000f8fb10 pc=0x6ddf2d
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: net/http.serverHandler.ServeHTTP(0xc00010e380, 0x118b4a0, 0xc00639aa80, 0xc000d72c00)
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/.gimme/versions/go1.16.6.linux.amd64/src/net/http/server.go:2867 +0xa3
> fp=0xc000f8fba0 sp=0xc000f8fb70 pc=0x6df663
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: net/http.(*conn).serve(0xc0001500a0, 0x118f2a8, 0xc0005c7040)
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/.gimme/versions/go1.16.6.linux.amd64/src/net/http/server.go:1932 +0x8cd fp=0xc000f8ffc8 sp=0xc000f8fba0 pc=0x6dab8d
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: runtime.goexit()
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/.gimme/versions/go1.16.6.linux.amd64/src/runtime/asm_amd64.s:1371 +0x1
> fp=0xc000f8ffd0 sp=0xc000f8ffc8 pc=0x472181
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: created by net/http.(*Server).Serve
> Jan 20 12:43:55 chivmdevnats003 nats-streaming-server: /home/travis/.gimme/versions/go1.16.6.linux.amd64/src/net/http/server.go:2993 +0x39bJ
> 
> >

**Comment by wilstoff** [comment]
Thank you for fixing this so quickly.

**Comment by kozlovic** [comment]
@wilstoff No problem, and thanks for the report. I am holding off a bit before doing a release with this fix, in case we have a NATS Server release soon and also to see if there are other reported issues :-)
