### ISSUE TITLE
Why nats server reads members info from meta.json?

### ISSUE THREAD

**Issue by DrManojD** [nats-io/nats-streaming-server#1246]
Why nats server reads members info from meta.json under log/XXXX-XXXXX-XXXXX/snapshots/ instead of the configuration file stan.conf?

If I remove meta.json file and restart the nats server from all the nodes, the nats cluster does not come up even the membership info are available in the configuration file. This exercise was needed as one unwanted node id exists as cluster member in meta.json, so we wanted nats to read the membership details from configuration file afresh.

One more question, does it also use raft.log under log/XXXX-XXXXX-XXXXX same way if meta.json is missing?

**Comment by kozlovic** [comment]
You can't simply remove this file. If you want to reset *completely* the state, then you would have to remove all `datastore` and `cluster_log_path` directories.

There are ways to dynamically add/remove peers in a cluster. As you know, I have explained this is an earlier issue you reported: https://github.com/nats-io/nats-streaming-server/issues/1240
