### ISSUE TITLE
question: upgrading nats-streaming without upgrading nats-server

### ISSUE THREAD

**Issue by fowlerp-qlik** [nats-io/nats-streaming-server#1250]
Hi we recently upgraded nats-streaming to v0.24.3 but left nats-server at v2.1.9. The nats-streaming 0.24.3 release notes mention a dependency on nats-server version v2.7.4. 

So do we have an incompatibility that may result in issues?

**Comment by kozlovic** [comment]
@fowlerp-qlik No, it's just since the NATS Server code is embedded, we keep it up-to-date. But if you connect to a remote NATS Server, you can use version of your choice.
