### ISSUE TITLE
NATS messages sent by the producer not getting processed by the consumer.

### ISSUE THREAD

**Issue by pravir** [nats-io/nats-streaming-server#1254]
We have created a few alarms and integrated webhooks. Now when alarms got triggered the webhook alerts are firing and it is showing in the webhooks client but for a specific  NATS subject (subj=Mytestrequest) the webhook alerts are not showing. The communication between alarms and webhook is using NATS.

So basically alarms are working fine and generated the webhook alerts for all the messages of NATS subject where the subject is not equal to Mytestrequest. The issue is with the Mytestrequest subject type.

Can anyone help me to understand the issue and share the solution for this?

**Comment by kozlovic** [comment]
Closing now since I did not hear back from you.
