### ISSUE TITLE
error on parsing routes in ipv6 

### ISSUE THREAD

**Issue by yicding** [nats-io/nats-streaming-server#1280]
I am hitting this error:

Parse error on line 6: 'Expected a map value terminator "," or a map terminator "}", but got ':' instead.'

The config.conf has the following configuration:

      1 port: 4222
      2 http_port: 8222
      3 log_file: "/log/messaging-server.log"
      4 cluster {
      5     listen: 0.0.0.0:6222
      6     routes: [ nats://[64:aaaa:bbbb:1000::1]:6222 ]
      7 }
      
The NATS streaming version is 0.20.0.

Please let me know which version has this issue fixed.

Thanks.

**Comment by kozlovic** [comment]
It should work if you use `"` around the whole URL, such as:
```
routes: [ "nats://[64:aaaa:bbbb:1000::1]:6222" ]
```
If that is not the case, let us know and we can re-open the issue.
