### ISSUE TITLE
A new build (0.25.6)? 

### ISSUE THREAD

**Issue by fowlerp-qlik** [nats-io/nats-streaming-server#1294]
Hi. Release support ended June 30th. We have migrated to Solace messaging but upper management would like to keep
Nats streaming as an insurance policy until the end of the year so we need to rebuild nats-streaming with Go 1.20.9 to address some security vulnerabilities.

I started going down that path when I saw some commits in October. Do you plan on doing another release?

**Comment by kozlovic** [comment]
I could do a release after some updates of dependencies. I think the v0.25.6 would stay with NATS Server v2.9.x version though (that is, not upgrade it to v2.10.x).

**Comment by fowlerp-qlik** [comment]
That sounds great!

**Comment by kozlovic** [comment]
@fowlerp-qlik We just released v0.25.6 (https://github.com/nats-io/nats-streaming-server/releases/tag/v0.25.6). By the way, it contains an update of the Raft library that should solve the issue you reported some time ago regarding "Time.UnmarshalBinary: unsupported version". We will be submitting the PR for the official image later today.

**Comment by fowlerp-qlik** [comment]
Thank you very much!
