### ISSUE TITLE
Add support for Fault Tolerance and High Availability

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-streaming-server#13]
Need support for Fault Tolerance and High Availability

- [ ] Shared Storage Fault Tolerance (#263)

**Comment by stephenjannin** [comment]
Do you have any plan/advice on how to achieve high availability for nats streaming servers ?
For example I have a 3 nodes cluster and if I loose a node, clients gets reconnected to another one  and don't loose any messages ?

**Comment by dahankzter** [comment]
What does the "ready" label mean?

**Comment by nsamala** [comment]
Bumping this issue too. @mcqueary is this functionality available in NATS streaming currently or is this planned development?

**Comment by joeblew99** [comment]
https://github.com/minio/dsync 
- object level storage clustered across servers. Using minio, which is pretty well used now. Its limited in terms of the one to many options and no rebalacning yet, but is one option i feel.
- If a NATS server dies, the data does not die with it. New one boots up, takes over the namespace and off it goes. Still needs heartbeating / discovery with etcd or whatever i guess.

**Comment by sfrooster** [comment]
@joeblew99 can you expand on how this works, what it would provide? Possibly as a bridge until true clustering is available?

**Comment by joeblew99** [comment]
@sfrooster its just an idea.
the goal is to have Kafka like functionality. In other works  that you can store events in the system for ever if need be. As you well know this is how people se kafka in a CQRS architecture.

dsync provides some base primitives as does minio. this needs much much more research.
other will disagree what the goal of clustering support is perhaps too.

Happy to debate this...

**Comment by dahankzter** [comment]
I have always expected the clustering support to allow for replacing Kafka.
As soon as it is there our Kafka instances are history.

**Comment by sfrooster** [comment]
@joeblew99 @dahankzter 
I'm aware of the need for clustering, I just want it sooner than the current schedule. I want to avoid kafka in the first place.  Would either or both of you mind elaborating as to why you're moving away from kafka? I'm of the same mindset, but would really like to hear other's experiences.

**Comment by dahankzter** [comment]
For me it is the hopefully easier and faster operations aspect. The
performance of message delivery as well of course but primarily operational
simplicity.

**Comment by sfrooster** [comment]
Can you elaborate on some of the operational challenges you've had?

**Comment by dahankzter** [comment]
Actually Kafka has been much better than many other Zookeeper dependent
tools. Usually it is a combination of jvm gc and adding/removing nodes and
partitions. I have perhaps gotten my hopes up too high since Nats is so
very easy to use and maintain in operations.

**Comment by joeblew99** [comment]
why i am avoiding Kafka:
1. Because its JVM and so makes dev and ci and ops just that extra bit harder. We try to use golang for everything (even for mobile and web GUI). I knwo its naughty to put all eggs in one basket...

2. Because i use NATS on mobiles, servers, desktops now.  Its very sweet how with golang you can run it on all mobiles and leverage lots of golang code.  The other apps on the mobile phone can then bind to the local NATS system, and everyone gets automatic off lien capability with catchup. that is one of the reasons..

**Comment by mcqueary** [comment]
@dahankzter Sorry for the delayed response. The "ready" label is an indicator that the item is "ready to work on". It's a waffle.io thing.

**Comment by mcqueary** [comment]
@nsamala It's in early development right now.

**Comment by dahankzter** [comment]
I don't mind trying out some alpha status stuff as soon as possible :)

**Comment by JensRantil** [comment]
@mcqueary Care to share your thoughts on how you plan to solve clustering? Might be interesting and maybe also for you to get some feedback.

**Comment by JensRantil** [comment]
@mcqueary I know all developers dislike the question, but do you have any idea when cluster support might be added? January? March? June?

**Comment by JensRantil** [comment]
Also, this issue is in "early development", but i milestone "Needs discussion". Needs milestone update?

**Comment by JensRantil** [comment]
To partially answer my own questions, [this page states](https://blog.gopheracademy.com/advent-2016/nats/):

> ... and the team is also in the process of delivering clustering for NATS Streaming - you can look forward to that in the first half of 2017.

**Comment by mkharibalaji** [comment]
@mcqueary - I am on the same page as @JensRantil - When can we expect this feature ? - Sooner the better !

**Comment by bjflanne** [comment]
@mkharibalaji @JensRantil -- Saw this and wanted to give you some context: our team is currently in the design phase of Clustering. The timeframe I've heard communicated most recently would be to deliver some beta functionality in the 1st half of this year. Hopefully this helps?

**Comment by mcqueary** [comment]
@mkharibalaji @JensRantil Fair points all. I have updated the milestone to reflect reality.

As a general statement, clustering in the context of 1:N and N:M data streaming using publish subscribe is not a trivial problem to solve, as we are being reminded of this as we go through the requirements to establish a candidate design. We are actively working through this and have set an internal milestone for 1H2017. We'll announce more as the design elements become more "officialized" :) Thanks for your continued patience and please know this is our top priority for NATS Streaming this year.

**Comment by glycerine** [comment]
Design wise, I would invite you to consider a TAPIR based design for replication (clustering).
http://syslab.cs.washington.edu/research/tapir/

TAPIR is a recent design (2015), but one that is extremely efficient (while being quorum safe). It does have the advantage also of having working C++ code implementation code available for reference, as well as TLA+ model-checked proofs of protocol correctness. https://github.com/UWSysLab/tapir

**Comment by c4milo** [comment]
paper link throws 404

**Comment by sfrooster** [comment]
Are you suggesting a TAPIR based distributed message store, or something
else?

**Comment by glycerine** [comment]
> Are you suggesting a TAPIR based distributed message store, or something else?

The ticket called for sharding, replication, and a consistency protocol. Larry mentioned raft, but TAPIR would replace raft and provide for replication and consistency. After that sharding is not difficult. TAPIR claims better throughput AND better latency. It's a distributed txn protocol, which may be overkill, but it will still be faster than running raft or paxos to do consistent replication.

**Comment by sfrooster** [comment]
I'd suggest you engage them more vigorously than this post.

Many people are interested in an implementation of streaming which is TLA+
provable and of it happens to be better than RAFT, so much the better.

**Comment by glycerine** [comment]
Hi Michael,

> I'd suggest you engage them more vigorously than this post.

I'm really not sure what you mean. I'm not offering to work on it myself, just suggesting a nice efficient algorithm if things are still at the design phase.

**Comment by sfrooster** [comment]
It may be a very useful approach to their problem but your pitch doesn't
offer anything over RAFT, but maybe you don't care. Understand, I'm not
saying TAPIR doesn't offer anything over RAFT, but you're not currently
offering them anything when what they want to do is get to a solution.

**Comment by dahankzter** [comment]
Using RAFT or TAPIR is fortunately an entirely internal implementation
detail which means it can be switched at any time later.

tors 9 feb. 2017 kl 07:31 skrev Michael Haan <notifications@github.com>:

**Comment by peterdeka** [comment]
Apart from clustering, a DB store (MongoDB for example) could provide a simple way to grant a simpler failure recovery in production environments where file binding is less desirable. Thinking about a containerized execution for example, if the nats-streaming (one and only in the VMs cluster) dies, reinstantiation on any VM would be very easy.

**Comment by petemiron** [comment]
We're decomposing this issue into multiple requirements starting with #263, partitioning (sharding) and NATS Streaming managed replication will follow as we flesh out the requirements. Please review and give us your feedback on that issue. This should take into account many of the suggestions thus far with leader election and should not prevent anyone from adding one of the DB-based file stores suggested.

**Comment by ryanhmasten** [comment]
From what I can see on https://github.com/nats-io/nats-streaming-server it says the NATS Streaming server supports connecting to a cluster of NATS servers but when I try it doesn't work. It appears to connect to both the cluster of servers but then streaming clients cannot connect to the NATS Streaming server. Do you have any examples or steps to make it work? Essentially what I'd like is two streaming servers (active-standby) and have it connected to a cluster of NATS servers, then connect a Go client to the streaming server. 

From my reading on the link above, this should be supported already?

**Comment by sirajmansour** [comment]
Any recent development/updates on this ?

**Comment by tylertreat** [comment]
We're currently working on clustering. There is a branch, clustering_mvp, that you can follow.

**Comment by jmwilkinson** [comment]
It appears that clustering support was added. Is there a commit that this issue could be tied to and closed?

**Comment by kozlovic** [comment]
@jmwilkinson Yes. Here is the tag: https://github.com/nats-io/nats-streaming-server/releases/tag/v0.8.0-beta and specific commit: https://github.com/nats-io/nats-streaming-server/commit/6fdcdfbb2589e68692a68fd5b64b1b7e7c54bf05
