### ISSUE TITLE
NAT Forwarding / Protocol 

### ISSUE THREAD

**Issue by gregoryflood9** [nats-io/nats-streaming-server#1300]
1. Initial packets follow the classic forwarding path, once the flow enters the established state according to the conntrack semantics (ie. we have seen traffic in both directions), then you can decide to offload the flow to the flowtable from the forward chain via the 'flow offload' action available in nftables. Packets that find an entry in the flowtable (ie. flowtable hit) are sent to the output netdevice via neigh_xmit(), hence, they bypass the classic forwarding path (the visible effect is that you do not see these packets from any of the netfilter hooks coming after the ingress). In case of flowtable miss, the packet follows the classic forward path. The flowtable uses a resizable hashtable, lookups are based on the following 7-tuple selectors: source, destination, layer 3 and layer 4 protocols, source and destination ports and the input interface (useful in case there are several conntrack zones in place). Flowtables are populated via the 'flow offload' nftables action, so the user can selectively specify what flows are placed into the flow table. Hence, packets follow the classic forwarding path unless the user explicitly instruct packets to use this new alternative forwarding path via nftables policy. This is represented in Fig.1, which describes the classic forwarding path including the Netfilter hooks and the flowtable fastpath bypass.
•           The flowtable entry also stores the NAT configuration, so all packets are mangled according to the NAT policy that matches the initial packets that went through the classic forwarding path. The TTL is decremented before calling neigh_xmit(). Fragmented traffic is passed up to follow the classic forwarding path given that the transport selectors are missing, therefore flowtable lookup is not possible. Example configuration --------------------- Enabling the flowtable bypass is relatively easy, you only need to create a flowtable and add one rule to your forward chain.
•              This example adds the flowtable 'f' to the ingress hook of the eth0 and eth1 netdevices. You can create as many flowtables as you want in case you need to perform resource partitioning. The flowtable priority defines the order in which hooks are run in the pipeline, this is convenient in case you already have a nftables ingress chain (make sure the flowtable priority is smaller than the nftables ingress chain hence the flowtable runs before in the pipeline). The 'flow offload' action from the forward chain 'y' adds an entry to the flowtable for the TCP syn-ack packet coming in the reply direction. Once the flow is offloaded, you will observe that the counter rule in the example above does not get updated for the packets that are being forwarded through the forwarding bypass.

**Comment by kozlovic** [comment]
@gregoryflood9 I am not sure why you created this issue in NATS Streaming Server repository. I don't see anything related to the product. On top of that, this product is no longer supported: https://github.com/nats-io/nats-streaming-server?tab=readme-ov-file#warning--deprecation-notice-warning. I am closing this issue now.
