### ISSUE TITLE
Dockerfile + official release on Docker Hub?

### ISSUE THREAD

**Issue by VojtechVitek** [nats-io/nats-streaming-server#137]
Hi guys, thank you for this awesome project.

Do you plan to release NATS Streaming Server to Docker Hub anytime soon?

**Comment by kozlovic** [comment]
Thank you for your interest! Yes, we do plan to release NATS Streaming to Docker Hub in the coming weeks. Stay tuned!

**Comment by kozlovic** [comment]
Just an update for you guys: I have submitted a PR to Docker's official images repo, waiting for them to review and hopefully merge: https://github.com/docker-library/official-images/pull/2036

**Comment by VojtechVitek** [comment]
@kozlovic thank you!

**Comment by zshamrock** [comment]
@kozlovic any news from Docker on this one? It still can't be find in the Docker Hub.

**Comment by kozlovic** [comment]
@zshamrock Unfortunately no, I have just put a comment in the PR to see if I get some feedback. Not sure if that helps, but you can go to https://github.com/docker-library/official-images/pull/2036 and put a thumbs up ;-)

**Comment by zshamrock** [comment]
Done (thumb up). But you still can upload NATS.io official image (not necessary under Docker official images) into the Docker Hub. It will be better than nothing in the meanwhile?

**Comment by kozlovic** [comment]
Happy to announce that it is now ready [here](https://hub.docker.com/_/nats-streaming/). Thanks all for your patience!
