### ISSUE TITLE
Support extremely large numbers of topics

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-streaming-server#168]
The NATS Streaming server should support extremely large numbers (millions) of topics.

Areas to investigate to achieve this include:
- Reduce memory utilized by active subscriptions.
- Increase throughput to the embedded / connected NATS server (multiple connections).
- Add a backing store type that can efficiently handle large numbers (millions) of channels. 

It should be understood that performance will be correlated to the choice of backing store.

**Comment by TomFreeman** [comment]
Is there a benchmark for how many topics NATS Streaming server can support right now?

**Comment by golang101** [comment]
@mcqueary 
Is there a limit for the number of topics?

**Comment by kozlovic** [comment]
Regarding the use of `--file_fds_limit`, just note that this is available in master but not in the latest release (v0.3.8).

**Comment by Go101** [comment]
@Go101
for chat room and game instance servers, the topic number is uncertain.
But I think for a single physics server, two thousands concurrent topics are enough.
But the two thousands concurrent topics may be vary from time to time,
in other words, some old topics would become inactive.
Does nats-streaming support closing/deleting topics dynamically at run time, without restart server?

**Comment by ColinSullivan1** [comment]
@Go101 , Absolutely - happy to help.

Two thousand topics shouldn't pose any problems for you.

Assuming you are using a file store, the NATS streaming server won't automatically clear up old topics (channels), although you can manage the disk space it uses.  NATS streaming has the concept of slices, where persisted messages are rolled off into other files based on limits you define.  You can define limits for slices, and setup scripts to the server will invoke to delete what you no longer need, detailed [here](https://github.com/nats-io/nats-streaming-server#configuring).  (Check out the various `--file_slice_max_xxxx` and `--file_slice_archive_script` parameters).

Store limits will allow you to reduce the disk space you'd need, but you'll still periodically need to stop the server and delete the old channel directories for your use case.

**Comment by Go101** [comment]
Thanks for the answer.

**Comment by TomFreeman** [comment]
@ColinSullivan1 we're still making architectural decisions etc... so the number of topics is a bit flexible. Ultimately it'll be millions in our ideal (simplest architecture) setup.

But I ask for two reasons, one is to know where the current status-quo is, but the other is to be able to measure the progress of any work towards supporting millions.

**Comment by ColinSullivan1** [comment]
@TomFreeman , In work toward supporting millions of subjects, I suggest taking a look at [Partitioning](https://github.com/nats-io/nats-streaming-server#partitioning), where you can partition your subject namespace across a number of NATS streaming servers to horizontally scale.

**Comment by riaan53** [comment]
Hi @ColinSullivan1 ,

Any progress on this? We are busy prototyping some new architecture ideas and nats-streaming looks like a good fit. Our number of concurrent users is not that high (and low TPS per user) but we have a lot, few million users per geo region. We plan on using a sharing pattern per geo region and then extra partitioning inside each region but it will still be a few mil per cluster.

**Comment by voltcode** [comment]
Hi all, I came here through https://github.com/nats-io/nats-general roadmap, saying that streaming is high on the priority list (with JETSTREAM annotation).
I also came across https://bravenewgeek.com/building-a-distributed-log-from-scratch-part-5-sketching-a-new-system/ where jetstream is mentioned as previous name to liftbridge.

My questions are - is there a more detailed plan / schedule somewhere on NATS Streaming progress, possibly addressing some of the issues that the artictle mentions?
Or maybe it is about making liftbridge v2 of NATS Streaming?

I'm looking into using NATS Streaming as a durable message queue that can be embedded as part of a larger solution, installable on-prem, without Kafka et al operational overhead. So far I have been evaluating Akka with Cluster and Persistence modules for this purpose. 

It would be great to understand the Streaming plans for the future, and how big it is on the whole NATS roadmap in terms of resource allocation, etc. I think a product like this could hit a sweet spot for many - a message queue that can be applied to small and large products, without large Ops overhead.

**Comment by voltcode** [comment]
@ColinSullivan1 regarding my earlier post - would you mind at least pointing me in the right direction, so I can understand better whether I should bet on NATS (Streaming) for my projects?

**Comment by maxless** [comment]
So, a lot of time has passed and it looks like no updates or any information. How are things currently? Can we have a million or 10 million streams up and what'll be the memory overhead?
@ColinSullivan1

**Comment by kozlovic** [comment]
@maxless The project has been EOL since June 2023. We had this warning in place a long time ago: https://github.com/nats-io/nats-streaming-server?tab=readme-ov-file#warning--deprecation-notice-warning

I would recommend that you look at JetStream (part of NATS Server: https://github.com/nats-io/nats-server). You won't either be able to have millions of streams (equivalent of channels), but instead you can have streams with wildcard subjects and maybe go around that limitation. I would also recommend that you join the Slack channel to get help from the community (see Contact info here: https://github.com/nats-io/nats-server?tab=readme-ov-file#contact)

I am closing this issue now since there won't be any resolution at this time.

**Comment by maxless** [comment]
Oh, sorry. I mixed up the repos while Googling for answer. I was talking about JetStream actually. Thank you for clarification.
