### ISSUE TITLE
Occupies 50% of memory

### ISSUE THREAD

**Issue by zshamrock** [nats-io/nats-streaming-server#171]
Not sure if it is related to the server or the client library (Java) we use.
But starting the nats streaming (v0.2.2) the free memory goes from 3.7GB to 167MB immediately.

Changing the current data dir with lots of files there (121 subjects/channels dirs), to the new data dir, then NATS streaming no longer occupies that much memory, and system continues to have 3.7GB of a free memory.

It could be due to:
```
-rw-rw-r-- 1 ubuntu ubuntu 14K Oct 11 13:44 clients.dat
-rw-rw-r-- 1 ubuntu ubuntu 183 Sep  7 19:35 server.dat
```
As 14K size of the clients.dat looks really suspicious. And this could be the reason why then immediately all the memory was being consumed.

The question is then why this file is growing, as there are no active client connections at all to the NATS streaming, and we close the connection on the application shutdown. It also could explain why recently we have to increase `-mc` from 100 to 1000, as we start getting exceptions while connecting to it that maximum number of connections is achieved. Which is again, why?

**Comment by ColinSullivan1** [comment]
@zshamrock - Thank you for using NATS!

We'll look into it.  In the meantime, could you run a small test with an instance of your application where you run the NATS streaming server with the `-SDV` flag, and send us the output?

**Comment by kozlovic** [comment]
@zshamrock The file store implementation in `v0.2.2` is keeping messages in memory, so there was effectively no disk read after the initial restart.
Could you try with this [PR](https://github.com/nats-io/nats-streaming-server/pull/166) and use `-file_cache=false` on the command line to see if the memory usage drops? In this PR, the file store implementation can now disable caching (which will result in disk reads when looking up messages for delivery). 
Let us know if this solves the memory issue.

Note regarding `-mc`: this is the max number of channels (aka subjects), not connections. Make sure that you are not using request/replies with streaming (inboxes, unique subjects, etc..) that would eat-up the max number of channels.

**Comment by zshamrock** [comment]
Hi, @ColinSullivan1 here is the log from running NATS streaming with -SDV (and again if running against that directory memory goes from almost 4GB to 150MB in less then minute).

[events.sdv.log.zip](https://github.com/nats-io/nats-streaming-server/files/525152/events.sdv.log.zip)

**Comment by kozlovic** [comment]
@zshamrock Please check my comment above. Try with the file store implementation found in the PR (I hope to issue a release soon with that PR and other things merged). 

Regarding the client file, assuming that you make sure that your connections are closed, then don't worry about the size of the file. It is compacted based on some thresholds, so 14K does not mean that the server recovers that many connections. 

Also, it looks like your subjects (I can see this one: `session.0e06de75-9085-11e6-b39c-feaea2cbe019`) may be generated to be unique and so be minded that in Streaming, a channel does not go away. So if you have ephemeral subjects, it won't play nice with Streaming.

**Comment by kozlovic** [comment]
@zshamrock Note about using the code in PR. This PR introduces index files for the message stores. If you run the server built from PR, it will find that there is no index file so recover the `msgs.dat` files and generate the index files on the flight. However, if you do run with the new version and go back to use the `v0.2.2` with current data files, the index would not be updated. So you would need to manually delete the index files if you switch again to v0.3.0.

**Comment by zshamrock** [comment]
Hi, @kozlovic. Thank you.

Yes, will then try the version from PR to see if it addresses this issue, and let you know then.

> Regarding the client file, assuming that you make sure that your connections are closed, then don't worry about the size of the file. It is compacted based on some thresholds, so 14K does not mean that the server recovers that many connections.

Ok, this was my next question :). Then good to know.

One more thing, could you, please, explain more on this:
> Also, it looks like your subjects (I can see this one: session.0e06de75-9085-11e6-b39c-feaea2cbe019) may be generated to be unique and so be minded that in Streaming, a channel does not go away. So if you have ephemeral subjects, it won't play nice with Streaming

Specifically by "channel does not go away"? Our use case, is that we don't have well predefined channels upfront (like, I don't know "events", for example), but instead create a new channel every time a new session starts (session - in our application is the limited in time activity for which events are generated). We never actually query it (currently), but simply use NATS streaming, as a backup store for those "raw" data per session. So, we could replay the session, and debug it if necessary, as having all the events, we can easily rebuild the sessions state over the time.

Also it means that number of subjects will grow over time, i.e. we could have 10*N of the sessions in average per day, where N will continue to grow over time, as more users join.

**Comment by zshamrock** [comment]
Also, if it matters, the overall size of the data already stored in the data dir, is about 1.3GB. So, if reading everything into memory on startup, it could explain this. And as we don't query it in real-time (or often), we indeed better to disable `file_cache`

**Comment by kozlovic** [comment]
Yes about disabling file_cache, and using the code from PR should reduce the memory footprint.

That being said, you need to understand that anytime you send to a new subject (channel), the server will create a sub-directory and store messages and subscriptions info in that directory. The number of channels is limited by the `-mc` option. Those channels don't go away, meaning that there is no current way to ask the server to delete a channel (short of stopping the server and deleting the sub-directory in question). So in your use case, overtime the number of sub-directories will increase and overall resource usage of the server will increase. The current file store implementation may not be suited for thousands of channels (subjects) due to the use of file descriptors per channel. See [this issue](https://github.com/nats-io/nats-streaming-server/issues/168) for more info.

**Comment by zshamrock** [comment]
Thank you. Yes the issue you've mentioned looks interesting. Specifically this "It should be understood that performance will be correlated to the choice of backing store." Also from your notes 
> The current file store implementation may not be suited for thousands of channels (subjects) due to the use of file descriptors per channel. See this issue for more info.

I understand the limitation. We have couple of months before going 100% public, so maybe at that time the new backing store will be ready. Or we build the workflow to workaround this. For now it fits very nicely what are doing :).

Thank you, for that nice tool.

**Comment by kozlovic** [comment]
@zshamrock Ok thanks. Let us know if using the code from PR with `-file_cache=false` works for you, and I will close this issue.

**Comment by kozlovic** [comment]
@zshamrock I am closing this issue now. Will re-open if needed.
Thanks!
