### ISSUE TITLE
How to delete channels

### ISSUE THREAD

**Issue by 2cats** [nats-io/nats-streaming-server#177]
In my application, a unique topic is created for each client's request. However, as time goes by,I encounter the "**too much channel**" error.So ,How can I **delete channel when it is useless** ?

**Comment by kozlovic** [comment]
By request, do you mean that you are doing request/reply with Streaming? If so, not that the API has been removed from the streaming clients (they were there originally to make the streaming API look alike the NATS API). Request/reply is not appropriate with Streaming. Regular NATS Request/Reply is giving enough guarantee that the receiver has received and processed the request, so there is no need for persistence. 
Streaming channels are not meant to be ephemeral, and as of now there is indeed no way to delete a channel. We may add this in the future though, but probably not for the reasons you need it.

**Comment by 2cats** [comment]
Thanks for your reply , Seems  I have to use streaming and regular nats together now

**Comment by kozlovic** [comment]
Note that the with the client API, you have a convenient method (`conn.NatsConn()`) that returns the underlying NATS connection that you could use for NATS request/reply if you desire. Or you can use a dedicated one, up to you.
