### ISSUE TITLE
Use streaming and normal nats together [question]

### ISSUE THREAD

**Issue by riaan53** [nats-io/nats-streaming-server#178]
Hi, If i just start up a nats streaming server and connect to it via the normal nats client and a streaming client to get the fuctionality of both. It works but I just want to know if it will be ok to use it like that? Will the normal nats client behave the same as if running against the standard server?

Thanks!

**Comment by kozlovic** [comment]
Thanks for using NATS!

By default, the NATS Streaming server embeds a NATS Server, but it is a standard NATS server, so this is why both NATS and Streaming client can connect and work as expected.
You could start the Streaming server and connect to a NATS server using the `-ns` command line parameter. See the NATS Streaming server as a NATS client (which it is).

**Comment by riaan53** [comment]
Awesome! 👍

**Comment by StarpTech** [comment]
@kozlovic would cluster mode work as expected when I connect as a nats client?

**Comment by StarpTech** [comment]
@kozlovic has been clarified https://github.com/nats-io/nats-streaming-server#clustering thanks.
