### ISSUE TITLE
Does this replicate data across the cluster for fail-over

### ISSUE THREAD

**Issue by joeblew99** [nats-io/nats-streaming-server#179]
This looks awesome

i am looking at my Infrastructure roadmap, and NATS-Streaming looks like its has the properties to replace Kafka. 

But, does this replicate data across the cluster for fail-over yet ?
I also noticed its a simple file based disk persistence. I guess this will be changed to a formal WAL of some sort ?

**Comment by kozlovic** [comment]
Thanks for your interest!

Clustering is in the roadmap but not implemented yet. The target is for Q1 2017, but nothing is set in stone.
As for storage, we have memory and indeed a simple file base implementation. We have tried to use a Store interface to make it is easier to add future implementations. We welcome community contributions ;-)

**Comment by joeblew99** [comment]
@kozlovic 
The store interface sounds good. I suggest one being boltDB for portability reasons, as i run lots of go code on mobile , desktops and servers, and bolt runs everywhere.
