### ISSUE TITLE
 AckAwait always multiply by 3 seconds?

### ISSUE THREAD

**Issue by DasAng** [nats-io/nats-streaming-server#186]
I have a weird behavior when trying to use AckAwait in a manual acknowledge mode.

Maybe I'm missing something here but I have experienced a scenario where I see the duration I set in  AckAwait() being multiplied by 3 seconds.

For example:

`stan.QueueSubscribe("foo","bar",stan.SetManualAckMode(),stan.AckWait(time.Second))`

Then after 3 seconds if I haven't acknowledged the message it gets redelivered.
If I set the timeout to for example 2 seconds instead:

`stan.QueueSubscribe("foo","bar",stan.SetManualAckMode(),stan.AckWait(time.Second*2))`

Then after 6 seconds I get the message redelivered and so on...

Have anyone experienced the same behavior?

**Comment by kozlovic** [comment]
Are you receiving one message at a time or are you seeing this after your application has receive tons of messages? The reason I ask is that if the subscriber has receive MaxInflight messages, it is considered stalled and no message is sent to it. This is blocking redelivery, but redelivery is forced after 3 failed redeliveries.

**Comment by DasAng** [comment]
I'm seeing this one message at a time. I've set MaxInFlight to for example 1.

**Comment by kozlovic** [comment]
Well that's the point. You set MaxInFlight to 1, so that means the server stalls the subscriber after the first message. So what you see is expected.

**Comment by kozlovic** [comment]
As a test, don't set MaxInFlight at all. Run your subscriber with manual ack and don't acknowledge. Send 1 message, look at the message redelivery. Do you still see 3 seconds?

**Comment by kozlovic** [comment]
I just verified and it works as I stated above.

**Comment by DasAng** [comment]
Yes If I don't set MaxInFlight it works as expected. Ok thanks for the explanation. Is this documented somewhere?

**Comment by kozlovic** [comment]
Here: https://github.com/nats-io/go-nats-streaming#subscriber-rate-limiting. It does not specifically describes redelivery, but redelivering messages to slow consumers will probably not help, hence the decision to force a redelivery only after an amount of failed redelivery attempts.
