### ISSUE TITLE
Unsubscribing from Subscription Inside Subscription Handler Errors

### ISSUE THREAD

**Issue by sfrooster** [nats-io/nats-streaming-server#188]
cc @aricart 

Using the node streaming client, we have the following typescript code:
`let subOpts = this.stanConn`
`.subscriptionOptions()`
`.setMaxInFlight(1)`
`.setManualAckMode(true)`
`.setStartWithLastReceived()`
`.setAckWait(ackWaitMS);`
` `
`let lastMsgSub = this.stanConn.subscribe("some-string-here", "", subOpts)`
`    .on("message", (lastMsg: NATSMessage) => {`
`        doReplay(lastMsg);`
`        // we were doing just lastMsgSub.unsubscribe() but go errors`
`        setTimeout(() => lastMsgSub.unsubscribe(), 10000);`
`    });`

The intent is to get just one message, the last received message.  When we had just the commented line (lastMsgSub.unsubscribe()), we routinely got:
`Error: Subject must be supplied`

I tracked it down to https://github.com/nats-io/node-nats-streaming/blob/master/lib/stan.js#L748
where this.subscription.ackInbox was undefined when the error occurs.

I can make the error occur much less frequently with the code above where we defer the unsubscribe for 10 seconds, but it still happens occasionally. I can also reduce the incidence by acking after unsubscribing (but not as much as deferring the unsubscribe). acking before unsubscribing is not preferred for this use case, and also fails nearly as much as just unsubscribing.

**Comment by aricart** [comment]
@sfrooster  What server are you using? There may be an issue with the server forwarding messages before the protocol response is received.

Could you please try with commit hash 624ac895c4065ccaf7cf21496e170945f7e14be6

**Comment by ColinSullivan1** [comment]
@sfrooster We're looking at potential bug introduced in master - I'll keep you posted.

**Comment by sfrooster** [comment]
Ok - so don't try with the commit hash above...

**Comment by ColinSullivan1** [comment]
@sfrooster - Sorry for the confusion - the commit hash @aricart mentioned is good, or give PR #191 a shot.   Which version of the NATS streaming server did you see your problem with?

**Comment by sfrooster** [comment]
Latest - 0.3.1 / 0.9.4

**Comment by sfrooster** [comment]
Given that, which should I be trying?

**Comment by ColinSullivan1** [comment]
If you really want to use master branch, feel free to use commit hash 624ac89.  Otherwise, use release v0.3.0.  Master branch will not be as stable as a release.  Thanks for reporting this!

**Comment by sfrooster** [comment]
https://github.com/nats-io/nats-streaming-server/pull/191 seems to have
fixed the issue we were experiencing in
https://github.com/nats-io/nats-streaming-server/issues/188

**Comment by aricart** [comment]
#191 Fixes the issue.
