### ISSUE TITLE
Server should track list of existing channels

### ISSUE THREAD

**Issue by sfrooster** [nats-io/nats-streaming-server#198]
I'd would be useful for the server keep a list of all channels (++info) to support reporting and admin operations against, for example, old, out dated or orphaned channels.

**Comment by kozlovic** [comment]
@sfrooster The server can get stats on all channels through the store interface. So I guess this is more of adding channels info into #116, which you already commented in that issue, right?

**Comment by sfrooster** [comment]
Yes - it's the first bullet point on my list :-)

**Comment by kozlovic** [comment]
So should we close tis (#198) issue then?

**Comment by sfrooster** [comment]
Closing in favor of #116
