### ISSUE TITLE
Durable Queue Subscribers not properly removed from store when leaving the group

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-streaming-server#215]
When a member leaves the group (but there are still members on that group), the member is removed from the group in memory but not from the store, which means that for file based stores, after a server restart, the member that left is incorrectly recovered and will consume messages that should be sent to members that would be added later.

Some steps to reproduce would be:
- create a durable queue subscriber (qs1) on subject "foo" with queue name "bar" and durable name "dur" with clientID: cid1
- create a durable queue subscriber (qs2) on subject "foo" with queue name "bar" and durable name "dur" with clientID: cid2
- close qs2 (either Subscription.Close() or close its connection)
- send msg1 to "foo" and notice qs1 receives it.
- close qs1 (either Subscription.Close() or close its connection)
- restart server (with `-SDV`)
- send msg2 to "foo" and notice message is sent to qs2 (clientID: cid2), although this member is not running.
- start a durable queue subscriber on subject "foo" with queue name "bar" and durable name "dur" with deliver all and notice that it does not receive message msg2.

**Comment by mackeyja92** [comment]
PR seems to have fixed it. thanks @kozlovic
