### ISSUE TITLE
How to set the embedded NATS server options in the config files 

### ISSUE THREAD

**Issue by szank** [nats-io/nats-streaming-server#225]
Hi, I have just started testing the nats-steraming. 
I have copied the example config file from the readme file, and statrted editing. 
I wanted to start two nats-steraming servers on my laptop, so decided to run one with non standart port 
running `nats-streaming-server -sc ./config.file -p 4223` and it works well. If i addd 
`port: 4332` to the ./config.file the servet still listens on port 4223

Any ideas ?

**Comment by szank** [comment]
Anyway, I could have written a separate nats config file with the port no, and pass it with the `-c` argument, but this is not very admin friendly.

**Comment by kozlovic** [comment]
As you know there is two sets of configuration parameters, one set for the NATS server if you embed it, and one set for the NATS Streaming server. 

I have testes and you can put the two sets in the same configuration file and provide the same configuration file to both `-sc` and `-c`. Please try and report back.

**Comment by kozlovic** [comment]
That being said, any command line parameter overrides the ones in the configuration file. So if `port` is specified in the config file and you use `-p xxx` on the command line, this one will take precedence.

**Comment by szank** [comment]
@kozlovic, 
thanks! Passing the same file for the `-sc` and `-c` parameters should do the trick for our use case. I didn't think about that.

**Comment by kozlovic** [comment]
@szank Me neither until you raised the question ;-)

I am closing the issue for now, feel free to re-open if you have a problem.

**Comment by Maheshvaws** [comment]
![image](https://user-images.githubusercontent.com/107991049/196133203-c99ddc2f-6021-4969-a339-af1671d0870d.png)
why am getting this error  and does it solve
