### ISSUE TITLE
pull vs push

### ISSUE THREAD

**Issue by glycerine** [nats-io/nats-streaming-server#229]
Is nats-streaming-server (n.s.s.) a push or a pull based design?  On its face it appears to be push (update: from the point of view of the consumer), but I haven't gotten to play with it (yet).

For context, the designers of Kafka couldn't make push work for their uses. Discussion below. Does n.s.s. finesse such issues in some way?

p.s. this project needs a shorter name(!)

http://kafka.apache.org/documentation.html#design_pull
> Push vs. pull
>
> An initial question we considered is whether consumers should pull data from brokers or brokers should push data to the consumer. In this respect Kafka follows a more traditional design, shared by most messaging systems, where data is pushed to the broker from the producer and pulled from the broker by the consumer. Some logging-centric systems, such as Scribe and Apache Flume, follow a very different push-based path where data is pushed downstream. There are pros and cons to both approaches. However, a push-based system has difficulty dealing with diverse consumers as the broker controls the rate at which data is transferred. The goal is generally for the consumer to be able to consume at the maximum possible rate; unfortunately, in a push system this means the consumer tends to be overwhelmed when its rate of consumption falls below the rate of production (a denial of service attack, in essence). A pull-based system has the nicer property that the consumer simply falls behind and catches up when it can. This can be mitigated with some kind of backoff protocol by which the consumer can indicate it is overwhelmed, but getting the rate of transfer to fully utilize (but never over-utilize) the consumer is trickier than it seems. Previous attempts at building systems in this fashion led us to go with a more traditional pull model.
>
> Another advantage of a pull-based system is that it lends itself to aggressive batching of data sent to the consumer. A push-based system must choose to either send a request immediately or accumulate more data and then send it later without knowledge of whether the downstream consumer will be able to immediately process it. If tuned for low latency, this will result in sending a single message at a time only for the transfer to end up being buffered anyway, which is wasteful. A pull-based design fixes this as the consumer always pulls all available messages after its current position in the log (or up to some configurable max size). So one gets optimal batching without introducing unnecessary latency.
>
> The deficiency of a naive pull-based system is that if the broker has no data the consumer may end up polling in a tight loop, effectively busy-waiting for data to arrive. To avoid this we have parameters in our pull request that allow the consumer request to block in a "long poll" waiting until data arrives (and optionally waiting until a given number of bytes is available to ensure large transfer sizes).
>
> You could imagine other possible designs which would be only pull, end-to-end. The producer would locally write to a local log, and brokers would pull from that with consumers pulling from them. A similar type of "store-and-forward" producer is often proposed. This is intriguing but we felt not very suitable for our target use cases which have thousands of producers. Our experience running persistent data systems at scale led us to feel that involving thousands of disks in the system across many applications would not actually make things more reliable and would be a nightmare to operate. And in practice we have found that we can run a pipeline with strong SLAs at large scale without a need for producer persistence.

**Comment by kozlovic** [comment]
Similar to Kafka, I guess, so it is both.
Producers send messages to the server (Push). When a subscriber starts, the server will start sending messages to it up to the subscriber's defined MaxInflight (Pull).
Note that when a message is published, and if subscribers are already running, the server will automatically send those messages to the subscribers (again, up to subscriber's MaxInflight).

**Comment by glycerine** [comment]
> When a subscriber starts, the server will start sending messages to it up to the subscriber's defined MaxInflight (Pull).

From the point of view of the consumer, this is push, not pull.

To me, pull means the consumer polls and requests data that starts from a given offset. This facilitates, for instance, recovering from a crash.

How does a consumer request data from the past in nss?

Thanks Ivan.

**Comment by kozlovic** [comment]
Yes, when the subscriber starts, it indicates to the server from which point it wants to receive data (message sequence or time delta). This is a pull.

But after the initial start, all messages that follow are pushed from the server - up to MaxInflight. The MaxInflight is used as a flow control mechanism. When server has sent that many messages without receiving acks from the subscriber, it will stop sending. When receiving acks, when the number of outstanding acks falls below MaxInflight, then server resumes sending messages to subscriber.

**Comment by vjpr** [comment]
@kozlovic This was a bit confusing for me as it is similar to Kafka, but very different.

Say I want to process events in batches of 100, I have to now implement the batching logic in my client code. If we could read a set number of events at a time (pull-based), I would not need to implement this batching logic in each client. This is the beauty of Kafka.

**Comment by kozlovic** [comment]
First let me preface by saying that I do understand that there are benefits to pull vs push. But NATS Streaming was designed with the pull semantic in mind.

> Say I want to process events in batches of 100

Could you clarify what you mean here? Are you suggesting that after receiving/processing those 100 messages you would want the subscription to be closed? Which means that if you want to receive/process the 100 next ones you would create a new subscription?
Because if what you want is simply to slow down the rate at which the server sends you messages, that already exists, and it is called `stan.MaxInflight()`. This option sets the maximum number of messages the server sends to a subscription without receiving message acknowledgements. That is, if set to 1, then server sends a single message. When receiving the message ack, then it sends the next, etc...

> I have to now implement the batching logic in my client code. If we could read a set number of events at a time (pull-based), I would not need to implement this batching logic in each client.

Yes, as of now you could create the subscription with `stan.MaxInflight(100)` (not required, but prevents server from sending the default 1024 messages - if avail - at the start of the subscription) and in the callback keep track of the number of messages you have received and then call `Msg.Sub.Close()` to stop delivery of messages.

**Comment by vjpr** [comment]
@kozlovic PS. My complete use case is here: https://stackoverflow.com/questions/47530962/using-nats-streaming-server-as-the-primary-data-store-for-iot-position-data

**Comment by kozlovic** [comment]
Yes, but you would need to call `msg.Ack()` to actually let the server send you more messages (and avoid a redelivery)
