### ISSUE TITLE
How can I build the server?

### ISSUE THREAD

**Issue by StarpTech** [nats-io/nats-streaming-server#248]
I extract the zip and run `go build` but it throws such errors Thanks!
```
λ go build .\nats-streaming-server.go
# command-line-arguments
.\nats-streaming-server.go:115: cannot use nOpts (type *"github.com/nats-io/gnatsd/server".Options) as type *"github.com/nats-io/nats-streaming-server/vendor/github.com/nats-io/gnatsd/server".Options in argument to "github.com/nats-io/nats-streaming-server/server".ConfigureLogger
.\nats-streaming-server.go:116: cannot use nOpts (type *"github.com/nats-io/gnatsd/server".Options) as type *"github.com/nats-io/nats-streaming-server/vendor/github.com/nats-io/gnatsd/server".Options in argument to "github.com/nats-io/nats-streaming-server/server".RunServerWithOpts
```

**Comment by kozlovic** [comment]
@StarpTech `go build` with vendor involved is very sensitive to the location of the source. If you already have your go environment setup, you should go into `$GOPATH/src/github.com/nats-io/nats-streaming-server` and build from there. It can't be done from another directory, and the directory must be named `nats-streaming-server`.

If you already have that directory from a previous clone, simply update it (from inside this directory):
```
# ensure you are on master
git branch
* master
# update
git pull -p
# build
go build
```

**Comment by StarpTech** [comment]
@kozlovic thanks!
