### ISSUE TITLE
Shared Storage Fault Tolerance

### ISSUE THREAD

**Issue by petemiron** [nats-io/nats-streaming-server#263]
## Goals:

1. Provide a durable messaging solution with server fault tolerance.

## Requirements

1. This solution assumes a FileStore NATS Streaming configuration with a shared, replicated set of physical disks, logically mounted by multiple servers (e.g. an NFS Mount (Gluster in Google Cloud or EFS in Amazon). MemStore can not be used in the Shared Storage Fault Tolerant solution.
1. A Group of NATS Streaming Servers must be configured so that only one NATS Streaming Server is a Primary Node writing to the data store.
1. NATS Streaming Server data shall be redundant across multiple disks in multiple enclosures (separate disk, power, network).
1. All state (messages, clients, subscriptions) updates must be handled by a single Primary Node. The Primary Node must prevent multiple writers and have a method to lock the data files for a single writer -- possibly using NFS locking.
1. NATS Clients must seamlessly reconnect to another server if they were on the failed unresponsive Primary Node.

**Comment by sfrooster** [comment]
What's the expected performance for this solution?  I know that's difficult to answer, but I'd recommend (and personally appreciate, even help contribute to) a MongoDB implementation along side what is proposed above.  This has lots of benefits (one being price) and, I believe, has the possibility to be equally if not more interesting to the community.  I could also be thinking only of myself - hard to tell :-)

**Comment by kozlovic** [comment]
@sfrooster The storage is independent of this feature. The goal here is to have servers that are ready to take over when the active process failed. The storage is shared, it can be file store (the only persistent store that we have at the moment) or a database if an implementation becomes available. The behavior will remain the same: only one server will write/read from the storage.

**Comment by petemiron** [comment]
Removed quorum requirement, as solution for fault tolerance should be able to be started with a single instance.

(removed: 1. An administrator must be able to configure the target group size. Quorum will be determined by (Group Size / 2) +1 and the cluster will not begin operations until Quorum is met.)

**Comment by joeblew99** [comment]
The current design assumes a NAS or SAN backing the NATS streaming server ?

**Comment by kozlovic** [comment]
@joeblew99 In Fault Tolerance mode, yes. Data is not replicated, all servers point to the same shared storage. There is only one active server accessing the store and servicing clients. Standby servers are just there to take over should the active server fail.

A bit of documentation can be found [here](https://github.com/nats-io/nats-streaming-server#fault-tolerance) and [here](https://github.com/nats-io/nats-streaming-server#shared-state).

**Comment by joeblew99** [comment]
@kozlovic ok understood. 
NAS and SAN is going to rule out allot of potential topology use cases. Not many infrastructures have this or want to have it too :)

I wonder if you have considered Minio ? I wont state its properties here as i read that NATS with Minio has been done, so you know what it can and cant do.
