### ISSUE TITLE
Support partitioning by channel

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats-streaming-server#271]
A cluster of NATS streaming servers should be able to distribute work through horizontally partitioning channels.  Each server in a cluster can service a set of channels.  This will increase performance and allow users to scale NATS streaming.

Requirements:
* Allow multiple active servers using the same cluster ID.
* A channel can be serviced by exactly one streaming server at a time.
 
Discussion points:
* Should channel assignments be predetermined, or randomized, or allow both?
* How do we enforce one channel per cluster? (_e.g. Use RAFT consensus to have a leader decide who owns a channel, then have all members update configuration files with white and black lists?_)
* Can channels be "moved"?

**Comment by kozlovic** [comment]
@ColinSullivan1 I would vote for channel assignments being static for this feature. There could be a global flag that instructs the server to only subscribe to a given list of channels (that would reduce traffic, etc). The list could be given through the store limits configuration section (see https://github.com/nats-io/nats-streaming-server/pull/265 also for background, except that we would not delegate this to the store).
The enforcement could be somehow done by servers exchanging their channels list on startup, but ultimately, this is the administrator responsibility to ensure that these are not duplicated.
Also I would vote no for channels being "moved".
Anything more sophisticated would fall more in the clustering feature IMO.

**Comment by ColinSullivan1** [comment]
@kozlovic It would be nice if a configuration could be shared.  If servers were named, the configuration could have server specific lists of channels, and it'd be simple to check for overlaps.  With each cluster member having all information, we could support the equivalent of wildcards in the configuration (superseded by explicit channels).  That way one could say server A handles `foo` and `bar`, server B handles `baz`, and server C handles `*` (or `_unspecified`), indicating all other channels.  Server C handle any channel that was not explicitly listed channel by A or B.

**Comment by kozlovic** [comment]
That would open the door to issues where C starts to handle subject X and then X is later added to A or B, and then you have a problem. 
Already servers checking that its list is not overlapping with another server in the "cluster" is not that simple. First, the check would be made only on startup, and due to NATS message payload limitation, we may need to split the list in many messages, etc.. 
I see the value for wildcards in configuration, but keep in mind that we don't have a sublist in streaming server, although I believe that this is exported from NATS server and have that code accessible in vendor.

**Comment by ColinSullivan1** [comment]
I agree, it could pose headaches if there an implicit agreement that a server would service a channel that a user might want to explicitly list later.  I think it'd be useful to to get input from the community to see if static lists would be acceptable, or if a server should be the overflow for unspecified channels, in case users dynamically create subjects.  Wildcard support in the configuration may suffice there, though.

**Comment by kozlovic** [comment]
But having a servicing "all others" is difficult and I believe not with the scope of this ER. By that I mean that the server would have to know each other server's configuration. And that means that if one of the server in the cluster is not present or started later, we would again end-up with duplicated channels.
Also, the idea that a server would explicitly listen to only the set of static channels would not work with that approach. It would mean that ultimately, all servers would receive all messages and then decide if it should process it or not. That's possible, but add traffic for nothing when a server knows in advance if it should handle a given channel.

**Comment by ColinSullivan1** [comment]
Perhaps starting simple is best, and we can begin with static.  I wouldn't think there'd be design decisions supporting static that would preclude supporting dynamic in the future if it becomes a requirement.
