### ISSUE TITLE
any schedule for virtual destination and wildcards?

### ISSUE THREAD

**Issue by liebo** [nats-io/nats-streaming-server#290]
for example, subscribe to virtual destination like foo.*, and if message is published to destination foo.a and foo.b, both message will be consumed.

**Comment by kozlovic** [comment]
There have been talks, but I believe that providing this feature with current server implementation would be very difficult.

**Comment by liebo** [comment]
Understood. actually I am thinking about a quick alternative using server filtering: Giving a channel foo, there will be foo.a and foo.b messages in this channel. if a client subscribe foo.a, the server will filter foo.b for this client. Is it reasonable?

**Comment by kozlovic** [comment]
I don't see how this would be easier to implement ;-). We are not saying categorically no to wildcard subscriptions. All we know, is it would be difficult to implement and may require some protocol changes. We need to internally review and specify what it would mean. But my guess is that this is not a feature that would be added quickly, if that helps for your planning.

**Comment by kozlovic** [comment]
Closing this issue and use #340 instead for tracking and feedback.
