### ISSUE TITLE
Message reordering

### ISSUE THREAD

**Issue by joeblew99** [nats-io/nats-streaming-server#301]
Is there any ability to do this.
I ask because i have a system for real time streaming collaboration and rather than rely on network clocks i use the context of the message received on the server to slot it ahead or behind other messages in the queue.

**Comment by joeblew99** [comment]
Btw does "Last Value Semantics" have a bearing on this ?
The quoted term is written in the readme but i could not see any clear explanation of what it is.
Am curious :)

**Comment by kozlovic** [comment]
I am not sure what you are asking here. Messages are stored in the channel's message log as they arrive. A message timestamp is assigned when it stored in the server.

The last value means that when you create a subscription, you need to specify a start position in the stream. One of the option (in Go, that would be `StartWithLastReceived()`) is to start receiving from the last message that is currently stored.

**Comment by joeblew99** [comment]
its because the mobiles time stma their mutations and send them in, but i
need to reorder them because i am doing Operational Transforms for
collaboration use cae
its ok i can do it before it hits NATS i think

**Comment by kozlovic** [comment]
Ok, let us know if you have additional questions.
