### ISSUE TITLE
Stream/Topic Discovery

### ISSUE THREAD

**Issue by codmajik** [nats-io/nats-streaming-server#304]
Since nss can't support wildcard (#290) with current implementation. 

I think providing an api to fetch all available streams (ie topics) in the cluster would probably serve most uses cases. The client can then just subscribe to them. 

It could be a special topic that would be polled or subscribed to.

**Comment by kozlovic** [comment]
This would be covered in #116, would you agree? If so, I will close this issue in favor of #116. Thanks!

**Comment by codmajik** [comment]
Yes, it is covered.
