### ISSUE TITLE
Better error message on Connection failure

### ISSUE THREAD

**Issue by ganesh-karthick** [nats-io/nats-streaming-server#309]
When connecting to nats-streaming-server  from go client with a wrong cluster id , Go client returns an error
```
err="stan: connect request timeout"
```
A better error message would help in debugging.

**Comment by kozlovic** [comment]
If you provide a cluster ID not used by any of the servers in the network, no server will respond to the client, hence the timeout error message from the client library. If anything, this is an error message that needs to be updated in the client libraries, not in the server.
