### ISSUE TITLE
Possbile endless loop in memstore/expireMsgs

### ISSUE THREAD

**Issue by vl409** [nats-io/nats-streaming-server#318]
It looks like 'return' statement  is missing here:
https://github.com/nats-io/nats-streaming-server/blob/master/stores/memstore.go#L194
If the 1st message falls under condition, no progress is made in the loop:
elapsed is not updated, as well as current time (calculated before entering the loop).

**Comment by kozlovic** [comment]
You are right, it is the same for the file store implementation.
This test was to protect against time clock going backward, but clearly, the return statement is missing.
PR coming! Thanks a lot for the report.
