### ISSUE TITLE
Nats Mirror Maker

### ISSUE THREAD

**Issue by clanstyles** [nats-io/nats-streaming-server#323]
Does nats or nats streaming server have anything like Kafka Mirror Maker? I'm looking to push the traffic from smaller "edge" regions to the primary nats server that does all the processing.

**Comment by kozlovic** [comment]
No, but as I understand it, the Kafka MirrorMaker is simply a consumer/producer tool that sucks messages from one cluster and publishes to another cluster (I am probably oversimplifying).

With `v0.5.0` coming today (and already in master), you will be able to get the list of channels using monitoring ports. You could have an application connecting to a cluster, getting all channels and creating subscriptions for those, then using a connection to the other cluster, publish all the consumed messages.

**Comment by alahijani** [comment]
Is this still the current answer?
This is a very common use case, for copying data across datacenters where clustering is not desirable. So I hoped there would be an easy way or maybe an out of the box solution.

**Comment by alahijani** [comment]
Thanks @ripienaar, I'll give it a shot.

**Comment by SkinnySackboy** [comment]
@alahijani did you have any luck with this in the end, as I've just seen this post and need to solve a similar problem?
