### ISSUE TITLE
Monitoring routes returns 404

### ISSUE THREAD

**Issue by antonkhabaiev** [nats-io/nats-streaming-server#326]
I've started nats-streaming-server with "-m 8444" args, and it would give me a 
"[1] 2017/06/20 17:18:48.882315 [INF] Starting http monitor on 0.0.0.0:8444"
Per documentation
https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fnats-io%2Fnats-streaming-server%23enabling&sa=D&sntz=1&usg=AFQjCNHUpUK61Nsqa60J2qb9tUSSo2NJ6w

But then when I go to http://localhost:8444 I see regular nats monitoring, not the streaming, and  /streaming, streaming/serverz returns 404.

I'm using docker image, so it's version 0.4.0.

**Comment by kozlovic** [comment]
The release v0.5.0 with monitoring is now available. This should resolve your issue. https://hub.docker.com/_/nats-streaming/

**Comment by shadiakiki1986** [comment]
Why are there 2 official docker images?

- https://hub.docker.com/_/nats/
- https://hub.docker.com/_/nats-streaming/

I was using the `_/nats` image and getting the same issue as OP here
