### ISSUE TITLE
Instance panicks periodically 

### ISSUE THREAD

**Issue by klrkdekira** [nats-io/nats-streaming-server#344]
Hi folks, 

My production instance of nats-streaming panicks every few day.
I'm still investigating this but I'm filing this first just in case you folks know what happened.

The deployment environment is as follow.
The said problematic instance is deployed as a Stateful Set at Kubernetes 1.5, 
using docker image nats-streaming:0.5.0.
The file storage is mounted at Kubernetes NFS Volume.

It might be a few factors, I suspect it is either NFS or when I gzipped my payload (by correlation, it started after I did that). I suspected file sync too, but it still happens after I turned it on.

Here's the log (for the recovery attempts), it happens randomly while running too.
https://pastebin.com/SCW2XQwh

**Comment by kozlovic** [comment]
Thanks for the report. I am having a look and will keep you updated.

**Comment by kozlovic** [comment]
@klrkdekira Thank you for the report. I think I have found the reason for the panic and have a PR (#345) opened. If you want to try and see if it solves your issue, that would be great.

**Comment by klrkdekira** [comment]
It runs fine for 2 days now. Thanks.

**Comment by kozlovic** [comment]
Glad to hear that fixed the issue. Thanks!
