### ISSUE TITLE
Dynamic channels performance

### ISSUE THREAD

**Issue by arunkjn** [nats-io/nats-streaming-server#357]
Hi,

I was planning to use nats streaming as a messaging solution in a microservice architecture. My solution will require me to create a large number of channels dynamically. I wanted to know if there is some limit on the number of channels that can be supported? Or can it be just increased by adding more storage. Also is there any loss in performance with growing number of channels?

**Comment by kozlovic** [comment]
Thank you for your interest!

Could you qualify "large"? Assuming that you would use a streaming server with persistence (the FileStore implementation is the only available at the moment), each channel requires file descriptors. We have added the ability to limit the server to a given number of file descriptors, but it does impact performance since files may need to be opened/closed, etc..

Again, without knowing what number we are talking about it is difficult to say. Few thousands may be ok, but it will also all depend on the volume of data going through, number of subscriptions, etc...
Are those channels long lived? As of now, there is no deletion of channels (except by stopping the server and deleting the sub director(ies) corresponding to the channel(s) that you wish to delete). We plan to add the feature to do that at runtime, but the point is that channels were supposed to be long lived and not used in a very dynamic fashion (for instance as being used as a "reply" subject in a request/reply scenario).

If you could give us a bit more detail on your use case, we may be able to help better.

**Comment by arunkjn** [comment]
Thanks for your reply. 

The number of channels could be in the order of few thousands. They also have a lifecycle which can span from days to months (long lived) or minutes (short lived). Channel management apis like deletion would be helpful here.

We are planning to implement a workflow orchestration service in which a workflow would comprise of a directed acyclic graph in which each node is an independent service and the edges are event from one service, a transformation function and the resultant event to another service. 

The workflow service is responsible for executing the workflow by subscribing to the events of all the services and pushing appropriate messages to the services which need to process them.

In addition to workflow service there would be a messaging service which would provide a gPRC messaging interface for all services including workflow service. This service would be responsible to interface with NATS streaming and use it as a broker to provide messaging service.

Each service would have an independent channel dedicated to it from which it could subscribe. This would be fairly limited and would require a fixed number of long lived topics.
The problem comes at the orchestration service where it would require a workflow based subscription where it would consume all the messages for a particular workflow. The options here are -
1. Create a single channel and use it to publish all events. Filter messages at the messaging service layer and pass them to workflow subscriptions. 
2. Create a channel per workflow and put a workflows messages in its own channel.

I dont see the first option scaling very well with a large number of messages and workflows.
The second option is the use case I am talking about. Please let me know if you need more clarity.

**Comment by kozlovic** [comment]
Again, limitation for now is on file descriptors and disk access. Few thousands channels may be doable depending on your resources, you would have to experiment there.

The next issue I can see is this:

> The workflow service is responsible for executing the workflow by subscribing to the events of all the services and pushing appropriate messages to the services which need to process them.

As of now, there is no support for subscriptions on wildcards (although there are talks on how we would do that #340). Are the channels known a priori by the workflow service? Without wildcard subscription and if that service needs to subscribe to all channels, it also means thousands of subscriptions, just for this service.

As a stop gap to wildcards subscriptions, we have this experimental branch (https://github.com/nats-io/nats-streaming-server/tree/system_channel_for_new_channels_notifications) that would offer a system channel in which events about channels creation (and later if we support deletion) are stored, so one can subscribe to this channel and be notified when a new channel is created and if desired create a subscription on that channel. It does not address the possible huge number of subscriptions that an application would have to create if it wants to subscribe to all channels.

**Comment by arunkjn** [comment]
I was thinking of the workflow service as one logical service which has multiple instances managing a set of workflows. Since each workflow would have a dedicated topic, any instance would need to create only as many subscriptions as the number of workflows it is managing. This would eliminate the need for wildcard subscription and also one service managing many subscriptions.

**Comment by kozlovic** [comment]
It seems that it would then be possible. The investment in trying NATS Streaming is pretty low. The API set is limited (in a good way) and the server can be started with minimal or no configuration (you may want to look at https://github.com/nats-io/nats-streaming-server#configuring to see what you *could* configure if you need). Therefore, I think that you should easily be able to plug NATS Streaming in your overall design. If it does not work for you, please let us know and we will see if there is anything we can do to make it work for you. Ultimately, if this is not the right fit, as I said, you will not have invested a lot in trying it out.

Closing for now. Thanks again for your interest!

**Comment by arunkjn** [comment]
Thank you. will definitely try it out. Cheers!
