### ISSUE TITLE
Expose durable queue subscriptions through monitoring endpoint

### ISSUE THREAD

**Issue by bruth** [nats-io/nats-streaming-server#385]
The use case is to observe all durable subscriptions and their current state with respect to the channel. I had assumed they were at first since the subscription payload contains the `is_offline` flag, but the entire subscription entry is gone when it disconnects.

**Comment by kozlovic** [comment]
@bruth I have checked that master behaves correctly. That is, a durable subscription that is closed is still showing in the list of subscriptions and the flag `is_offline` is set to true. The latest published release `v0.5.0` had a defect where durable subscription would be listed twice.

Are you sure you are not calling `Unsubscribe()` on application exit? If you call unsubscribe, then the durable subscription is removed, so it makes sense that it disappears. Also, make sure you are not in a situation where you restart the server without file store, in which case no state is restored.

**Comment by bruth** [comment]
I too am using the latest master and it is still occurring. I am not unsubscribing from the channel and the file store is being used. I am pulling data from `/streaming/channelsz?subs=1`.

**Comment by kozlovic** [comment]
I start a nats-streaming-server with `-m 8222` and connect a durable subscription called "dur" on channel "foo":
```
{
  "cluster_id": "test-cluster",
  "server_id": "LsEnpaLsnyyRfQTI273wM2",
  "now": "2017-09-04T14:33:30.667273766-06:00",
  "offset": 0,
  "limit": 1024,
  "count": 1,
  "total": 1,
  "channels": [
    {
      "name": "foo",
      "msgs": 0,
      "bytes": 0,
      "first_seq": 0,
      "last_seq": 0,
      "subscriptions": [
        {
          "inbox": "_INBOX.1lqT5vW0JaOT8pRBokhe8A",
          "ack_inbox": "_INBOX.LsEnpaLsnyyRfQTI273wQ6",
          "durable_name": "dur",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 0,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    }
  ]
}
```
I then stop the subscription (making sure not to call `Unsubscribe()`, and as you can see the subscription is still listed and `is_offline` is set to true:
```
{
  "cluster_id": "test-cluster",
  "server_id": "LsEnpaLsnyyRfQTI273wM2",
  "now": "2017-09-04T14:34:55.870983239-06:00",
  "offset": 0,
  "limit": 1024,
  "count": 1,
  "total": 1,
  "channels": [
    {
      "name": "foo",
      "msgs": 0,
      "bytes": 0,
      "first_seq": 0,
      "last_seq": 0,
      "subscriptions": [
        {
          "inbox": "_INBOX.1lqT5vW0JaOT8pRBokhe8A",
          "ack_inbox": "_INBOX.LsEnpaLsnyyRfQTI273wQ6",
          "durable_name": "dur",
          "is_durable": true,
          "is_offline": true,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 0,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    }
  ]
}
```
Can you please send in a reproducible test case?

**Comment by bruth** [comment]
Ok, I see the difference. I did your test case and used `conn.Subscribe` with a durable name. That worked as you showed. I have been using the `QueueSubscribe` with a durable name and I can confirm that it no longer shows in the subscription list (foo2) when I close.

Response:

```json
{
  "cluster_id": "test-cluster",
  "server_id": "8BQ0Wogb50uVYW5xf6GbSS",
  "now": "2017-09-04T17:09:44.535137279-04:00",
  "offset": 0,
  "limit": 1024,
  "count": 2,
  "total": 2,
  "channels": [
    {
      "name": "foo",
      "msgs": 0,
      "bytes": 0,
      "first_seq": 0,
      "last_seq": 0,
      "subscriptions": [
        {
          "inbox": "_INBOX.1yiQjmk4J27zZPNUCMlpT1",
          "ack_inbox": "_INBOX.8BQ0Wogb50uVYW5xf6Gbds",
          "durable_name": "foo",
          "is_durable": true,
          "is_offline": true,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 0,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    },
    {
      "name": "foo2",
      "msgs": 0,
      "bytes": 0,
      "first_seq": 0,
      "last_seq": 0
    }
  ]
}
```

Code:

```go
package main

import (
	"context"
	"log"
	"os"
	"os/signal"

	stan "github.com/nats-io/go-nats-streaming"
)

func main() {
	conn, err := stan.Connect("test-cluster", "client-1", stan.NatsURL("nats://localhost:4224"))
	if err != nil {
		log.Fatal(err)
	}

	sub, err := conn.QueueSubscribe("foo2", "foo2", func(*stan.Msg) {}, stan.DurableName("foo"))
	if err != nil {
		log.Fatal(err)
	}

	ctx, cancel := context.WithCancel(context.Background())

	sig := make(chan os.Signal)
	signal.Notify(sig, os.Kill, os.Interrupt)

	go func() {
		select {
		case <-sig:
			cancel()
		}
	}()

	<-ctx.Done()
	if err := sub.Close(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by bruth** [comment]
Funny, I am reviewing my own snippet.. no need for `ctx`, just block on `sig`.

**Comment by kozlovic** [comment]
@bruth I see. This is a bug, I will have a fix and test for this today. Thanks!

**Comment by bruth** [comment]
👍 Thanks @kozlovic

**Comment by kozlovic** [comment]
@bruth You are welcomed! Thank to you for reporting the issue!
