### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by sachinwalia2k8** [nats-io/nats-streaming-server#396]
I am wondering if it is possible to switch for a faster release cadence such as monthly so that community can also contribute in testing.

**Comment by ColinSullivan1** [comment]
@sachinwalia2k8 , thank you for bringing this up.  We do have plans to move to a more frequent release schedule.

**Comment by kozlovic** [comment]
We will try to release more frequently, at least once a month if there has been fixes/features added.
