### ISSUE TITLE
Channel aliasing

### ISSUE THREAD

**Issue by bruth** [nats-io/nats-streaming-server#397]
This is inspired by [ElasticSearch's aliases feature](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html).

The use case is the ability to transparently and atomically swap out a channel by name with live subscriptions. This would enable migrating a channel without interruption to active clients. One specific use case is migrating a historical log of events in the context of Event Sourcing. Table 1 in [this paper](http://files.movereem.nl/2017saner-eventsourcing.pdf) describes effectively the full set of _migrations_ that may need to be done over the long term. Having the ability to perform these operations and atomically swap out the physical underlying stream would make more a very seamless experience.

That being said, I wholly acknowledge the potential issue with the managing positions in the durable subscriptions since that would need to be concrete. Assuming the alias swapping would be atomic, new clients should not be affected unless they have some preconceived position in mind. But that would be on the developer to manager since they are also performing the migration. For active clients, specifically subscribers, the atomic swap would likely need to happen once each subscriber reads messages up to the moment the switch occurs and only subsequent messages would be consumed.

Another issue is deliberately creating streams. If publishers and subscribers are assumed to use the alias, that presupposes the existence of the concrete stream. Since publishers nor subscribers would be using that concrete stream directly, there would need to be a mechanism for initializing it so the alias could be associated with it. This _could_ be implicit. If an alias `foo` is defined to map to `foo.0` then `foo.0` would be implicitly created and designated the target for published message for `foo`. 

There are likely other implications such as security and channel limits that may need to be fleshed out. One constraint that may be worthwhile is to require aliases to be a superset of the concrete channels. That is, an alias `foo.bar.baz` will require concrete channels to be versioned or at least a child of the path, e.g. `foo.bar.baz.0`.

One thing to clarify is that in order for a migration pattern to work, publishers still need to be able to publish to the concrete channels like `foo.bar.baz.0` or `foo.bar.baz.1` in lieu of the alias. A faux function may look like this:

```go
func Migrate(source, target string, handle func(msg *stan.Msg)) {
    // Subscribe to old version and publish to the new one..
}

Migrate("foo.bar.baz.0", "foo.bar.baz.1", func(msg *stan.Msg) {
   // ...
})
```

To prevent downtime or a missed migration, this would likely need to stay online while the alias swap occurs so any final messages are migrated. Since the swap would be atomic, messages published to `foo.bar.baz` would simply be routed to the new version of the channel.

Like I said.. there may be other factors at play here, but I wanted to share the idea and general semantics around the idea.

**Comment by bruth** [comment]
Looking at the code snippet, I suppose if there was a built-in function that assumed a migration strategy, it could be reduced to:

```go
Migrate("foo.bar.baz", func(msg *stan.Msg)) {
   // ...
})
```

Any the version would be incremented behind the scenes relative to the current concreted version.

**Comment by ColinSullivan1** [comment]
@bruth , thanks for opening this.  We're revisiting issues in the near future, and will discuss this.
