### ISSUE TITLE
Auto-generate nats-streaming user when using embedded server.

### ISSUE THREAD

**Issue by petemiron** [nats-io/nats-streaming-server#400]
A user `{username, password}` should be automatically generated when using an embedded NATS server and any form of authentication is configured.

This reduces configuration when using multiple user auth and will improve observability over time.

**Comment by kozlovic** [comment]
Decided not to implement that because that would not allow admin to configure permissions/etc.. so instead added ability to add user/password/token/nkey in config file (#1100)
