### ISSUE TITLE
Clustering: Raft group partitioning

### ISSUE THREAD

**Issue by tylertreat** [nats-io/nats-streaming-server#409]
This is regarding the current WIP implementation of clustering.

With the current clustering design (Raft group per channel), we have two issues which remain more or less unresolved:

1) If a channel is created while a node is offline or if we add a *new* node to the cluster, how does the node discover the channel and know to join the Raft group?

2) The overall design of Raft-per-channel has inherent scalability problems.

One option to address problem 1 is to have nodes in the cluster gossip the channels they know about, but my thought is we could tackle both of these issues at the same time if we rethink how we structure our Raft groups.

Instead of using a Raft group per channel, we could have a fixed number of Raft groups and use a hash ring to map a channel to a Raft group. Creating a channel would then be a Raft operation, which would solve problem 1. Also, we would have a bounded number of Raft groups, which would solve problem 2.

We could then make the number of Raft groups tunable so that users could configure it based on their use case. If you know you will only have 10 channels, you probably want 10 Raft groups, but if you know you'll have 10,000 channels, perhaps you only want 1,000 Raft groups. In the future, we may want to take this idea even further and do something similar to [what CockroachDB did](https://www.cockroachlabs.com/blog/scaling-raft/) to scale Raft.

Using a hash ring would potentially allow users to add/remove Raft groups as we would only need to rehash a portion of the channels. However, I haven't yet thought through how this would work with Raft.

Overall, I think this would help immensely with the scalability of clustering with respect to channels, and it also addresses the channel "discovery" problem, which in my opinion needs to be fixed before an MVP.

**Comment by kozlovic** [comment]
The current beta brought the number of Raft groups to only 1. Having raft group for meta data and channels made it impossible to safely apply the raft entries in correct order. Closed with #434
