### ISSUE TITLE
Clustering: file store snapshotting

### ISSUE THREAD

**Issue by tylertreat** [nats-io/nats-streaming-server#410]
This is regarding the current WIP implementation of clustering.

Currently, the way channel messages are snapshotted is by snapshotting the first and last sequence of the channel and storing all messages in between. This can repeatedly fail if the channel is constantly being truncated due to exceeding size limits, etc. Snapshot failure will prevent Raft log compaction from happening.

If we assume using the file store with clustering, snapshotting channel messages could simply be a matter of copying the contents of the store files. Restoring is then a matter of dropping the file store contents and replacing it with the snapshot contents. This is safe because replication does not proceed until a follower has finished restoring from a snapshot. This would then solve the "rolling snapshot" problem.

To start, we should probably require using the same store type in all nodes within a cluster, but we could potentially transform snapshot types to make them compatible with different store types.

**Comment by kozlovic** [comment]
Closed with #434
