### ISSUE TITLE
A problem when useing nats-streaming on natsd cluster

### ISSUE THREAD

**Issue by xiaomi-tc** [nats-io/nats-streaming-server#419]
I deployed a natsd cluster include two nodes.  A nats-streaming-server attached  on natsd node A, and a sub_client connected to node B to subscribe nats-streaming messages.  The pub_client publish messages.   Everything seems OK, sub_client can receive messages from nats-streaming-server currectly.  
　　But when nats-streaming-server restarted,  sub_client can't received messages any more, unless restart sub_client too.  
　　Can this problem be solved?  

***Topologic  graph:***
nats-streaming-server <--> natsd-A(cluster-1) <=======>natsd-B(cluster-1)<-->sub_client
      /\\
      ||  
pub_client

**Comment by kozlovic** [comment]
Are you using `-store file -dir <datastore>` or not? If not it means that you are using memory store which has no persistence. See https://github.com/nats-io/go-nats-streaming/issues/157 for instance.

**Comment by xiaomi-tc** [comment]
It's ok since using "-store file --dir ...".    thank you
