### ISSUE TITLE
Can I change nats-streaming-server auth options dynamically?

### ISSUE THREAD

**Issue by rafw** [nats-io/nats-streaming-server#426]
Add/Edit/Remove user and pass for server when server is running.

**Comment by ColinSullivan1** [comment]
@rafw , Yes you can, if the NATS streaming server is running standalone connected to an external core NATS server (gnatsd).  

By default, the NATS streaming server launches an embedded core NATS server, which uses credentials stored in the configuration file you pass.  You can direct the NATS streaming server to connect to an external NATS server instead (configured with your credentials), and use the NATS server configuration reload feature to reload credentials.

To achieve this:

1) Launch the core NATS server (gnatsd) separately with your credentials in its configuration file.
2) Launch the NATS streaming server with the `-ns <url>` parameter to have it connect to the core NATS server (gnatsd).  e.g.  `-ns nats://localhost:4222`
3) Alter the credentials in the gnatsd configuration file as required.
4) Reload credentials with `gnatsd -sl reload` (more information can be found [here](https://github.com/nats-io/gnatsd#process-signaling)).

**Comment by rafw** [comment]
Great.
