### ISSUE TITLE
Unable to flush msg store: fsync: input/output error

### ISSUE THREAD

**Issue by byrnedo** [nats-io/nats-streaming-server#439]
Got this error this morning, first time I've seen this.
We run a very minimal setup with external nats server. Using file store of course.

version:
nats-streaming-server version 0.5.0, nats-server version 0.9.6

Logs: newest at bottom
```
November 30th 2017, 06:53:44.967		/go/src/github.com/nats-io/nats-streaming-server/server/server.go:2435 +0xe7
November 30th 2017, 06:53:44.966	created by github.com/nats-io/nats-streaming-server/server.(*StanServer).startIOLoop
November 30th 2017, 06:53:44.965	github.com/nats-io/nats-streaming-server/server.(*StanServer).ioLoop(0xc420079180, 0xc4215f2820)
November 30th 2017, 06:53:44.965		/go/src/github.com/nats-io/nats-streaming-server/server/server.go:2520 +0x6b5
November 30th 2017, 06:53:44.951		/usr/local/go/src/runtime/panic.go:500 +0x1a1
November 30th 2017, 06:53:44.907	panic(0x867660, 0xc42012c450)
November 30th 2017, 06:53:44.907	goroutine 38 [running]:
November 30th 2017, 06:53:44.906	 - 
November 30th 2017, 06:53:44.905	panic: Unable to flush msg store: fsync: input/output error
```

**Comment by kozlovic** [comment]
@byrnedo Unfortunately, there is not much that can be done here. The system call `sync()` failed with an `EIO` error code, which means that there was a problem flushing pending I/O operations to disk.
Where is your store located? Is it a local disk, a mounted one? Check for out-of-space or mount issues, etc...

**Comment by byrnedo** [comment]
@kozlovic Ah, okay. We have quite a small amazon ebs volume. Space is fine, I'll look for mount issues. I only saw this once, when stan restarted everything was fine again.

**Comment by kozlovic** [comment]
Closing for now, please re-open if you get any new information.
