### ISSUE TITLE
When will the cluster version be released?

### ISSUE THREAD

**Issue by leenux** [nats-io/nats-streaming-server#450]
I found the doc `Streaming clustering with full replication of data across a set of streaming servers is planned for later this year.`
Because our payment system planned to use nats-streaming, it does not want a single point of failure.
We hope to know when released and rank our plan,Thank you.

**Comment by tylertreat** [comment]
There is currently a preview branch of clustering (https://github.com/nats-io/nats-streaming-server/tree/clustering_mvp_integration). We are waiting on additional feedback from the community before releasing.

**Comment by leenux** [comment]
@tylertreat 
Thank you very much.
I will test the branch.
