### ISSUE TITLE
Issue with "clustering_mvp_integration" branch: "Failed to make RequestVote RPC"

### ISSUE THREAD

**Issue by rse** [nats-io/nats-streaming-server#451]
I've NATS Server running in a cluster of 5 Servers and want to attach clustered NATS Streaming Server to this NATS Server cluster now. For this I've installed the latest snapshot of the "clustering_mvp_integration" branch as of 2017-12-17 to try it out.

Unfortunately, I guess I've overlooked something, because it isn't working as expected. Certainly a configuration error on my side, but after a few hours configuring back and forth I've
to confess: I've no more clue how to fix it. Hence, this mail to you in the hope you can shed some light onto my situation.

I've 5 machines in the cluster named soe1, soe2, soe3, soe4 and soe5. All have NATS Server and NATS Streaming Server running. The configs and logs of all five machines I've attached to the end
of this issue after freshly firing up all services, let them running for some seconds and then stopping them again.

If you look into the logs of NATS Streaming Server you can see that the RAFT protocol has trouble. As far as I understand your implementation, you are running RAFT over NATS and in the NATS Server logs there are also messages related to this RAFT protocol. But it seems the servers
do not find theirself via NATS in their RAFT protocol communication. On all servers I always get messages like:

```
[47030] 2017/12/16 15:54:01.562496 [INF] STREAM: Node at
soe1.soe1._metadata [Candidate] entering Candidate state in term 231
[47030] 2017/12/16 15:54:01.782237 [INF] STREAM: Failed to make
RequestVote RPC to {Voter soe3 soe1.soe3._metadata}: nats: timeout
[47030] 2017/12/16 15:54:01.782277 [INF] STREAM: Failed to make
RequestVote RPC to {Voter soe2 soe1.soe2._metadata}: nats: timeout
[47030] 2017/12/16 15:54:01.782343 [INF] STREAM: Failed to make
RequestVote RPC to {Voter soe4 soe1.soe4._metadata}: nats: timeout
[47030] 2017/12/16 15:54:01.782408 [INF] STREAM: Failed to make
RequestVote RPC to {Voter soe5 soe1.soe5._metadata}: nats: timeout
```

According to the sources, the "nats: timeout" comes from
the NATS client library while the "Failed to make RequestVote RPC"
comes from the RAFT library. So, seems like the RAFT over NATS
protocol does not work for my sitation, although one can see
messages on the NATS Server side.

I really would like to get your clustered NATS Streaming Server
running, as it is the last puzzle on this cluster of machines
I'm seeking for.

Do you have any clue what I've done wrong?

The configurations and logs fo NATS Server and NATS Streaming Server (branch "clustering_mvp_integration") follow (both servers code base as of 2017-12-17):

[soe1-nats-server.conf.txt](https://github.com/nats-io/nats-streaming-server/files/1568601/soe1-nats-server.conf.txt)
[soe1-nats-server.log.txt](https://github.com/nats-io/nats-streaming-server/files/1568602/soe1-nats-server.log.txt)
[soe1-nats-streaming-server.conf.txt](https://github.com/nats-io/nats-streaming-server/files/1568603/soe1-nats-streaming-server.conf.txt)
[soe1-nats-streaming-server.log.txt](https://github.com/nats-io/nats-streaming-server/files/1568604/soe1-nats-streaming-server.log.txt)
[soe2-nats-server.conf.txt](https://github.com/nats-io/nats-streaming-server/files/1568606/soe2-nats-server.conf.txt)
[soe2-nats-server.log.txt](https://github.com/nats-io/nats-streaming-server/files/1568607/soe2-nats-server.log.txt)
[soe2-nats-streaming-server.conf.txt](https://github.com/nats-io/nats-streaming-server/files/1568608/soe2-nats-streaming-server.conf.txt)
[soe2-nats-streaming-server.log.txt](https://github.com/nats-io/nats-streaming-server/files/1568609/soe2-nats-streaming-server.log.txt)
[soe3-nats-server.conf.txt](https://github.com/nats-io/nats-streaming-server/files/1568610/soe3-nats-server.conf.txt)
[soe3-nats-server.log.txt](https://github.com/nats-io/nats-streaming-server/files/1568612/soe3-nats-server.log.txt)
[soe3-nats-streaming-server.conf.txt](https://github.com/nats-io/nats-streaming-server/files/1568613/soe3-nats-streaming-server.conf.txt)
[soe3-nats-streaming-server.log.txt](https://github.com/nats-io/nats-streaming-server/files/1568614/soe3-nats-streaming-server.log.txt)
[soe4-nats-server.conf.txt](https://github.com/nats-io/nats-streaming-server/files/1568615/soe4-nats-server.conf.txt)
[soe4-nats-server.log.txt](https://github.com/nats-io/nats-streaming-server/files/1568616/soe4-nats-server.log.txt)
[soe4-nats-streaming-server.conf.txt](https://github.com/nats-io/nats-streaming-server/files/1568617/soe4-nats-streaming-server.conf.txt)
[soe4-nats-streaming-server.log.txt](https://github.com/nats-io/nats-streaming-server/files/1568618/soe4-nats-streaming-server.log.txt)
[soe5-nats-server.conf.txt](https://github.com/nats-io/nats-streaming-server/files/1568619/soe5-nats-server.conf.txt)
[soe5-nats-server.log.txt](https://github.com/nats-io/nats-streaming-server/files/1568620/soe5-nats-server.log.txt)
[soe5-nats-streaming-server.conf.txt](https://github.com/nats-io/nats-streaming-server/files/1568621/soe5-nats-streaming-server.conf.txt)
[soe5-nats-streaming-server.log.txt](https://github.com/nats-io/nats-streaming-server/files/1568622/soe5-nats-streaming-server.log.txt)

**Comment by tylertreat** [comment]
@rse I'm taking a look and will let you know what I find.

**Comment by tylertreat** [comment]
@rse The `id` field in the config file actually corresponds to a cluster id, not a node id (the node id is the `node_id` field). All of your NATS Streaming servers in the cluster should have the same cluster id. Right now, they each have a unique id: `soe1`, soe2`, etc.

**Comment by rse** [comment]
Ops, great catch! Sorry, I was not aware that the "id" is actually the cluster id. I've now switched all 5 servers to an "id" of "soe" and: voila, it no more trouble in starting up the cluster. All servers now play together and at least elected a leader and on killing the leader automatically re-elected a new leader. Many thanks for your support. I'll now continue playing with NATS Streaming Server in the cluster mode by also _using_ the service (and not just trying to start it up).
