### ISSUE TITLE
Partitioning ft_group on 3 kubernetes nodes

### ISSUE THREAD

**Issue by gertcuykens** [nats-io/nats-streaming-server#453]
This works on a stateful 3 node kubernetes set where each node gets a stream pod, but it seems when enabling partitions you can only have 1 active and 1 standby instead of 1 active and 2 standby (one on each node) The 3 one will crash with rpc limit reached?
```
https: 0.0.0.0:8222
listen: 0.0.0.0:4222
tls {
  cert_file: "/etc/nats/tls/nats.pem"
  key_file:  "/etc/nats/tls/nats-key.pem"
  ca_file:   "/etc/nats/tls/ca.pem"
  verify:   true
}
authorization {
  user:     nats_client_user
  password: nats_client_pwd
}
debug:   true
trace:   true
logtime: true
max_connections: 100
max_control_line: 512
max_payload: 65536
write_deadline: "2s"

cluster {
  listen: 0.0.0.0:6222
  tls {
    cert_file:  "/etc/nats/tls/nats.pem"
    key_file:   "/etc/nats/tls/nats-key.pem"
    ca_file:    "/etc/nats/tls/ca.pem"
  }
  authorization {
    user: nats_route_user
    password: nats_route_pwd
  }
  routes = [
    nats://nats_route_user:nats_route_pwd@nats:6222
  ]
}

streaming {
  cluster_id: nats-streaming
  nats_server_url: nats://nats_client_user:nats_client_pwd@nats:4222
  store: FILE # MEMORY
  dir: "/store"
  ft_group: "ftg"
  secure: true
  tls {
    client_cert: "/etc/nats/tls/nats.pem"
    client_key:  "/etc/nats/tls/nats-key.pem"
    client_ca:   "/etc/nats/tls/ca.pem"
  }
  partitioning: false
  store_limits {
    channels {
      bench-subject {}
    }
  }
}
```
Ps feel free to comment on my config if you see mistakes, thx
Also I think that having a `client {...}` is going to be less confusing so you can have 3 config blocks client cluster and streaming

**Comment by kozlovic** [comment]
Few things:
- Not sure what the "rpc limit reached" issue is, but does not sound like it is coming from NATS Streaming.
- The NATS related configuration details above will be ignored due to the presence of `nats_server_url` parameter, which basically means that the Streaming server should connect to a separate NATS Server running at that address.
- For FT to work, the datastore needs to be shared (accessible) to all FT members, not sure if that is what you have in your configuration?

**Comment by gertcuykens** [comment]
If rpc limit reached is not a error coming from NATS or STAN then I can assume its my kubernetes config. The thing that confuses me is if I do just `partitioning: false` instead of `partitioning: true`and leave everything the same I don't get any error and everything works as expected on 3 nodes. 2 STAN's on standby 1 active. Reacting immediately if I kill the active pod, one of the standby pods take over. Maybe just coincidence.

**Comment by ColinSullivan1** [comment]
@gertcuykens , just following up.  Is this still an issue?  If so, would you have a log we can see that shows the rpc limit error you are encountering?

**Comment by gertcuykens** [comment]
![image](https://user-images.githubusercontent.com/863731/35190082-9498fee2-fe59-11e7-9f82-507187d0f743.png)
to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF

![image](https://user-images.githubusercontent.com/863731/35190089-d5aae382-fe59-11e7-9e07-9e078131e42d.png)

![image](https://user-images.githubusercontent.com/863731/35190095-ebc6481e-fe59-11e7-8f67-a63544e42b55.png)

**Comment by gertcuykens** [comment]
When partitioning is false everything works as expected

![image](https://user-images.githubusercontent.com/863731/35202301-19fa43de-ff22-11e7-96a6-1bd2b72d41ef.png)

**Comment by kozlovic** [comment]
@gertcuykens I think I understand what is going on with partitioning and FT, and I am even surprised that you can get one of the standby to be running at all...
Will take a closer look today.

**Comment by kozlovic** [comment]
@gertcuykens Would you be able to test with the code from PR #458 and see if it resolves your issue? Thanks!
