### ISSUE TITLE
TLS config inconsistency between NATS and STAN

### ISSUE THREAD

**Issue by gertcuykens** [nats-io/nats-streaming-server#454]
Can the following differences be ironed out please

```
tls {
  cert_file: "/etc/nats/tls/nats.pem"
  key_file:  "/etc/nats/tls/nats-key.pem"
  ca_file:   "/etc/nats/tls/ca.pem"
  verify:   false
}
```

```
  secure: true
  tls {
    client_cert: "/etc/nats/tls/stan.pem"
    client_key:  "/etc/nats/tls/stan-key.pem"
    client_ca:   "/etc/nats/tls/ca.pem"
  }
```
Can both use `verify` please and `xxx_file` I understand why you used `client_cert` but still when used inside `streaming {}` it should not matter.

Simplicity is one of the the features of NATS yet the config of STAN can be confusing compared to NATS

I think it's worth breaking backward compatibility and clean it up.

**Comment by kozlovic** [comment]
The `verify` makes sense only from the (NATS) server perspective, the process accepting the TLS connection. When you configure both TLS sections in NATS Streaming, you are indicating that the Streaming server should embed the NATS Server. The Streaming server then needs to have a `tls` section that configures the ability of the streaming server to connect to the embedded NATS server.

To make it easier to setup first, I would recommend that you run the NATS Server standalone and simply configure the Streaming server has you would for a client. 

Also, check https://github.com/nats-io/nats-streaming-server#tls for more details.

**Comment by gertcuykens** [comment]
Ok thank you for your response. In my eyes the verification parameters to indicate to verify a CA certificate should be identical for server and client. Something like
```
  secure: true
  tls {
    server_cert: "/etc/nats/tls/stan.pem"
    server_key:  "/etc/nats/tls/stan-key.pem"
    server_ca:   "/etc/nats/tls/ca.pem"
  }
```
```
  secure: true
  tls {
    client_cert: "/etc/nats/tls/stan.pem"
    client_key:  "/etc/nats/tls/stan-key.pem"
    client_ca:   "/etc/nats/tls/ca.pem"
  }
```
Maybe it just boils down to personal preference I guess
