### ISSUE TITLE
Using external -ns seems to fail using master

### ISSUE THREAD

**Issue by eigood** [nats-io/nats-streaming-server#457]
In my local project, we have nats-streaming-server talking to an external nats-server.  Today, this failed.  We compile master against both projects.

I was able to work around it by removing the -ns, removing the nats-server from my docker-compose, and reconfiguring everything to talk to the embeded nats server of nats-streaming.

**Comment by eigood** [comment]
This is using the new 0.7.0 of nats-streaming-server.

**Comment by ripienaar** [comment]
How exactly did it fail?

**Comment by eigood** [comment]
It says 'no servers available' after printing the nats-server connection info.

**Comment by eigood** [comment]
I'll give a log in a few minutes.

**Comment by kozlovic** [comment]
This parameter instructs the NATS Streaming server to connect to a remote NATS Server, so make sure that the NATS Server is running *and* reachable at that address.

**Comment by eigood** [comment]
[19] 2018/01/19 18:42:29.331304 [INF] STREAM: Starting nats-streaming-server[mlo] version 0.7.0
[19] 2018/01/19 18:42:29.331320 [INF] STREAM: ServerID: SjO4v8YGKmNMWaEDrAxMnS
[19] 2018/01/19 18:42:29.331322 [INF] STREAM: Go version: go1.7.4
[19] 2018/01/19 18:42:29.331349 [TRC] STREAM:  NATS conn opts: { [nats://nats-server:4222] false _NSS-mlo-send false false false <nil> true -1 250ms 2s 0s 2m0s 2 0x4e92f0 0x4e9340 0x4e92a0 <nil> 0x4e9230 8388608 8192    <nil> false}
[19] 2018/01/19 18:42:31.331513 [INF] STREAM: Shutting down.
[19] 2018/01/19 18:42:31.331534 [FTL] STREAM: Failed to start: nats: no servers available for connection

**Comment by eigood** [comment]
I have 2 docker containers, nats-server, and nats-streaming-server.  Other clients are able to connect directly to nats-server, and I see in it's log that stuff is occurring.  It's just nats-streaming-server that fails to connect.

**Comment by kozlovic** [comment]
Maybe `nats-server` is not resolving properly from the NATS Streaming server's host.

**Comment by eigood** [comment]
nats-server does resolve, I have a WAIT_HOSTS environment set, that my control script then loops on, using getent to make certain it resolves.

**Comment by kozlovic** [comment]
The docker image is using Golang 1.9.2 to build the 0.7.0 streaming server. I see in the output above that you are using Golang 1.7.4. Did you build your own docker image?

**Comment by eigood** [comment]
The compile didn't fail, if it really requires that version, then it should fail and not produce any output.

**Comment by eigood** [comment]
I have a 'compile' phase in docker, that volume mounts from the host, compiles a bunch of stuff, then saves it in $TOP_DIR(in this case, $TOP_DIR/externals/go).  I then make use of those output binaries at runtime(again, as a volume mount, but I could just as easily embed them directly into a pre-built image).

**Comment by kozlovic** [comment]
I was just pointing out that the docker image is built with Golang 1.9.2 and I see a different version indicating that it is not the "official" image. I don't have an issue with master and `-ns` and there was no change that I know of about this command line in master.
Did it use to work before? What changed?

**Comment by eigood** [comment]
I have golang-1.8 installed via stretch-backports, 1.9 is only available in buster.  We can't use buster.  It's been working fine for months with this config, and today when my coworker recompiled, did it fail.  I have not attempted to find the commit that broke this.

**Comment by eigood** [comment]
I don't use community go images.  I compile all the go-using stuff once, and save the output, and at runtime, I use stretch-slim, with the compiled go binaries.  This has less of a surface area exposed(no golang at runtime).

**Comment by eigood** [comment]
I can look at this in more detail later, but I have a meeting in 1.25 hours, and need to get back to frontend dev.  I'm glad you're paying attention.

**Comment by kozlovic** [comment]
I just built locally a docker image using nats streaming master and Golang 1.7.4 and run it connecting to a separate container running NATS server and it works fine. Not sure what is wrong with your setup.
![screen shot 2018-01-22 at 12 55 38 pm](https://user-images.githubusercontent.com/13736691/35241448-bcb6ba66-ff73-11e7-9fa5-c97479fd6148.png)

**Comment by kozlovic** [comment]
Could it be that you simply changed the port NATS Server is running on? Maybe it is not 4222?

**Comment by eigood** [comment]
We've changed all ports of all services to be non-defaults, and then configured all the isolated docker instances to use the non-default ports, using whatever configuration is provided by the software.  This is to prevent accidentally connecting to a host-run process.

I haven't yet had a chance to debug this further, but do plan on doing so.

**Comment by kozlovic** [comment]
You've reported this:
```
[19] 2018/01/19 18:42:29.331322 [INF] STREAM: Go version: go1.7.4
[19] 2018/01/19 18:42:29.331349 [TRC] STREAM: NATS conn opts: { [nats://nats-server:4222] false _NSS-mlo-send false false false true -1 250ms 2s 0s 2m0s 2 0x4e92f0 0x4e9340 0x4e92a0 0x4e9230 8388608 8192 false}
[19] 2018/01/19 18:42:31.331513 [INF] STREAM: Shutting down.
[19] 2018/01/19 18:42:31.331534 [FTL] STREAM: Failed to start: nats: no servers available for connection
```
As you can see, the URL the streaming server tries to connect to is: `nats://nats-server:4222`, and `4222` is the default NATS Server port. So if you have started NATS Server to a non default port, and forgot to change the `-ns` to point to that port, that would explain it.
Will wait for your feedback.

**Comment by kozlovic** [comment]
Closing for now, please re-open if you still have the issue.
