### ISSUE TITLE
Garbage Collecting Channels

### ISSUE THREAD

**Issue by notbdu** [nats-io/nats-streaming-server#459]
Even if we continually increase the max channel limit, we will hit a wall at some point (e.g. max fds). 

Would it be possible for STAN to support garbage collection of unused channels after hitting channel limits?

**Comment by kozlovic** [comment]
Closing this, please refer to #358. Thanks!

**Comment by notbdu** [comment]
Ah, sorry @kozlovic! Poor searching on my part, this particular issue didn't come up.

**Comment by kozlovic** [comment]
No worries. Please add feedback on that other issue if you want. Thanks!
