### ISSUE TITLE
Unable to run nats-streaming-server docker image

### ISSUE THREAD

**Issue by daghb** [nats-io/nats-streaming-server#462]
After downloading the latest image nats-streaming/0.8.0-beta I am unable to run nats-streaming-server

`docker run nats-streaming nats-streaming-server -p 4223 -m 8223`

always gives me this response regardless of parameters to nats-streaming-server

```
unrecognized command: "nats-streaming-server"
Usage: nats-streaming-server [options]
[...]
```

**Comment by kozlovic** [comment]
Otherwise, do not specify the executable name. So it should be:
```
docker run nats-streaming -p 4223 -m 8223
```

**Comment by daghb** [comment]
Ah, thanks @kozlovic, that worked.
