### ISSUE TITLE
Erroneous docker hub documentation

### ISSUE THREAD

**Issue by daghb** [nats-io/nats-streaming-server#463]
The documentation calls for a default run command like
`$ docker run nats-streaming-server nats-streaming-server -p 4223 -m 8223`

but this should read

`$ docker run nats-streaming nats-streaming-server -p 4223 -m 8223`

**Comment by kozlovic** [comment]
Thanks, I will fix that. Also keep in mind that this is only for Windows docker image, and only if you need to pass parameters from the command line:
```
Windows Docker image

Due to restrictions on how the Windows Docker Image is built, running the image without argument will run the NATS Streaming server with memory based store on port 4222 and the monitoring port 8222. If you need to specify any additional argument, or modify these options, you need to specify the executable name as this...
```

**Comment by daghb** [comment]
Thanks a lot, @kozlovic. When using Portainer to orchestrate nats-streaming, I have to supply an entrypoint regardless of this. I tried /nats-streaming-server and it seems to run. Perhaps it's worth noting somewhere that there is a way to supply an entrypoint regardless of the setting in the generating Dockerfile and where it may be found?

Another typo in the Docker Hub docs:

`Run a NATS Streaning server`

should read

`Run a NATS Streaming server`

**Comment by kozlovic** [comment]
@daghb You mean something like this?

```
docker run -ti --entrypoint /nats-streaming-server nats-streaming -p 4223 -m 8223
```

**Comment by daghb** [comment]
Yes, this should give Portainer users a clue

**Comment by kozlovic** [comment]
@daghb It should have been addressed in https://github.com/docker-library/docs/pull/1146.
Thanks again for the report!
