### ISSUE TITLE
Subscription not removed from client after subscription error

### ISSUE THREAD

**Issue by AshfordN** [nats-io/nats-streaming-server#467]
If a client subscribes to a channel and there is an error, the subscription fails, but the entry is not removed from the client. To reproduce this, allow 2 clients to subscribe to channel "foo.bar" using the following configuration file:

`store_limits {
	channels: {
		"foo.bar": {
			max_subs: 1
		}
	}
}`

The bug should occur when the second client attempts to subscribe to the channel. This can be checked at the **clientsz** endpoint (/streaming/clientsz?subs=1)

**Comment by kozlovic** [comment]
@AshfordN Thank you for the report. I will work on a fix later today.

**Comment by kozlovic** [comment]
@AshfordN Not sure if you will get a chance to test, but PR #468 should fix this issue. Thanks!

**Comment by AshfordN** [comment]
Yeah it works! Thanks
