### ISSUE TITLE
Segmentation violation in cluster mode and latest docker container

### ISSUE THREAD

**Issue by sega-yarkin** [nats-io/nats-streaming-server#474]
Hi guys!
I've just tested latest version of NATS Streaming in cluster mode with 3 nodes and got `panic: runtime error: invalid memory address or nil pointer dereference`.

My steps:
1) Create 3 data directories (`srv1`, `srv2`, `srv3`)
2) Put simple `nats.conf` in each data directory (ports end with 1, 2 and 3 respectively):
```
port: 4231
http_port: 8231
store: "file"
dir: "/data"
cluster {
  host: '10.10.0.100'
  port: 5231
  bootstrap: true
  raft_logging: true
  routes = [
    nats-route://10.10.0.100:5232
    nats-route://10.10.0.100:5233
  ]
}
```
3) Start 3 docker containers:
`docker container run -it --name nats1 -v ${PWD}/srv1:/data --network=host nats-streaming -c /data/nats.conf`
4) Do some simple tests to be sure everything is working.
5) Start 3 consumers (just commented out printing every messages):
```
stan-sub -s nats://10.10.0.100:4231 -id 1 --qgroup qgtest -all test
stan-sub -s nats://10.10.0.100:4232 -id 2 --qgroup qgtest -all test
stan-sub -s nats://10.10.0.100:4233 -id 3 --qgroup qgtest -all test
```
6) Start data producer:
```
stan-bench -s nats://10.10.0.100:4231 -np 1 -ns 0 -n 10000000 -ms 1000 -a test
```

After several minutes second and third containers started printing errors:
```
...
[1] 2018/02/14 20:32:31.100452 [ERR] STREAM: [Client:benchmark-pub-1] Error replicating message for subject "_STAN.pub.test-cluster.test": timed out enqueuing operation
[1] 2018/02/14 20:32:31.100464 [ERR] STREAM: [Client:benchmark-pub-97] Error replicating message for subject "_STAN.pub.test-cluster.test": timed out enqueuing operation
[1] 2018/02/14 20:32:31.100475 [ERR] STREAM: [Client:benchmark-pub-94] Error replicating message for subject "_STAN.pub.test-cluster.test": timed out enqueuing operation
[1] 2018/02/14 20:32:31.100485 [ERR] STREAM: [Client:benchmark-pub-97] Error replicating message for subject "_STAN.pub.test-cluster.test": timed out enqueuing operation
...
```

and then:
```
[1] 2018/02/14 20:32:27.598057 [ERR] STREAM: [Client:benchmark-pub-85] Error replicating message for subject "_STAN.pub.test-cluster.test": timed out enqueuing operation
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x87e359]

goroutine 70 [running]:
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).removeFirstMsg(0xc42009a340, 0x0, 0xc42ec9af00)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2647 +0x69
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).enforceLimits(0xc42009a340, 0x1e0001, 0xc4531b12c0, 0xc447f7b801)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2589 +0xa2
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).Store(0xc42009a340, 0xc4531b12c0, 0x0, 0x0, 0x0)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2482 +0xb99
github.com/nats-io/nats-streaming-server/server.(*StanServer).Apply(0xc4201ea000, 0xc450f849a0, 0xdfe320, 0x3)
	/go/src/github.com/nats-io/nats-streaming-server/server/server.go:4498 +0x176
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc44b13b1e0)
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/fsm.go:57 +0x17b
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).runFSM(0xc4200e1340)
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/fsm.go:120 +0x31e
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).(github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.runFSM)-fm()
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/api.go:506 +0x2a
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc4200e1340, 0xc420180500)
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/state.go:146 +0x53
created by github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*raftState).goFunc
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/state.go:144 +0x66
```

After restarting failed containers:
```
$ docker container start -ai nats2
[1] 2018/02/14 20:34:30.879042 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.8.0-beta
[1] 2018/02/14 20:34:30.879082 [INF] STREAM: ServerID: PIWf5lutLWcVp9fYVr2WFY
[1] 2018/02/14 20:34:30.879087 [INF] STREAM: Go version: go1.9.3
[1] 2018/02/14 20:34:30.879323 [INF] Starting nats-server version 1.0.4
[1] 2018/02/14 20:34:30.879554 [INF] Starting http monitor on 0.0.0.0:8232
[1] 2018/02/14 20:34:30.879671 [INF] Listening for client connections on 0.0.0.0:4232
[1] 2018/02/14 20:34:30.879685 [INF] Server is ready
[1] 2018/02/14 20:34:30.880552 [INF] Listening for route connections on 10.10.0.100:5232
[1] 2018/02/14 20:34:30.906597 [INF] STREAM: Recovering the state...
[1] 2018/02/14 20:34:31.373113 [INF] STREAM: Recovered 1 channel(s)
[1] 2018/02/14 20:34:33.298825 [INF] STREAM: raft: Initial configuration (index=1): [{Suffrage:Voter ID:ib2LAFTTccvyusMmcYgM9D Address:test-cluster.ib2LAFTTccvyusMmcYgM9D.stan}]
[1] 2018/02/14 20:34:33.298939 [INF] STREAM: raft: Node at test-cluster.ib2LAFTTccvyusMmcYgM9D.stan [Follower] entering Follower state (Leader: "")
[1] 2018/02/14 20:34:33.300337 [INF] STREAM: Message store is RAFT_FILE
[1] 2018/02/14 20:34:33.300415 [INF] STREAM: ---------- Store Limits ----------
[1] 2018/02/14 20:34:33.300425 [INF] STREAM: Channels:                  100 *
[1] 2018/02/14 20:34:33.300431 [INF] STREAM: --------- Channels Limits --------
[1] 2018/02/14 20:34:33.300436 [INF] STREAM:   Subscriptions:          1000 *
[1] 2018/02/14 20:34:33.300443 [INF] STREAM:   Messages     :       1000000 *
[1] 2018/02/14 20:34:33.300449 [INF] STREAM:   Bytes        :     976.56 MB *
[1] 2018/02/14 20:34:33.300456 [INF] STREAM:   Age          :     unlimited *
[1] 2018/02/14 20:34:33.300464 [INF] STREAM: ----------------------------------
[1] 2018/02/14 20:34:35.169644 [INF] STREAM: raft: Heartbeat timeout from "" reached, starting election
[1] 2018/02/14 20:34:35.169694 [INF] STREAM: raft: Node at test-cluster.ib2LAFTTccvyusMmcYgM9D.stan [Candidate] entering Candidate state in term 3
[1] 2018/02/14 20:34:35.169961 [INF] STREAM: raft: Election won. Tally: 1
[1] 2018/02/14 20:34:35.169977 [INF] STREAM: raft: Node at test-cluster.ib2LAFTTccvyusMmcYgM9D.stan [Leader] entering Leader state
[1] 2018/02/14 20:34:35.170079 [INF] STREAM: server became leader, performing leader promotion actions
[1] 2018/02/14 20:34:38.276052 [INF] STREAM: WARNING: Reached limits for store "test" (msgs=963311/1000000 bytes=976.56 MB/976.56 MB), dropping old messages to make room for new ones
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x87e359]

goroutine 92 [running]:
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).removeFirstMsg(0xc42023a000, 0x0, 0xc4203e1600)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2647 +0x69
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).enforceLimits(0xc42023a000, 0x1e0001, 0xc42172aa50, 0xc422016a01)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2589 +0xa2
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).Store(0xc42023a000, 0xc42172aa50, 0x0, 0x0, 0x0)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2482 +0xb99
github.com/nats-io/nats-streaming-server/server.(*StanServer).Apply(0xc4201ee000, 0xc4203354a0, 0xdfe320, 0xbe99453790618e89)
	/go/src/github.com/nats-io/nats-streaming-server/server/server.go:4498 +0x176
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc4202ec2d0)
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/fsm.go:57 +0x17b
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).runFSM(0xc4200d0000)
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/fsm.go:120 +0x31e
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).(github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.runFSM)-fm()
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/api.go:506 +0x2a
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc4200d0000, 0xc4202ec150)
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/state.go:146 +0x53
created by github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*raftState).goFunc
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/state.go:144 +0x66
```

**Comment by kozlovic** [comment]
@sega-yarkin You should not set `bootstrap` to true! You are basically making all cluster nodes the leader. The first thing I noticed is when you stated that each node was containers started to report `Error replicating message for subject`. Only 1 node (the leader) should ever report that since only the leader should be replicating.
Also, the datastore should not be shared by these 3 instances, and it looks like you are doing it?

**Comment by sega-yarkin** [comment]
@kozlovic If we have empty data directory we can not start first node, but it has looked working when all nodes have this flag. Now I have the flag only for first node (every test I start with empty data directories), but nothing changed: every nodes got `invalid memory address or nil pointer dereference` in 10-15 minutes after test is started. Every container has own data directory, nothing is shared.

**Comment by kozlovic** [comment]
There is definitively and issue, several even. But having more than one node with the `-cluster_bootstrap` is a misconfiguration. The doc [here](https://github.com/nats-io/nats-streaming-server#clustering-auto-configuration) states that only 1 node (the seed) should have this set.
I probably need to make this more obvious in the doc and maybe add some defensive code in the server to try to detect this misconfiguration (this would lead otherwise to probably corrupted stores).

As for the panic here, I think I understand what's going on. There is a timeout used to schedule the "apply" of a log entry through raft, timeout that really we should not be using. The troubling part is that the timeout is 5 seconds and that means that the server/container/etc.. is really not able to keep up.
With the misconfiguration I was able to reproduce outside of docker by lowering the timeout down to 1ms (instead of 5secs), but with proper configuration I was not.

Still, it brought to the surface issues that need to be addressed.
- The first step will be to remove timeouts, this will apply back pressure to the publisher though, so you may start to see publishers reporting Publisher Ack Timeout errors (the benchmark tool is not reporting those and so we should fix that too).
- Second, ensure consistency with message sequences when errors occur on publish. The cause of the panic is that the server ended up storing messages with a gap in sequence, which the FileStore implementation was not designed for . So either make sure server never schedule storage of a message with a gap in sequence or have Store implementations tolerant of that.

Thanks again for the report.

**Comment by kozlovic** [comment]
@sega-yarkin Just an update that I have made some progress and may have a PR sometime tomorrow.

**Comment by sega-yarkin** [comment]
@kozlovic Hi, I've just built new docker container with last source code and have the same error:
```
[1] 2018/03/01 20:34:17.146415 [INF] STREAM: raft: Snapshot to 138210 complete
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x844209]

goroutine 61 [running]:
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).removeFirstMsg(0xc4201921a0, 0x0, 0xc42ec01700)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2658 +0x69
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).enforceLimits(0xc4201921a0, 0x620001, 0xc4326d4190, 0xc4244de001)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2600 +0xa2
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).Store(0xc4201921a0, 0xc4326d4190, 0x0, 0x0, 0x0)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2493 +0xb99
github.com/nats-io/nats-streaming-server/server.(*StanServer).Apply(0xc420176500, 0xc42033c810, 0xe323e0, 0xbe9e36e47378e544)
	/go/src/github.com/nats-io/nats-streaming-server/server/server.go:4900 +0x268
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc43185a030)
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/fsm.go:57 +0x17b
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).runFSM(0xc42035e000)
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/fsm.go:120 +0x31e
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*Raft).(github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.runFSM)-fm()
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/api.go:506 +0x2a
github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc42035e000, 0xc420290370)
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/state.go:146 +0x53
created by github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft.(*raftState).goFunc
	/go/src/github.com/nats-io/nats-streaming-server/vendor/github.com/hashicorp/raft/state.go:144 +0x66
```

**Comment by kozlovic** [comment]
I have been running servers with smaller bytes limits and file slices to increase the chance of removing messages from head of channel and I have not been able to reproduce so far.
This was running with local executables. I will try to build the docker image and run them and see if it makes a difference.
Anything more info that you could give in the steps to reproduce would be appreciated. For instance, were the 3 nodes running all the time and just having 3 queue subs and 1 prod blasting messages? Did you stop/restart some of the servers and or apps? Any specific configuration that you may have changed compared to initial report? (well, except for bootstrap that should now cause a failure if running on all nodes).
Did you build from master? If could you give the commit ID (so I build from the same)?
Thanks!

**Comment by sega-yarkin** [comment]
I've built from master (d28a98c) and I used the same way to test as in the first message, you're completely right about the situation.

**Comment by kozlovic** [comment]
@sega-yarkin Just an update that I am still working on this issue. I was not able to reproduce the issue, but was able to find another possible panic, which I have a PR for that.

I could add defensive code to prevent the panic that you have reported, I think, but I would prefer to be able to understand how this can happen in the first place. I believed that the fix in #477 should have solved the problem. I will continue the investigation.

Thanks for your patience!

**Comment by kozlovic** [comment]
Have you been able to reproduce with empty datastore? (the previous runs with `-cluster_bootstrap` would have left them in an incorrect state). How long does it take for you to reproduce the crash? I still haven't been able to. Any chance you can provide the logs if each node when you get it to crash (with a test starting from scratch)? Thanks!

**Comment by kozlovic** [comment]
I noticed something: you are not providing the `-cluster_log_path`, which means that the instance will use the <cluster name>/<node id> as the path for the raft logs. Since this is a docker container, the raft state will be lost if you restart the instance, resulting in possible wrong leader election (if you use bootstrap). You need to provide `-cluster_log_path data` so that the raft state is persisted along side the Streaming data. If you do that and cleanup the state first, are you then able to reproduce the issue?

**Comment by sega-yarkin** [comment]
@kozlovic Before starting every test I cleaned all data directories and start from scratch:
1) Start first node with `bootstrap: true`
2) Start second and third nodes without `bootstrap` flag
Once one container crashed I stop the test. I will try to reproduce it again and provide more logs.

**Comment by kozlovic** [comment]
Thanks, but please check my last comment too. I understand that if you were not stopping/restarting the servers as part of the test it should not really matter, but this is important.

**Comment by sega-yarkin** [comment]
I started 3 new empty containers (without any previous state), and then ran load testing without any interaction with containers (left my system in a while). [Here are console outputs of all containers.](https://gist.github.com/sega-yarkin/2abfd960af7a85004724f7277437cfa9) Raft logs are very big (about 4-5 gigs). Commit is the same as before.

**Comment by kozlovic** [comment]
@sega-yarkin If you really built from the commit you mentioned (https://github.com/nats-io/nats-streaming-server/commit/d28a98c6d748ef8539ffcaffa163954fc22b4a53)
this is what the version would be (0.9.0): https://github.com/nats-io/nats-streaming-server/blob/d28a98c6d748ef8539ffcaffa163954fc22b4a53/server/server.go#L41
However, your severs are still 0.0.8-beta: https://gist.github.com/sega-yarkin/2abfd960af7a85004724f7277437cfa9#file-nats1-console-L2
So I wonder if you are not still running with old code?

**Comment by kozlovic** [comment]
How are you building your docker image?

**Comment by kozlovic** [comment]
Yes, so for sure you are still running 0.8.0-beta. Look at the stack:
```
github.com/nats-io/nats-streaming-server/server.(*StanServer).Apply(0xc4201f4000, 0xc4243e75f0, 0xdfe320, 0xbe9e92e8c556db13)
	/go/src/github.com/nats-io/nats-streaming-server/server/server.go:4498 +0x176
```
server.go:4498 is where we call `c.store.Msgs.Store()` in 0.8.0-beta. In 0.9.0 (master) this would be line 4898.

**Comment by sega-yarkin** [comment]
@kozlovic  Ohh, sorry for misinformation, I've chosen wrong container, I'm going to run 0.9.0

**Comment by sega-yarkin** [comment]
Before it can failed in 15-20 minutes after start, but now it's working well more that 30 minutes, it's very strange. Yesterday it was the last commit according to the stack and it failed. The difference is raft logs located in mounted volume now (the same as data directory). I will run test over the weekends, and then will try with previous configuration.

**Comment by kozlovic** [comment]
Ensure that you run 0.9.0, but then, if you don't specify `log_path` and reproduce the issue, make sure that the container was in no way restarted. If it was, then there would be no RAFT state recovered (since the `/<cluster name>/` directory would not be recovered) but streaming state recovered, which would lead to inconsistent state (I will try to see if I can add code to detect such situation and fail the startup). Thanks again for your patience and running those tests!

**Comment by kozlovic** [comment]
@sega-yarkin Have you had a chance to run more tests? Were you able to reproduce if you are using the proper path for raft logs? (I am planning to add code to detect situations where there is no raft log but there is a streaming store and bail out).

**Comment by sega-yarkin** [comment]
@kozlovic Yes, I ran test during last weekends with raft logs path and I wasn't able to reproduce it, I don't know how it was possible before (it definitely was the latest commit). I will try to run tests without log path and message here if I be able to reproduce the panic. Thank you!
