### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by cemremengu** [nats-io/nats-streaming-server#487]
Any plans for an admin UI? I checked but dont think any community projects exists as well.

I like NATS but kind of feel in the dark without a control/admin panel :thinking:  Even something simple would be great.

**Comment by cemremengu** [comment]
Just discovered `nats-top` which should be enough for most purposes

**Comment by kozlovic** [comment]
As discussed in Slack, yes, `nats-top` can help but it is more geared toward NATS core. Please have a look at monitoring endpoints for NATS Streaming. Here is the link to the doc in the README: https://github.com/nats-io/nats-streaming-server#monitoring

**Comment by bergkvist** [comment]
Some other ones worth looking at:
- https://www.npmjs.com/package/nats-streaming-ui
- https://github.com/KualiCo/nats-streaming-console

**Comment by ArmorDarks** [comment]
All those UI dashboards are abandoned and do not provide the ability to publish messages which is handy for development.

After those years, maybe something changed about the plans for the official dashboard? Something like [Redis UI](https://redis.com/redis-enterprise/redis-insight/)

**Comment by kozlovic** [comment]
@ArmorDarks NATS Streaming Server has been deprecated (see notice here: https://github.com/nats-io/nats-streaming-server#warning--deprecation-notice-warning). There are no plans to work on GUI for this project.

You should look at migrating to NATS JetStream, which is part of NATS Server: https://github.com/nats-io/nats-server: https://docs.nats.io/nats-concepts/jetstream

**Comment by ArmorDarks** [comment]
@kozlovic sorry, didn't notice it's streaming server repository. My question was about UI for `nats-server`

**Comment by kozlovic** [comment]
Please open an issue on for that repo then (https://github.com/nats-io/nats-server). There may be plans for providing one or some may exist from the community.
