### ISSUE TITLE
Production readiness

### ISSUE THREAD

**Issue by cemremengu** [nats-io/nats-streaming-server#488]
Is nats-streaming-server considered production ready yet? 

I know its still in 0.x but looks solid to me so far.

**Comment by kozlovic** [comment]
It is being used in production already by various users. You may find some posts from users in our blog interesting: https://nats.io/categories/community/

The clustering feature is currently beta. I have received some feedback reports and fixed some bugs. I may soon merge the PR about channel deletion and make a new release removing the beta status for clustering.
