### ISSUE TITLE
Track client consumption offset

### ISSUE THREAD

**Issue by jmwilkinson** [nats-io/nats-streaming-server#491]
Is there any way to track the offset consumption of a client? So you know if they are caught up or behind in consuming a subject? I haven't managed to find anything in the docs about this.

**Comment by kozlovic** [comment]
You should look at monitoring: https://github.com/nats-io/nats-streaming-server#monitoring

For instance this kind of query: http://localhost:8222/streaming/channelsz?channel=foo&subs=1
would allow you to know what is the last sequence in the channel, and what is the last sent to a specific subscription.

**Comment by kozlovic** [comment]
Closing for now, will re-open if you still have issues.

**Comment by jmwilkinson** [comment]
Sorry for the delay in responding.

This is very helpful, but it would be nice to have some clarification around those query parameters. They do not appear to be explicitly documented anywhere, and it is unclear precisely what they do. On a related note, are those the only parameters available, or are there others?

In the docs, you get back the following when saying `subs=1`:

```
{
  "name": "foo",
  "msgs": 704770,
  "bytes": 105698990,
  "first_seq": 1,
  "last_seq": 704770,
  "subscriptions": [
    {
      "client_id": "me",
      "inbox": "_INBOX.jAHSY3hcL5EGFQGYmfayvC",
      "ack_inbox": "_INBOX.J3Odi0wXYKWKFWz5D5uhem",
      "is_durable": false,
      "is_offline": false,
      "max_inflight": 1024,
      "ack_wait": 30,
      "last_sent": 704770,
      "pending_count": 0,
      "is_stalled": false
    },
    {
      "client_id": "me2",
      "inbox": "_INBOX.jAHSY3hcL5EGFQGYmfaywG",
      "ack_inbox": "_INBOX.J3Odi0wXYKWKFWz5D5uhjV",
      "is_durable": false,
      "is_offline": false,
      "max_inflight": 1024,
      "ack_wait": 30,
      "last_sent": 704770,
      "pending_count": 0,
      "is_stalled": false
    },
    (...)
  ]
}
```

What does that `1` refer to? Is it a particular subscriber group and this is listing their subscriptions? Is it an individual subscriber?

Also, just to be clear, the lag of a particular subscription is `last_seq - last_sent`. Is this true? Also, is the `last_sent` referring to the last sent *and* acknowledged, or just the last sent without any sort of acknowledgement on the client side? In other words, if you were to restart a client, would it pick up at `last_sent` every time?

Thanks for your help.

**Comment by kozlovic** [comment]
The `1` in `subs=1` is just to trigger the listing of subscriptions. I do document that in the Monitoring chapter in the README:
```
You can also get the list of subscriptions with subs=1. For example: http://localhost:8222/streaming/channelsz?limit=1&offset=0&subs=1.
```

For a given subscription `last_sent` is the message sequence of the newest message sent to a subscription. It does not mean that this message was acknowledged. Note that an application can acknowledge out of order, so the monitoring endpoint does not give you the list of message sequences missing acknowledgment, but it offers `pending_count` which is the number of messages that are not yet acknowledged.

If you restart a *durable* subscription, then the server will first attempt to redeliver unacknowledged messages and then resume at the `last_sent`+1.

**Comment by jmwilkinson** [comment]
When I said it wasn't documented, I just meant what the option meant. I didn't realize the `subs` value was a boolean and we were just turning it on.

Thanks for the explanation of what is happening. That really clarifies things. One additional question on `pending_count`: is that the number of sent but unacknowledged messages, or is that *all* possible acknowledgements that have yet to occur, i.e., if the channel had 2000 messages and the client had acknowledged 1000 and 100 were in flight, would the `pending_count` be 100 or 1000? Thanks!

**Comment by kozlovic** [comment]
`pending_count` is the number of messages sent to a subscriptions for which there is no acknowledgment yet. So in your example it would be 100, not 1000. Notice that the `pending_count` should be at max `max_inflight` since this is the maximum number of messages without acknowledgement the server should send to a subscription.

Also, keep in mind that a subscription does not have to consume all messages in a channel, so if your channel has 2000 messages, a subscription could well start at sequence 1000 when created.

**Comment by jmwilkinson** [comment]
Fantastic, I think I understand what the various pieces mean. Thanks a bunch! Really helped to clarify this.
