### ISSUE TITLE
Performance cap when using multiple producers/consumers

### ISSUE THREAD

**Issue by jmwilkinson** [nats-io/nats-streaming-server#494]
It looks like clustering does not appear to scale around more nodes- i.e., there is a soft cap around the message throughput for a cluster.

*(Subsequent test were performed an a 3 node multi-host cluster)*

Using the benchmarks in the `node-nats-streaming` client:

### Single Producer
With a single producer, we see throughput of about 15-16k msg/second.

```
++++++++++
Received 100000 msgs in 6361ms (15720 msgs/sec)
```

### Producer and Consumer
With both a producer and consumer we see a **total** transmit rate of about 19k msg/s, so for the producer a rate of about 8k and the consumer around 10k. This is close to halving the rate at which we can producer messages.

#### Producer
```
++++++++++
Received 100000 msgs in 12042ms (8304 msgs/sec)
```

#### Consumer
```
subscribed to foo qgroup:undefined
Received 100000 msgs in 9399ms (10639 msgs/sec)
```

### N Producers
This soft cap on throughput appears to be regardless of channel and combination of producers or consumers. With 3 producers on 3 different channels, we total about 17-18k msg/s.

#### Producer A
```
$ node bench/bench-pub.js foo 1234
++++++++++
Received 100000 msgs in 17255ms (5795 msgs/sec)
```

#### Producer B
```
$ node bench/bench-pub.js bar 1234
++++++++++
Received 100000 msgs in 16987ms (5886 msgs/sec)
```

#### Producer C
```
$ node bench/bench-pub.js baz 1234
++++++++++
Received 100000 msgs in 16983ms (5888 msgs/sec)
```

Furthermore, most likely the 2-3k variance between a single producer and multiple has to do with the benchmarking launch delay.

---

So appears to leave a few possibilities:

1. There is a setting somewhere specifying a cluster-level cap for in-flight messages.
2. This is a behavior localized to my network. Others who perform the test will not see these results.
3. This is a result of the RAFT protocol and the NATS-streaming implementation.

In the case of `1`, I would like to know what that setting is, and can it be removed.
If the reason is `2`, please provide the results on another network that show the differing behavior and I can try to pinpoint precisely why my network would behave this way.

Now, the third reason is problematic. I am unsure how to leverage clustering and the implied horizontal scaling if there is a throughput soft cap across the entire cluster. I would be interested to know if this is a well-known behavior and if there are plans or discussion on how to solve it.

Thanks!

**Comment by kozlovic** [comment]
The current implementation is not going to scale with adding more nodes (there will be simply more data to replicate). The clustering feature, as it is today, solves availability, not scalability.

PS: If you could use go bench tool to see if you get the same results. But again, NATS Streaming clustering performance is not going to increase with adding more nodes to the cluster.

**Comment by jmwilkinson** [comment]
Is there a plan or strategy in place to address this in the future? Are there any milestones around releasing a version that will scale out with cluster size?

**Comment by kozlovic** [comment]
There have been thoughts about a different approach, but nothing concrete and at least no timeline at this point.

**Comment by kozlovic** [comment]
Closing this issue for now.
