### ISSUE TITLE
Change the max message size

### ISSUE THREAD

**Issue by jmwilkinson** [nats-io/nats-streaming-server#502]
Is there a way to change the max message size NATS can receive? Currently there is the FAQ here: https://nats.io/documentation/faq/#msgsize stating a cap of 1MG, but there is no documentation around changing that.

**Comment by wallyqs** [comment]
You can tune the NATS server by setting `max_payload` to the value in bytes with the new limit: https://github.com/nats-io/gnatsd#configuration-file

```
# maximum payload
max_payload: 65536
```

**Comment by kozlovic** [comment]
Closing this issue now.

**Comment by iwittkau** [comment]
There is no `may_payload` configuration option in `nats-streaming-server`. I can only find `--max_bytes` which is described as "Max messages **total** size per channel".  
Is the maximum payload size fixed to 1048576 bytes? Because thats what my client with `NatsConn().MaxPayload()` is returning.

**Comment by kozlovic** [comment]
@iwittkau Check the comment above. You *can* change the max payload size with `max_payload` in the configuration file (not in the `streaming` section though). But that would work only if you are running NATS Streaming Server with embedded NATS server (the default). Also, if you have FT or Clustering in place, make sure all servers have the same configuration.

**Comment by iwittkau** [comment]
@kozlovic thanks for the clarification. I wasn't aware that the embedded `nats-streaming-server` accepts `NATSOptions`.  
I was able to set the payload size in an embedded server with the following code 
```
