### ISSUE TITLE
Is cluster participation recovery supported when using the SQL store?

### ISSUE THREAD

**Issue by activeshadow** [nats-io/nats-streaming-server#508]
I noticed in the [Clustering Configuration](https://github.com/nats-io/nats-streaming-server#clustering-configuration) of the README it states the following:
```
As long as the file store is used, this ID will be recovered on restart.
```
Does this mean the cluster node ID is not stored in the DB when the SQL store is used, and thus recovery when using the SQL store for a cluster is not supported?

**Comment by kozlovic** [comment]
Please see the note that I added in #511. You can use SQL but there will still be a need to store data locally (and this data should be recoverable on restart).

**Comment by activeshadow** [comment]
@kozlovic in the [Supported Stores](https://github.com/nats-io/nats-streaming-server#supported-stores) section you added, you mention the following:

> The location of the RAFT stores defaults to the current directory under a sub-directory named after the cluster ID, or you can configure it using `--cluster_log_path`.

I'm not seeing what the **current directory** would be by default, so I'm assuming the best way to use cluster mode in Kubernetes would be to create a PVC for the RAFT file store, and set manually set `--cluster_log_path` to point to the mount point for the PVC. Can you confirm?

**Comment by kozlovic** [comment]
Yes, I would recommend using `--cluster_log_path` in the context of k8s or Docker.
