### ISSUE TITLE
NATS Streaming server clustering in Docker Swarm tutorial?

### ISSUE THREAD

**Issue by MarsWarrior** [nats-io/nats-streaming-server#513]
## Expected Behaviour

A nice Docker Swarm tutorial to setup a NATS Streaming Cluster :smile: 

## Current Behaviour

The documentation clearly states how to deploy a NATS Cluster in Docker Swarm. This also works great!

We need however a NATS Streaming cluster. 
It is unclear to us how to deploy a nats-streaming cluster in Docker Swarm using the Docker NATS Streaming image v08.beta. 
We did try to setup one with 0.8beta, but failed. This might have to do with the 0.8beta of course...

## Possible Solution

1. Can you explain how to do this for now?
2. Add a cluster tutorial to the documentation (it seams v0.9 of NATS Streaming is around the corner??) ??

## Steps to Reproduce (for bugs)

1. N/A

## Context

We want to use a NATS Streaming cluster for OpenFaaS and our microservices backbone.

## Your Environment

* NATS Streaming `0.8beta`

* Docker version `17.12` (e.g. Docker 17.12):

* Are you using Docker Swarm or Kubernetes?
Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 16.04 LTS

**Comment by jacktuck** [comment]
There is a good README if you look at https://hub.docker.com/_/nats/ and https://hub.docker.com/_/nats-streaming/

**Comment by MarsWarrior** [comment]
Thanx for those links.
However the fact is that those are meant for just Docker, not Docker Swarm.
For NATS there is a nice one: https://nats.io/documentation/tutorials/nats-docker-swarm/

Now what I didn't know until you linked to that documentation, is that you can link a NATS Streaming server to an existing NATS server.

However, how should that work with Docker Swarm? That is what we are looking for!

**Comment by kozlovic** [comment]
Will ask around if there is anyone that has done that yet and will get back to you.

**Comment by MarsWarrior** [comment]
Thanx!

**Comment by kozlovic** [comment]
Sorry for the delay. @wallyqs do you think it would be possible to create one for streaming based on the one that exists for core NATS? Or is the operator a higher priority?

**Comment by wallyqs** [comment]
Sounds good, just made a PR to the docs site to include a simple example of joining a cluster for NATS Streaming: https://github.com/nats-io/nats-streaming-server/issues/513
