### ISSUE TITLE
clustering: support own node id in closer peers

### ISSUE THREAD

**Issue by primalmotion** [nats-io/nats-streaming-server#521]
Right now in order to start a 3 node nats-streaming-server cluster you must do:

```
node0: --cluster_id a --cluster_peers b,c
node1: --cluster_id b --cluster_peers a,c
node2: --cluster_id c --cluster_peers a,b
```

Doing this doesn't work:

```
node0: --cluster_id a --cluster_peers a,b,c
node1: --cluster_id b --cluster_peers a,b,c
node2: --cluster_id c --cluster_peers a,b,c
```

This doesn't make life easy on a  kubernetes statefulset.

If nats-streaming was simply pruning its own ID from the `cluster_peers` list, it would be very easy to write

```
node0: --cluster_id $(HOSTNAME) --cluster_peers ns-0,ns-1,ns-2
node1: --cluster_id $(HOSTNAME) --cluster_peers ns-0,ns-1,ns-2
node2: --cluster_id $(HOSTNAME) --cluster_peers ns-0,ns-1,ns-2
```

**Comment by kozlovic** [comment]
As discussed on Slack, this seem like a good idea. Thanks!

**Comment by primalmotion** [comment]
And as discus

**Comment by primalmotion** [comment]
Wrong button sorry :)

As discussed on slack too I’ll open a PR
