### ISSUE TITLE
NATS Streaming server in Docker container does not expose a volume for FILE persistance

### ISSUE THREAD

**Issue by tpihl** [nats-io/nats-streaming-server#541]
I have some issues setting up a streaming cluster using the official streaming image.

There is no provisions to manage a persistent --dir, and it may be bad to put that inside the container fs overlay.

The cluster_peers needs a way to (through any loadbalancer or similar) reach the underlaying nats cluster if you want to use the embedded nats server.

Would it be possible to add VOLUME /data and maybe also expose port 5552?

**Comment by kozlovic** [comment]
You can run docker with `-v` or `-mount` and specify a mount of your choice. As for the port, we could indeed expose by default the port that we usually use for routes (5222), although the default config does not specify any route. Note that you can always have a separate NATS cluster and have a Streaming server connect to that cluster (with the `-ns` command line option). For instance:
```
docker run -d --link nats-main nats-streaming -store file -dir datastore -ns nats://nats-main:4222
```
where nats-main would be a container running a NATS server.

**Comment by kozlovic** [comment]
Closing for now. Feel free to re-open with new details.
