### ISSUE TITLE
Persistence - clients.dat and server.dat

### ISSUE THREAD

**Issue by jeffrichiefs** [nats-io/nats-streaming-server#546]
Using file store for persistence - when does nats-streaming write to the server.dat and client.dat? I was tailing both and writing messages and nothing was being written to those files.

**Comment by kozlovic** [comment]
The file `server.dat` is storing some meta data information about the server (some subjects used between server and clients for communication). It is usually written only when a server starts for the first time (with empty datastore). The `clients.dat` file is updated any time a connection is created or closed.
