### ISSUE TITLE
publisher - consumer rate matching

### ISSUE THREAD

**Issue by nuhamind2** [nats-io/nats-streaming-server#554]
Hi, is there functionality to allow slowing down publisher if consumer is not fast enough in consuming message  (based on max unconsummed message probably) ? Or it is something that better layered on top of streaming-server ? Say, using nats server with request-reply pattern, subscriber can slow down publisher (or requester) by delaying/not sending reply.

Looking in the documentation, rate limiting/matching is available between publisher<-> streaming-server and streaming-server<->subscriber, but none between publisher<->subscriber.

**Comment by kozlovic** [comment]
You are correct. There is a client side property to block a publish (when doing async publish) if the number of outstanding pub ack reach that configured level, but the server will not apply back pressure based on the consumer rate.

Remember that NATS Streaming is not a queue-based message broker. That is, messages are appended to a message log, regardless of subscription interest. Even after a subscription consumes all messages, those messages are still in the log, avail for any other subscription. Only channel limits can cause old messages to be removed from the channel, not consumer acks.

As you pointed out, NATS request-reply is powerful and offers even end-to-end guarantee (as opposed to streaming - or most of other messaging products - where the publish's ack just let the publisher know that the message has been persisted, but offer no guarantee that the message will actually be processed by the application's code. Request-Reply can offer you that guarantee.

**Comment by nuhamind2** [comment]
Thanks for the response. Looking at the issue history, there seem to be some question similar to this.
#418 
#514

**Comment by nuhamind2** [comment]
#491
