### ISSUE TITLE
Confused about clustering vs fault tolerance

### ISSUE THREAD

**Issue by fedepaol** [nats-io/nats-streaming-server#555]
Hi everybody, we are slowly experimenting nats streaming in our solution, and we found some troubles in understanding the difference between having a distributed cluster (as described in [clustering](https://github.com/nats-io/nats-streaming-server#clustering)) and implementing fault tolerance (as described [here](https://github.com/nats-io/nats-streaming-server#fault-tolerance) )

If I understood correctly, fault tolerance need the active / standby instances to share the same storage (within the same node / using sql / using a shared disk), whereas the clustering implements data replication using raft.

Now, said that we do not want to loose our beloved messages, which one should we configure? And more: what are the advantages fault tolerance provide over clustering (if any) ?

Thanks a lot in advance, really loving nats and streaming so far!

**Comment by ripienaar** [comment]
For many the shared storage was a major hurdle and shared storage is just another point of failure.  However performance would always match 1 full instance and you would have failover.  For example there's no way in my install i can get a performant reliable NFS server so the only option is the raft option

Clustering (raft) has performance overhead but no shared resources, a write is ack'd when its written to all nodes in the cluster making it very robust from the perspective of your messages, however its a HA mechanism not a performance mechanism so you'll see some hit.  It's also fairly new.

I don't think there's a *right* one, you have to consider what you're comfortable with storage wise and what tradeoffs you can take.

**Comment by fedepaol** [comment]
Makes sense, thanks a lot. 
I guess I'd stick with the clustering trying to stress it out, since I may have the same problems about having a reliable shared "disk".

Thanks again

**Comment by caarlos0** [comment]
So, in cluster mode the filestore don't need to be shared between all nodes (e.g. no need to use NFS), correct?

**Comment by fedepaol** [comment]
> So, in cluster mode the filestore don't need to be shared between all nodes (e.g. no need to use NFS), correct?

Correct. The redundancy is handled by raft.

**Comment by caarlos0** [comment]
Cool, so, you just fired up, say, 3 instances, if one dies, the others continue to work, correct?

Are you using a load balancer in front of them?

**Comment by caarlos0** [comment]
What I want to do is actually to have a cluster of nats-streaming-server + nats, not sure if I can do this using the embedded nats...

**Comment by fedepaol** [comment]
That's what I understood, yes.

The balancing thing si a bit more complex since your client connects to a (regular) nats server and the node of the (regular) nats cluster is pick randomly.

Since partitioning is not supported by clustering I would say that each streaming server is receiving each message, but I am guessing the implementation and might be wrong here. Maybe it's better to wait someone more expert than me.

**Comment by caarlos0** [comment]
Cool, thanks for the answers @fedepaol!

Maybe @ripienaar has more info 🤔

**Comment by aricart** [comment]
The embedded NATS server is fully configurable. So the configuration of `cluster` is orthogonal of the streaming cluster configuration (which is set on the `streaming`), so you can use the embedded server for creating the NATS cluster that supports the NATS Streaming Cluster. 

There are some cases where it may makes more sense to run the NATS servers separate, and have the NATS Streaming Server join the NATS cluster instead. If you have non-streaming clients, I would probably have NATS streaming servers join a NATS cluster instead.

**Comment by caarlos0** [comment]
I have only nats-streaming-server clients... so I would prefer using the embedded one... will post here the results :)

thanks

**Comment by ripienaar** [comment]
Personally when I want clustering in NATS and NATS Streaming I split them apart and configure the 2 clusters seperately - the embedded server as @aricart says is configurable but the subtle differences in keys names and inconsistencies in config style just causes confusion.  So I split the tasks of building a reliable NATS cluster and a reliable Streaming cluster in 2.

ymmv :)

**Comment by kozlovic** [comment]
@caarlos0 To answer your original question, yes, in clustering mode you don't need shared storage. Each node will store the replicated data. The state should be persisted though, so that when a node restarts it can recover its state.
As for using separate NATS cluster or not, it is really up to you.

**Comment by caarlos0** [comment]
is it common to use a loadbalancer in front of it?

I'm trying locally with docker-compose and traefik, but I'm getting weird timeouts.

I created a repo showing that should be reproducible, maybe I'm doing something wrong... 

https://github.com/caarlos0/nats-streaming-server-cluster

the `main.go` is just a cli that subscribes and keeps adding new messages 

the compose folder starts 3 nats-streaming-server nodes and a traefik container

in the end, it should be listening on `localhost:4222`.

- `telnet localhost 4222` works
- `curl localhost:4222` returns a 500 and nats logs show `Client parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: localhost:"...'`
- the client just timeouts

thanks in advance for any info

**Comment by caarlos0** [comment]
I think maybe the problem is related to client not following redirects...

**Comment by kozlovic** [comment]
You can't curl on the client listen port (4222). Are you trying to get metrics? If so, you need to open the monitor port.

You don't specify what are the weird timeouts and which API is reporting them.

Try setup without load balancer in the picture first to make sure you understand how to setup the cluster and have clients connecting to it. If then you introduce load balancer and it fails, you will know where to look for.

Your client will connect to localhost:4222 since you don't specify a specific URL. If a telnet from the host where the client runs works, then the streaming client should be able to (as long as it is using the network).

**Comment by caarlos0** [comment]
hi, yes, it works without the LB... I was curling just to check what happens, because it usually returns something like 

```
INFO {"server_id":"Z6cduzXn632R0J0VsEW0iA","version":"1.4.1","proto":1,"git_commit":"3e64f0b","go":"go1.11.9","host":"0.0.0.0","port":4222,"max_payload":1048576,"client_id":13,"connect_urls":["172.19.0.4:4222","172.19.0.3:4222"]}
-ERR 'Unknown Protocol Operation'
```

anyway, the problem seems to be indeed in the load balancer part. What I did now to test is basically this: https://github.com/caarlos0/nats-streaming-server-cluster/blob/alt/main.go

and it works... so, pretty sure it's the LB, not sure if by design or if I'm doing something wrong.

**Comment by kozlovic** [comment]
Regarding this: https://github.com/caarlos0/nats-streaming-server-cluster/blob/alt/main.go#L30
there is an option called stan.NatsURL() where you pass the string, so you don't need to create an anonymous function to set this option. Also, we accept a list of urls, so you could pass "nats://host1:port,nats://host2:port,nats://host3:port" directly.

**Comment by caarlos0** [comment]
awesome @kozlovic, thanks! this helps a lot!
