### ISSUE TITLE
Include directive doesn't work

### ISSUE THREAD

**Issue by sega-yarkin** [nats-io/nats-streaming-server#559]
Hi! I'm trying to make an authorization and put a part of config to another file (like it is in NATS config examples), but NATS Streaming is throwing error `no such file or directory`.

I have `data` directory with these files:

1) `nats.conf`
```
port: 4222

authorization {
  include 'includes/users.conf'
}
```

2) `includes/users.conf`
```
STAN = {
  publish = ">"
  subscribe = ">"
}

STAN_PASSWORD = "STANPWD"

users = [
  {user: stan, password: $STAN_PASSWORD, permissions: $STAN}
]
```

When I start docker container with command:
`docker run -it --rm -v ${PWD}/data:/data --network=host nats-streaming:0.9.2 -c /data/nats.conf --user stan --pass STANPWD`
it throws error:
`Error parsing include file 'includes/users.conf', error opening config file: open includes/users.conf: no such file or directory.`

But if I make error in `includes/users.conf`, for example, comment out `STAN_PASSWORD` variable, there is another error:
`Error parsing include file 'includes/users.conf', Variable reference for 'STAN_PASSWORD' on line 10 can not be found..`
This means it actually can find and parse `includes/users.conf`.

If I put everything in one file there is no error. Also I tried to build latest commit (`0cdba20`), but no luck.

What am I doing wrong? Thanks!

**Comment by kozlovic** [comment]
I am still investigating. As a workaround, you can create a `nss.conf` that can be empty and pass those two config files with separate arguments:
```
nats-streaming -c /data/nats.conf -sc /data/nss.conf --user stan --pass STANPWD
```
When using only `-c` (or `-sc`), the server passes the config file to both NATS parsing code and to the streaming parsing code. That's when it seems there is a problem (when passing this config with includes to the streaming server parsing code). So separating nats and streaming config and passing them with `-c` and `-sc` seem to bypass the issue.

**Comment by sega-yarkin** [comment]
@kozlovic Thanks! Also works this one: `include '../data/includes/users.conf'` :-)

**Comment by kozlovic** [comment]
yes, indeed...

**Comment by kozlovic** [comment]
@sega-yarkin Ok, I think I got it. Just pushed a PR. If you want to have a go... but I did check myself and works now with Docker.

**Comment by sega-yarkin** [comment]
Looks working in `be70ed6`, thanks!

But I have another problem. When I try to pass password through environment variable and it starts with digits NATS Streaming throws error `Variable reference for 'USER1_PASSWORD' on line 10 can not be found`. If I prepend it with a letter everything is good.

**Comment by kozlovic** [comment]
That's common to our parser (both NATS Streaming and NATS). If you want to be treated as a string, but it starts with something that makes it look like a number, use quotes`"`. Let me know if that works.

**Comment by sega-yarkin** [comment]
@kozlovic But why does it say `can not be found`? Is it possible to fail back to string if the number has wrong suffix (not `k`, `kb`, etc.)? Quotes in environment variables look weird.

**Comment by kozlovic** [comment]
Not in the env variable itself, in the config file:
```
authorization {
   user: ivan
   password: "$user_password"
}
```
This works, even if `user_password` env is set to `1test`

**Comment by sega-yarkin** [comment]
Oh, thank you!

**Comment by sega-yarkin** [comment]
@kozlovic  Are you sure it should work?
I changed my `users.conf` above to:
```
STAN = {
  publish = ">"
  subscribe = ">"
}
users = [
  {user: stan, password: "$STAN_PASSWORD", permissions: $STAN}
]
```
and pass STAN_PASSWORD via env vars, NATS Streaming cannot start:
```
[1] 2018/05/21 18:19:56.585099 [TRC] STREAM:  NATS conn opts: { [nats://stan:randompasswordhere@127.0.0.1:4222] false _NSS-cluster-send false false false <nil> true -1 250ms 2s 0s 2m0s 2 0x918b30 0x918b80 0x918ae0 <nil> 0x918a70 -1 8192    <nil> <nil> false}
[1] 2018/05/21 18:19:56.585986 [DBG] 127.0.0.1:45904 - cid:1 - Client connection created
[1] 2018/05/21 18:19:56.587034 [ERR] 127.0.0.1:45904 - cid:1 - Authorization Error - User "stan"
[1] 2018/05/21 18:19:56.587251 [DBG] 127.0.0.1:45904 - cid:1 - Client connection closed
```

**Comment by kozlovic** [comment]
I see. It happens with NATS Server too (which is not surprising since we reuse the parsing code from that project). I will investigate. Thanks!

**Comment by kozlovic** [comment]
Unfortunately, the way our parser works (with env variables), I think that you would have to do this:
```
export stan_password=\"1test\"
```
The parser will lookup the env variable as `"1test"` but then apply interval parsing of `stan_password = "1test"`, which will correctly resolve as the password being `1test` (without the quotes).
