### ISSUE TITLE
Filtering of messages sent to subscribers based on ACL

### ISSUE THREAD

**Issue by aoboturov** [nats-io/nats-streaming-server#576]
Hi

I'm interested in having some kind of ACL linked to client credentials to have only topics from specified list delivered to each of them. This might be relevant if we would like to have just one instance of the streaming service and let different clients to connect to it. Subscribers should observe only subset of topics for which they have rights and not all of them. Would it fit into current architecture?

Best,
Artem

**Comment by aoboturov** [comment]
I guess it should be done somewhere in the 

```
// Ack our messages back to the publisher
for i := range pendingMsgs {
	iopm := pendingMsgs[i]
	s.ackPublisher(iopm)
	pendingMsgs[i] = nil
}
```

block in server.go

**Comment by aoboturov** [comment]
What should be changed then? Could the config be fetched from SQL?

**Comment by kozlovic** [comment]
We would need a new configuration entry that list what a user (or clientID) can subscribe to. That already exists for low level NATS, but that is not useable for NATS Streaming. What should then happen is that when the server receives a subscription request, it would check if the client ID (or other user information) is allowed to create a subscription on given channel. If not, an error should be returned.

**Comment by aoboturov** [comment]
How `*` and `>` would be handled in this approach? I guess that filtering
out messages would be more proper then...

**Comment by kozlovic** [comment]
Not sure what you mean here since NATS Streaming does not support wildcard subscriptions...

**Comment by aoboturov** [comment]
![image](https://user-images.githubusercontent.com/1026917/41247866-94ff592e-6daf-11e8-9e81-cc12461b6caf.png)

That's what I mean by wildcard subscription working with nats-streaming-server. A instance is running on the left, top right is the publisher. bottom right is the subscriber to the `isin.*` which received messages.

**Comment by aoboturov** [comment]
@kozlovic could you also check you work email?

**Comment by kozlovic** [comment]
Ah, but that's not the proper way of using Streaming. As discussed [here](https://github.com/nats-io/nats-streaming-server#relation-to-nats) (check last paragraph), NATS and NATS Streaming cannot communicate with each other. In NATS Streaming, you cannot create a subscription on wildcard subjects.

I did get your email and we will get back to you. Thanks!

**Comment by kozlovic** [comment]
Closing this for now.
