### ISSUE TITLE
Are there any good ways to support failover between nats streaming clusters?

### ISSUE THREAD

**Issue by YoninL** [nats-io/nats-streaming-server#577]
Hi,

I can setup a nats streaming cluster with 3 servers, now I have 2 clusters, how to sync data between them?

Let's say:

cluster A:
-node0
-node1
-node2

cluster B:
-node0
-node1
-node2

serviceA is connecting to clusterA, and serviceB is connecting to clusterB.
above serviceA and B there's a load balancer, which can support failover if A is down.

But because clusterB can't use the data directly on clusterA's nodes (error [FTL] STREAM: Failed to start: streaming state was recovered but cluster log path "test-cluster/noden" is empty), are there any good ways to support failover between clusters? Thanks.

**Comment by ripienaar** [comment]
why do you need these as separate clusters?

**Comment by YoninL** [comment]
we have two service clusters running at the same time, both need to be workable under a load balancer, if the two cluster connect to a same nats streaming cluster, some messages from producer in service cluster A will be received by a consumer in service cluster B.
So I tried to set separate nss cluster for them, but seems they can't share data store, for example, use the same mysql db.

**Comment by YoninL** [comment]
2 service clusters (one active and one standby) with 1 LB are for auto-failover. 2 nss clusters are for messages isolation. One workaround is only allow the active svc cluster to connect to nss cluster, and when switch to standby, switch the access as well.

**Comment by ripienaar** [comment]
Personally I think its best you use the HA, Failover and Replication Streaming provides on it's own and not try to invest your own with a LB

**Comment by YoninL** [comment]
OK, thanks a lot, I'll investigate more.
