### ISSUE TITLE
Docker host addresses in connect_urls

### ISSUE THREAD

**Issue by hryamzik** [nats-io/nats-streaming-server#587]
When nats is set up to listen on 0.0.0.0 it exposes docker host address (172.17.0.1) to `connect_urls`, result looks a bit wired:

```
"connect_urls":["192.168.99.108:4222","172.17.0.1:4222","192.168.97.138:4222","172.17.0.1:4222","192.168.100.42:4222"]
```

Configuration is trivial:

```
# NATS specific configuration
port: 4222
http: 0.0.0.0:8222
debug: true

cluster : {
  listen: 0.0.0.0:6222
```

Is there a way to filter `172.17.0.1` out without specifying particular IP to listen on?

**Comment by kozlovic** [comment]
You cannot filter some out, but you can ask NATS to not advertise the addresses at all:
```
cluster : {
  listen: 0.0.0.0:6222
  no_advertise: true
```
Or, you can advertise specific addresses for clients to connect to:
```
# NATS specific configuration
port: 4222
client_advertise: "<host or ip you want>:<port you want>"
```
Now obviously, these addresses/ports have to be able to reach the actual server's ip/port. Think of proxy in the middle.

Note that if you have a cluster of servers, if a server does not disable advertise, you may still have addresses in connect_urls even if your client connects to a server that has no_advertise set to true.
