### ISSUE TITLE
How do i migrate one instance to a cluster?

### ISSUE THREAD

**Issue by unisqu** [nats-io/nats-streaming-server#602]
How do i migrate one instance to a cluster?

**Comment by kozlovic** [comment]
There is not really a tool to migrate. What you can do is setup your cluster, then from your standalone server, ensure that there is no publisher running, start a durable subscription on each channel and publish back each message to the cluster.

**Comment by unisqu** [comment]
that's... a good suggestion.

**Comment by ripienaar** [comment]
I wrote a tool you might find useful for doing this over a period of time https://github.com/choria-io/stream-replicator
