### ISSUE TITLE
Current nats-streaming-server is using max 1 core (or cpu worker)

### ISSUE THREAD

**Issue by unisqu** [nats-io/nats-streaming-server#603]
advisable to use GOMAXPROCS setting? or can it be using all cores?

**Comment by kozlovic** [comment]
How did you observe that it is using a single core? Running some benchs on Macbook Pro and looking at Activity Monitor, I can clearly see that it is using more than one...

**Comment by unisqu** [comment]
Referring to this issue, I think I've never managed to push nats beyond 10% of CPU load because of slow ingestion rate and connecting subscriber.
https://github.com/nats-io/nats-streaming-server/issues/611
