### ISSUE TITLE
Code modification to stan-pub with problem to line 72

### ISSUE THREAD

**Issue by streetlist** [nats-io/nats-streaming-server#605]
I'm running a daemon and i modified the code below such that everything is published to nats-streaming-server. because i used nats streaming server like a persistent log, if i ran inside my program daemon, sometimes it will show errors on the "defer sc.close" line. 

i know it's supposed to close the sc connection but if i removed it, it runs perfectly without any error message. I suspect sc.close closed previous connection instead of current one etc because the log comes in processed too quickly.

my question is thus, since i've removed "defer sc.close" and it works "perfectly", is there any problem with this? i think starting or restarting my server daemon program should drop the open connection right? Else, how do I remedy / fix my problem?

https://github.com/nats-io/go-nats-streaming/blob/master/examples/stan-pub/main.go

**Comment by wallyqs** [comment]
What are the errors that you are getting on close? Just keep in mind that calling close before process exiting makes the client gracefully detach from NATS Streaming, it flushes any pending data that was inflight to be sent to NATS and signals the NATS Streaming Server/STAN to stop sending heartbeats to the client for example.
Also there would only be a single connection to NATS being in use by the NATS Streaming client so scenario of closing previous connection instead of current one would not happen.

**Comment by streetlist** [comment]
give me a few long hours for me to replicate this problem with a generated output. i've changed and modified a lot of code since the problem arised and need to redo this problem.

i realised also if i tried to use the async version, it seems to get "stuck" if i do a for loop over the async publish. i'm not sure if it's because of the multiple wait locks or because nats-streaming-server is doing GC or what. This bugs me too so I'm using the non async version with go coroutine
e.g. 
go Publish()
on the client side. (simulating a go function async i guess, which sort of works smoother)

**Comment by kozlovic** [comment]
Please provide code excerpt that shows exactly what you are doing and the error you are getting. Starting the server, creating a client connection and deferring its closing is what we do all the times in tests. Here is an [example](https://github.com/nats-io/go-nats-streaming/blob/master/stan_test.go#L179).

**Comment by streetlist** [comment]
i skipped this one and did some other things with nats.io streaming which works for now. will reopen if i found out this problem again. thx
