### ISSUE TITLE
panic nil pointer on file store

### ISSUE THREAD

**Issue by wongak** [nats-io/nats-streaming-server#608]
Hi, we encountered a panic while running nats-streaming in clustered mode with 3 nodes. 2 are now failing.

```
[1] 2018/07/05 09:24:37.394899 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.10.2
[1] 2018/07/05 09:24:37.394940 [INF] STREAM: ServerID: 9B9N8KWFN2AxjijLqN0TYG
[1] 2018/07/05 09:24:37.394944 [INF] STREAM: Go version: go1.10.3
[1] 2018/07/05 09:24:37.402666 [INF] Starting nats-server version 1.1.0
[1] 2018/07/05 09:24:37.402714 [INF] Git commit [not set]
[1] 2018/07/05 09:24:37.417410 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2018/07/05 09:24:37.417506 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2018/07/05 09:24:37.417512 [INF] Server is ready
[1] 2018/07/05 09:24:37.417799 [INF] Listening for route connections on 0.0.0.0:6222
[1] 2018/07/05 09:24:37.418823 [INF] 10.247.73.118:6222 - rid:1 - Route connection created
[1] 2018/07/05 09:24:37.553514 [INF] STREAM: Recovering the state...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8247cb]

goroutine 64 [running]:
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).ensureLastMsgAndIndexMatch(0xc420084b60, 0xc420073310, 0x0, 0x0, 0x0, 0xb1bd00)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2407 +0xeb
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).recoverOneMsgFile(0xc420084b60, 0xc420073310, 0x1, 0x401, 0x0, 0xc42005dd40)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2260 +0x10bc
github.com/nats-io/nats-streaming-server/stores.(*FileStore).newFileMsgStore(0xc4200b0840, 0xc420022420, 0x16, 0xc420022586, 0x10, 0xc4201715c8, 0x1, 0x153e6ebc2626a4db, 0x153e6ebc2626a4db, 0x0)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:1992 +0x8cb
github.com/nats-io/nats-streaming-server/stores.(*FileStore).recoverOneChannel(0xc4200b0840, 0xc420022420, 0x16, 0xc420022586, 0x10, 0xc4201715c8, 0xc42000a120)
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:1392 +0xd0
created by github.com/nats-io/nats-streaming-server/stores.(*FileStore).Recover
	/go/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:1325 +0x754
```

**Comment by kozlovic** [comment]
Would you mind also sending your configuration file(s) please? Thanks!

**Comment by kozlovic** [comment]
I can't seem to reproduce or understand what this would happen. If this is a test environment and does not contain sensitive data, would you be willing to send me the content of your `-dir` directory for review? If so, please send them at `ivan@nats.io`. Thanks!

**Comment by wongak** [comment]
Hi, we ran the cluster inside Kubernetes on an NFS persistent volume.

The flags were

```
-cid test-cluster
-st FILE
--dir /data
--clustered
--cluster_log_path /data/raftstate
-SD
--cluster_raft_logging
-m "8222"
--cluster nats://0.0.0.0:6222
--routes nats://nats-streaming:6222
```

Unfortunately we lost the volume due to the recycler picking it up.

**Comment by kozlovic** [comment]
Humm... from above, I don't see how the cluster would form since there is no bootstrap or definition of node_id/peers. Also, note that in NATS Streaming Clustering, the data is replicated on each node, so the datastore *must not* be shared, which I am not sure is what you have here.

**Comment by wongak** [comment]
Trust me, the cluster was fully formed and functional for some weeks.
I intentionally left out the bootstrap flag to not create confusion, which was only set on one of the three nodes. 
Each node had its own persistent volume, backed by NFS.
Nonetheless, the nil pointer is still a valid bug no matter the circumstances.

**Comment by wongak** [comment]
Indeed, it seemed also quite odd to me. I observed two out of three nodes being affected by this. It might have something to do with the underlying NFS, which is a service by our provider.
I am sorry that I couldn't provide more information. Thank you for looking into this.

**Comment by kozlovic** [comment]
@wongak I have addressed the issue. Thanks for the report!
