### ISSUE TITLE
What's the fastest way to get the return acknowledgement from nats-streaming-server?

### ISSUE THREAD

**Issue by unisqu** [nats-io/nats-streaming-server#612]
I've done sc.PublishAsync() or sc.Publish()

Both are very slow to return a value / acknowledgement.

How can I speed it up? All I'm looking for is just the fastest way to get

           err = sc.Publish(subj, msgInput)

or

           nuid, err := sc.PublishAsync(subj, msgInput, ackHandler) 

why is the return statement so slow?

**Comment by ripienaar** [comment]
@unisqu Streaming is not middleware, it does a lot of hard work to ensure your messages are 100% persisted to storage and secure when it tells you they got published - perhaps even across a cluster.  This is inherently slower than a normal middleware but that's to be expected of this kind of tool.

Likewise reading is also involving a lot of database like things, ensuring it keeps track of what you've seen before (and ensuring that is 100% persisted to its storage each time etc)

I think a number of the issues you've opened here is probably better asked on Slack

**Comment by unisqu** [comment]
Ok. Thanks
