### ISSUE TITLE
Cockroachdb

### ISSUE THREAD

**Issue by gedw99** [nats-io/nats-streaming-server#614]
I am wanting to use cockroachdb instead of the default postresl.

Anyone know if it works ? Should in theory

My use case is to replicate the data using cockroachdb for DR reasons. Not for HA.
So that on the origin cluster failing I at least have all the data on the DR cluster ready to go as a warm cluster. If someone has another viewpoint of best practice BATS way to do this please holler ?

**Comment by kozlovic** [comment]
Someone was trying to use CockroachDB and found an issue, which I fixed, however, CockroachDB is (was?) not supporting `SELECT FOR UPDATE`, which would prevent NATS Streaming Server to use CockroachDB as a SQL store. See https://github.com/nats-io/nats-streaming-server/pull/569 for details.

**Comment by kozlovic** [comment]
If there was equivalent, or something that works for MySQL, Postgres and CockroachDB, then of course, it would be nice to say that NATS Streaming works with that DB too.

**Comment by gedw99** [comment]
@ok. will work on the referenced issue..

**Comment by gedw99** [comment]
@kozlovic

So the buggy code is here:
https://github.com/nats-io/nats-streaming-server/blob/master/stores/sqlstore.go#L96

I assue your aware there was an RFC to support "SELECT FOR UPDATE"  in cockroachdb. 
Its here: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171024_select_for_update.md

However, they found it was too much work to do. However they give 3 other ways to do it.
https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20171024_select_for_update.md#alternatives-to-for-update

AM guessing by the date of this RFC that their suggestions were considered by rejected ?

**Comment by kozlovic** [comment]
To be clear, we did not investigate alternatives at this time, or in the past, to support CockroachDB. I may look at alternatives at one point, but no idea when that will be.

**Comment by gedw99** [comment]
Hey @kozlovic tap tap :) 
just seeing if there was any movement on this.

**Comment by kozlovic** [comment]
No, there has not been any change (from our side) on that front.

**Comment by lessless** [comment]
I hope one day NATS will be also able to support CockroachDB for more robust setups 🙏

**Comment by kozlovic** [comment]
@lessless This is not going to happen since NATS Streaming has been deprecated for a while (https://github.com/nats-io/nats-streaming-server#warning--deprecation-notice-warning).

NATS Server/JetStream (https://github.com/nats-io/nats-server) is now the product where all efforts go into, but that being said, there is no plan at the moment to offer (any) Database as storage backend. But at least you could ask in that repo for the feature.

**Comment by lessless** [comment]
@kozlovic oh, I didn't notice the difference. thanks for pointing that out :) 
It seems that JetStreams are fully taking care of persistence which is the best.
