### ISSUE TITLE
Can I use go-nats connect streaming server cluster,running as a nats server cluster?

### ISSUE THREAD

**Issue by Aavon** [nats-io/nats-streaming-server#617]
we used to deploy a nats server cluster.

But recently,we found we have a need for some advance features supporting by streaming server.However,we do not want to change the code using [go-nats](https://github.com/nats-io/go-nats).

Can we keep the code as it is?I have tried some basic usages,it seems there is no error.

**Comment by wallyqs** [comment]
You might be using the embedded version of the NATS Server that is enabled when running NATS Streaming in standalone.  To use NATS Streaming features you need to require the client library for NATS Streaming for Go so that messages are persisted: https://github.com/nats-io/go-nats-streaming

**Comment by Aavon** [comment]
Get it.Thanks!
