### ISSUE TITLE
Monitoring durable groups

### ISSUE THREAD

**Issue by pvanderlinden** [nats-io/nats-streaming-server#631]
As we are trying to move away from our current system to nats-streaming, I was wondering if it is possible to get metrics on channels and (durable) subscriptions, I have looked at the metrics currently exported, but I couldn't find the information needed for that.

Our main usage for this is to monitor if consumers has fallen behind, and if so, if it is catching up (we set an alert on subscriptions having more then x messages still waiting for delivery, and we have a dashboard outputting for example how fast it is consuming messages vs messages getting published to the subscription).

Is there any way to do this at the moment?

**Comment by kozlovic** [comment]
Have you had a look at the Monitoring chapter in the REAMDE? More specifically, there is the `channelsz` endpoint that may be of interest for you: https://github.com/nats-io/nats-streaming-server#channelsz

You can select a specific channel and have the subscriptions for this channel. You can look at durable subscriptions and check their `last_sent` versus the `last_seq` of the channel to know how far behind they are.

Let me know if that helps.

**Comment by pvanderlinden** [comment]
I'm sorry, not sure how I missed that (as I looked at the readme), this is perfect, thanks!

**Comment by kozlovic** [comment]
Glad it can help!
