### ISSUE TITLE
Server as Windows Service

### ISSUE THREAD

**Issue by sharkyfm** [nats-io/nats-streaming-server#632]
This is a duplication of the topic https://groups.google.com/forum/#!topic/natsio/jfYEfJe6bQQ
If install NATS Streaming Server as Windows Service (sc.exe create nats_streaming_server binPath = E: \ Soft \ nats-streaming-server \ nats-streaming-server.exe), the service does not start. But it would be extremely useful to have such an option (NATS Server can be installed as a service), for example, automatic start after Windows restart. In addition, it would be useful to have logging server errors in the Windows event log.
Really large companies do not use NATS Streaming Server on Windows? Run the server through the automatic launch of the bat-file at the start of the system is not a reliable solution.

**Comment by kozlovic** [comment]
@sharkyfm Submitted a PR for ability to run NATS Streaming Server as a Windows Service.
