### ISSUE TITLE
Documentation not very clear on clustering

### ISSUE THREAD

**Issue by artyomturkin** [nats-io/nats-streaming-server#638]
I am a bit confused by documentation regarding cluster implementation.

1. Do I need to setup partitions manually to take advantage of multiple servers or will cluster manager do it automatically?
2. If the partitioning happens automatically, can I specify replication factor to keep data on limited nodes only?

As of right now I am evaluating NATS to deploy in our environment, but I am afraid of a performance bottle neck if only one server will handle the traffik and all data is stored on all servers.

If that is the case should I just run multiple clusters on the same nats network using docker? From what i have seen resource overhead won't be a problem with nats streaming.

PS: Documentation in Partitioning section might be out of date, as it speaks of full clustering support not being implemented yet.

**Comment by kozlovic** [comment]
@artyomturkin I have updated the REAMDE (check PR #639). Partitioning and Clustering are not compatible. In Clustering mode, there is only one leader and all channels need to be replicated. You can, however, run multiple clusters on the same network as long as they don't have the same cluster ID. You will not be able to prevent creation of channels though (you can still have a list of channels for their individual limits, but not for partitioning purposes).

**Comment by artyomturkin** [comment]
@kozlovic Thank you! That answers my questions.
