### ISSUE TITLE
Using Oracle DB as store

### ISSUE THREAD

**Issue by jvrelits** [nats-io/nats-streaming-server#643]
Is it possible to use Oracle DB as store? We are currently doing a POT on NATS Streaming and Oracle DB is company database but it does not seem to be supported.

**Comment by ripienaar** [comment]
it's not support as far as i know

**Comment by kozlovic** [comment]
You would have to include a driver for Oracle and check if the provided SQL statements work. They may need updating. We can't support this at this time though. Also, I believe that available drivers require cgo, which we can't use when building the Docker image.
