### ISSUE TITLE
How can I read a the contents of .dat and .idx files? 

### ISSUE THREAD

**Issue by wjzhangcsu** [nats-io/nats-streaming-server#644]
I am check if the msg is sent correctly. I find `msgs.1.dat` and `msgs.1.idx `. Any ideas how I can extract the info to csv/excel,or other common files?

**Comment by kozlovic** [comment]
Simply create a subscription with option `DeliverAllAvailable()` and in the message callback write them to a file of your chosen format. 

Not sure what client you are normally using, but say if it was Go, you could start with our `stan-sub.go` example and go from there: https://github.com/nats-io/go-nats-streaming/blob/master/examples/stan-sub/main.go

You would pass the `-all` option to instruct the server to send all available messages.

**Comment by kozlovic** [comment]
Closing for now. Let me know if this did not answer your question.
