### ISSUE TITLE
Max number of retries for manual ack channel

### ISSUE THREAD

**Issue by cloudever** [nats-io/nats-streaming-server#645]
Hi!

Is it possible to set TTL or max number of retries for manual ack channel message?
Currently I'm checking that using redis cache, I feel it's a not good idea to make that way.

I'm using Node.js client.

**Comment by kozlovic** [comment]
What is your concern? That the server should stop redelivering a message or you want the application to be able to ask the server to stop? If the later, simply ack the message. For the former, no, there is no way to limit the number of redelivery attempts. There is a max age limit on a channel, but that's different. This is just to say that messages older than this limit are removed from the channel.

**Comment by cloudever** [comment]
Thanks, became clear.
