### ISSUE TITLE
Question: Reconnecting clients on first Connect failure

### ISSUE THREAD

**Issue by skyflyer** [nats-io/nats-streaming-server#650]
Just playing with NATS, but I'm wondering if I'm missing something or is it not supported by the `nats.Connect` call: if the server is not running, the client fails immediately with `No connection to server! nats: no servers available for connection`. If the server goes out after the client has been connected, than the Reconnects are "honored". I'm creating my client with this:

```go
		nc, err = nats.Connect(
			nats.DefaultURL,
			nats.PingInterval(2*time.Second),
			nats.ReconnectWait(5*time.Second),
			nats.Timeout(5*time.Second),
			nats.MaxReconnects(100),
			nats.ReconnectBufSize(102400),
			nats.ReconnectHandler(func(nc *nats.Conn) {
				fmt.Println("Reconnecting...")
			}))
```
and I've worked around it by simply wrapping it in a for/while loop for now.

Is this on the roadmap, or intentionally not supported?

**Comment by kozlovic** [comment]
The streaming servers and clients use NATS connections. The NATS Connection in Go does not allow a connect to happen in the background. As you saw, if an initial connect is not successful right away, an error is returned. (Note: the URL may be an array and all servers in the array will be tried first, but you get the point).

So unless NATS Go client (go-nats) implement this feature, the GO streaming client will behave this way. There is an issue to track this request: https://github.com/nats-io/go-nats/issues/195.

(For full transparency: some NATS clients have implemented "async" connect, and so streaming clients using those client libraries would benefit from that).

**Comment by skyflyer** [comment]
Thanks for the explanation and link to the relevant issue.
