### ISSUE TITLE
nats reconnecting issue

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [nats-io/nats-streaming-server#660]
I connect to my nats server like this, It has no problem with connecting at all,
```
nc, err := stan.Connect("test-cluster", "test-it")
if err != nil {
	panic(err)
}
```

But when I restart my nats server, It seems it cannot reconnect itself, nats logs, `connection closed`

Is there anything I should do for reconnecting it ? because I do not want some hacky way to reconnect it by myself

`stan.Pings(1, 500)` do you think adding this, is a good idea ?, could not find anywhere suggesting what to do

**Comment by kozlovic** [comment]
Are you using file or sql store? If not, state is only maintained in memory, so if the server is stopped and restarted, it does not know anything about the client that was left running. With newer Go client and server, the client will now report (if you setup the ConnectionLostHandler) this situation. Have a look at [this](https://github.com/nats-io/go-nats-streaming#connection-status).
