### ISSUE TITLE
Raft logging with SQL store-- race condition?

### ISSUE THREAD

**Issue by juandiegopalomino** [nats-io/nats-streaming-server#668]
Hi there,

So I'm trying to setup a nats streaming cluster (via kubernetes) w/ sql store as its backend. The trouble is that after the `-cluster_bootstrap` comes up, all the other instances fail saying
`[1] 2018/10/11 03:20:32.311584 [FTL] STREAM: Failed to start: streaming state was recovered but cluster log path [...] is empty`
Using volumes to mount the same log file for all the instances (thereby having them all share it), solved this problem, but I don't think that was the original intent, and I also saw problems where the monitoring port would only work for the instance with `-cluster_bootstrap` (if I got the endpoint from any of the other instances, it would report no channels or messages). I'm not sure what to do at the moment.

**Comment by juandiegopalomino** [comment]
OK, after doing some exploring, it looks like only the leader node has the real data of the state of the cluster. Going to `http://localhost:8222/streaming/channelsz` while port forwarding from it yields the expected state, while doing that from one of its siblings shows no data. This sounds alot like Standby servers as described in https://github.com/nats-io/nats-streaming-server#standby-servers, but I am puzzled as I did not set the fault tolerance flag. Is FT done automatically under some conditions?
Furthermore, if FT can not be avoided, is there some form of ensuring a kubernetes service to expose the management endpoints only directs traffic to the current leader?

**Comment by kozlovic** [comment]
Sorry for the delay. Two important things that may explain your issue:
- You need to make sure that the RAFT logs are persisted and will be recovered on container restart. See this [section](https://github.com/nats-io/nats-streaming-server#clustering-and-containers) in the README.
- If you are using SQL, you need to use a dedicated database per node. The point of using Clustering is that data is replicated on each node, so you can't share the database. Also note that even when using SQL store, there is a need for file storage (see [this](https://github.com/nats-io/nats-streaming-server#supported-stores))

If you intend to use SQL, you may want to look at Fault Tolerance instead: https://github.com/nats-io/nats-streaming-server#fault-tolerance

**Comment by juandiegopalomino** [comment]
@kozlovic yes, that makes sense, thank you. 2 final questions about your recommendation:
1. In FT mode, would the monitoring endpoint of each server (active and standby) return the correct, up-to-date data?
2. In FT mode, do we need a single db and/or raft log for the whole cluster?

**Comment by kozlovic** [comment]
In FT mode there is no raft and storage need to be shared. Only 1 server is active while the other are standby and don't have access to the storage (since it is used exclusively by the active server). So monitoring from standby servers would show "empty" values because they are not actively handling anything, just waiting for the active server to fail before trying to become active.

**Comment by juandiegopalomino** [comment]
@kozlovic ok, I believe I understand, thank you for the clarification. If we may, my team would like to make a feature request of having the monitoring endpoints of the standby servers redirect to the active server in order to get the valid data. We believe that this would be required for a kubernetes FT cluster deployment, as we'd need a k8 service for the monitoring endpoint and we don't know of a good way for a service to distinguish between the active and standby servers/pod. With the redirection in place, simply would not have that issue.

**Comment by kozlovic** [comment]
Created #671 for tracking purposes. Closing this issue now.
