### ISSUE TITLE
Resubscribing with new Start Position for Durable Queue Clients

### ISSUE THREAD

**Issue by johnyborek** [nats-io/nats-streaming-server#674]
I have a clustered consumer, all its nodes connect to a Channel as Durable Queue Subscribers. I'd like to re-subscribe with new Start Position (using startAtTime or startAsSequence options).

But it's very difficult to resubscribe with new Start Position, when we have Durable Queue Clients. It requires all the clients to unsubscribe first. So I need to implement some kind of "distributed unsubscribe":
* Broadcast notification to all Queue Subscribers, saying that they should unsubscribe
* Wait for all the client to unsubscribe
* Assure that subscription was removed from NATS Streaming Server
* Resubscribe with new Start Position
* Broadcast notification to all Queue Subscribers, saying that they can re-subscribe

It's pretty complex to implement, it might be hard to discover all the Queue Clients and assure that they get the notifications. It would be much better if NATS Streaming API would provide a way for deleting Durable Queue Subscription.

Is there another way to handle this scenario?

**Comment by kozlovic** [comment]
The point of a durable queue group is that adding members would start receiving messages from the current position in the channel, that is, the first not yet delivered message. Having member start at any position would create gaps and not make much sense.

But I understand the desire to unsubscribe as a whole so that the group can be recreated with a new position. However, the server does not have a way to communicate back to the clients that some of their subscriptions are no longer active. Meaning, your application that created queue members of the original group would then just sit there not receiving data but not aware that they will no longer do.

**Comment by johnyborek** [comment]
That's true, if there's no possibility to notify clients that their subscription is no longer active, then it's just not possible to implement "delete subscription" functionality.

I have some idea for implementing "distributed unsubscribe", but it's rather complex:
* Create a "technical channel" for sending notifications to queue members. All members will need to subscribe to this channel and handle the "commands" published there.
* Send "unsubscribe command" to this channel. Offline clients will not get this message, we'll handle them later.
* Wait for online queue members to unsubscribe. 
* Find out all the offline queue members, by calling /streaming/channelsz?subs=1.
* Create connections using offline client IDs, and perform unsubscribe on behalf of them.
* Subscribe with new starting point.
* Send "subscribe command" on the technical channel, so all the queue members can resubscribe.

Many things can go wrong on the way, so I'm not sure if it's worth to implement that. We'll try to find a way to go on without this functionality.

Thank you for very quick answer, you can close this issue :)

**Comment by johnyborek** [comment]
We actually have a simpler solution if someone is interested.
When we want to redeliver messages, we'll create a temporary client with new id, which is not a member of the queue. And this new client will:
- record the seqId of last delivered message for the queue (using NATS monitoring API)
- subscribe with desired Start Point
- handle the messages
- unsubscribe when all messages up to recorded seqId were handled

**Comment by kozlovic** [comment]
Also, you can always create a new group if needed. For queue group, the state is maintained per durable name + queue name. If you change any of those, you are basically creating a new group and it will start at the position you want.
