### ISSUE TITLE
Better documentation of client behaviour in nats-streaming-server cluster

### ISSUE THREAD

**Issue by selstam** [nats-io/nats-streaming-server#675]
Hi!

I tried to find information about this but couldn't find any, please point me in the right direction if I missed something.

I have a three node streaming cluster and a bunch of pub/subs. When connecting to the cluster they all have one URL pointing out one node in the cluster (the STAN client just provides a single URL, nothing more). If I connect and then close down the node that the client connected to it will still receive messages (through the other nodes, I'd assume). I will get the disconnected event from the underlying nats connection so if I use this to notify the client that the node (i.e. cluster) is gone, I'll be missing things.

If I restart my node it won't connect to the cluster since it'll try the url of the node no longer online (NATS.Client.NATSNoServersException: 'Unable to connect to a server.').  Is this as intended or is there another way of providing a way for a client to connect to the cluster?

**Comment by kozlovic** [comment]
When you create a streaming connection, you have the ability to pass a specific URL (as an option). This URL can be a list of URLs allowing you to reconnect to one of the other node should the one the client is connected to fails. But even if you provide a single URL, and assuming that this one is up and running when the client connects, then even if the node then fails, the client should be able to reconnect to any of the servers in the cluster (due to server auto-discovery and propagation to clients).

(I see that you seem to use the C# client, so look at `StanOptions.NatsURL`)

**Comment by selstam** [comment]
Although this code in ANTS.Client.Srv doesn't seem to accept multiple URL's:

```
    internal Srv(string urlString)
    {
      if (!urlString.ToLower().StartsWith("nats://"))
        urlString = "nats://" + urlString;
      this.url = new Uri(urlString);
    }
```

This will try to create a URI from "nats://localhost:4001,nats://localhost:4002" (which is the format I'd expect to put in my connectionurl) ... but that's not a well formed URI and it will throw a System.UriFormatException.

**Comment by kozlovic** [comment]
@ColinSullivan1 Can you have a look? It seems to be that you should be able to pass comma separated URLs since the low level NATS ConnectionFactory.CreateConnection() does call processUrlString() which knows how to deal with that.

**Comment by ColinSullivan1** [comment]
@kozlovic  - thanks, I'll take a look.  Yes, it should - a bug otherwise.

**Comment by ColinSullivan1** [comment]
@selstam , Multiple comma delimited urls are parsed correctly for me.  This code worked with the default streaming server settings...

```csharp
        var sopts = StanOptions.GetDefaultOptions();
        sopts.NatsURL = "nats://localhost:4222, nats://localhost:4322";
        var c = new StanConnectionFactory().CreateConnection("test-cluster", "id", sopts);
        c.Close();
```

Is it throwing an exception for you?

**Comment by selstam** [comment]
I was messing with the underlying NATS-connection by setting the NATS Options URL to the same URL as the nats streaming server. By splitting the configured urls and setting the Servers option instead it worked as it should.

So my bad! :)

**Comment by kozlovic** [comment]
Closing this for now.

**Comment by SidGrundfos** [comment]
Hello, When below - 
string url = "nats://wwncx1azwe-nats-cluster:4222";
        string subject   = "foo";
        string clientID  = "sidd";
        string clusterID = "wwncx1azwe-stan-cluster";

I am getting error in 
ar c = new StanConnectionFactory().CreateConnection(clusterID, clientID, cOpts)
STAN.Client.StanConnectionException: Invalid connection. ---> NATS.Client.NATSNoServersException: Unable to connect to a server.
Can you please help?
