### ISSUE TITLE
embedded nats streaming redelivers delivered messages - file store

### ISSUE THREAD

**Issue by viveksatasiya** [nats-io/nats-streaming-server#680]
Hello,

Steps to create an issue.

1. After delivering messages, acknowledge the messages
2. After sending acknowledgement, kill the process using Ctrl + c.
3. Start process again.
4. Embedded nats streaming module redeliver last message every time.

I am using file store for persistence.

Am I doing anything wrong?

**Comment by kozlovic** [comment]
Few questions:
- by embedded NATS Streaming, are you suggesting that you wrote an application that starts the Streaming server using its API? 
- how do you create and start the instance of the server?
- is the ctrl+c done after acks have been sent and processed by the server? 

It could be that you create an instance of the streaming server with bare file store options that do not call fsync. Also, you need to understand that if the process is stopped without the server having a chance to flush its write on disk (which would happen if you call s.Shutdown()), then there is indeed a risk that messages get redelivered because the acks for some messages are not recovered on restart.

**Comment by viveksatasiya** [comment]
Thanks for the quick response.

I have embedded NATS Streaming Server into my golang program by following [this article](https://github.com/nats-io/nats-streaming-server#embedding-nats-streaming).

Here is the code by which I start and stop the instance of the server.
```
import (
	natsd "github.com/nats-io/gnatsd/server"
        nats "github.com/nats-io/go-nats"
        stand "github.com/nats-io/nats-streaming-server/server"
        stores "github.com/nats-io/nats-streaming-server/stores"
        "github.com/nats-io/go-nats-streaming"
) 

func main() {
       // This configure the NATS Server using natsd package	
	nopts := &natsd.Options{}
	nopts.HTTPPort = 8222
	nopts.Port = 4223

	// Create the NATS Server
	ns := natsd.New(nopts)

	// Start it as a go routine
	go ns.Start()

	// Wait for it to be able to accept connections
	if !ns.ReadyForConnections(10 * time.Second) {
		panic("not able to start")
	}

	// Get NATS Streaming Server default options
	opts := stand.GetDefaultOptions()
	opts.StoreType = stores.TypeFile
	opts.FilestoreDir = "./natsStore"
	// Point to the NATS Server with host/port used above
	opts.NATSServerURL = "nats://localhost:4223"

	// Now we want to setup the monitoring port for NATS Streaming.
	// We still need NATS Options to do so, so create NATS Options
	// using the NewNATSOptions() from the streaming server package.
	snopts := stand.NewNATSOptions()
	snopts.HTTPPort = 8223

	// Now run the server with the streaming and streaming/nats options.
	s, err := stand.RunServerWithOpts(opts, snopts)

	nc, _ := nats.Connect("nats://localhost:4223")
	sc, err := stan.Connect("test-cluster", "client_id", stan.NatsConn(nc))
}
```

I press 'Ctrl + C' after Ack but still it redelivers after restart.

Actually, your suggestion to call shutdown() works. 
It seems that it might be a problem with fsync().

Is there anything which must be taken care If I embed NATS Streaming Server into golang binary? like closing connection of NATS server or NATS Streaming Server?

Right now, Calling shutdown() works for me.

Again, Thanks a lot for your quick response.

**Comment by kozlovic** [comment]
The server does not flush the subscriptions store for each ACK. When the server gets messages from the publisher(s), it stores them, then delivers to matching subscriptions (which translates to writing records to the subscriptions store) then flush both stores. However, processing of acks happen outside of this loop and therefore it is possible that some acks are buffered and not flushed on disk until some more messages are sent to subscriptions. On Shutdown() stores are flushed. We could add a timer per channel to flush subscriptions stores (I honestly believed that I was doing that).

But you do understand that there is no guarantee that when your application sends an ACK that the message is never going to be redelivered. Between the ACK being sent and the server processing and persisting it, the server could crash.

Of course, I understand the difference between a control shutdown of the server as opposed to a crash, but the point is that it is always possible that there is a redelivery. NATS Streaming offers at-least-once delivery, not exactly-once.

I will create an enhancement to see if we should add periodic flushing of the subscription stores. We can't do it for every ACK, performance will suffer too much.
