### ISSUE TITLE
[Question] A JavaScript or TypeScript client?

### ISSUE THREAD

**Issue by natiki** [nats-io/nats-streaming-server#685]
Hi,

Any plans for a JavaScript or TypeScript client?

**Comment by aricart** [comment]
@natiki what do you mean by typescript or javascript. Do you mean a client that works in the browser?

We currently have a javascript node client: https://github.com/nats-io/node-nats-streaming

For the browser, unfortunately, at this time we don't have a supported client. We are working on our web strategy. Stay tuned.

**Comment by natiki** [comment]
Hi @aricart,

> at this time we don't have a supported client. 

That was what I was after. Happy for you to close this one as it will be on a roadmap somewhere ;-). I will keep an eye out.

**Comment by aricart** [comment]
@natiki - it definitely is, just waiting on cycles for some server changes.
