### ISSUE TITLE
If there have some docs for nats-streaming?

### ISSUE THREAD

**Issue by xianghu1314** [nats-io/nats-streaming-server#694]
I want to write a client with websocket for nats-streaming.I tried my best to fond it but failed.
I hope there are some examples for us.Thank you.

**Comment by xianghu1314** [comment]
I want to write a client with websocket for nats-streaming.I tried my best to fond it but failed.
I hope there are some examples for us.Thank you.

**Comment by kozlovic** [comment]
You can't write a websocket client until the server can support it. NATS Streaming Server is actually a client to NAT Server (https://github.com/nats-io/nats-streaming-server#relation-to-nats), so until NATS Server provides this feature, you won't be able to have websocket streaming clients. Here is an issue on NATS Server that you can track if you want: https://github.com/nats-io/gnatsd/issues/315

**Comment by xianghu1314** [comment]
@kozlovic I know a few clients about nats-websocket. like [https://github.com/isobit/websocket-nats](url)
or [https://github.com/orus-io/nats-websocket-gw](url). but i dont fond it for nats-streaming.
iT try to write it by myself. but i dont understand the docment[https://nats.io/documentation/streaming/nats-streaming-protocol/](url).
Here is the docment of NATS's Client Protocol [https://nats.io/documentation/streaming/nats-streaming-intro/](url) .and it has many examples.

**Comment by xianghu1314** [comment]
first!Think you very much!@kozlovic what can i use the protobuf with websocket by NATS connection?This is where I am most puzzled.if you have some solution?

**Comment by xiaoDC** [comment]
@xianghu1314 did you have some solution? I want websocket can connect to nats-stream-server, too

**Comment by blinkinglight** [comment]
@xiaoDC nats and nats streaming example https://github.com/blinkinglight/go-nats.io-websocket
