### ISSUE TITLE
Use cluster w/ embedded nats server

### ISSUE THREAD

**Issue by juandiegopalomino** [nats-io/nats-streaming-server#696]
Hi guys,

Quick question: is there a way I can use embedded nats servers in my nats-streaming instances while on a cluster? I suppose I'd then need to find an alternative way of having them communicate with one another-- is that what the `--cluster` argument is for?

**Comment by kozlovic** [comment]
If you look at this [chapter](https://github.com/nats-io/nats-streaming-server#clustering-configuration), and scroll down a bit, there is an example of the configuration for a cluster of 3 servers each one embedding NATS Server, so they define cluster port indeed, along with routes.
Let me know if that helps.
