### ISSUE TITLE
Start time/sequence validation should be "inclusive" vs. "exact"

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats-streaming-server#7]
_From @mcqueary on March 15, 2016 19:14_

See [here](https://github.com/nats-io/stan/blob/master/server.go#L1061-L1070) and [here](https://github.com/nats-io/stan/blob/master/server.go#L1226-L1235) in `server.go`.

As a user, if my `SubscriptionRequest` specifies a time 100 seconds in the past, but the earliest stored message was 80 seconds in the past, I get `stan: invalid start time`. IMO that's broken, conceptually. 

Think of how you'd use a "since" date when qualifying Google search results (i.e. show me hits since this date). If I entered 1/1/2016, but the first result was from 1/3/2016, I'd expect to get everything starting from 1/3/2016, and not an error indicating that my "since" date was wrong. The same applies here: if my start time is before the earliest message, just start with the earliest message!

It's tempting to say "well, just use StartPosition.First instead", but I as a user actually require data since exactly (at most) 100 seconds ago, and I have no idea when "First" will start (3 days, 2 hours, or 5 seconds). 

I propose that if start time (or sequence) is earlier than the first message, that we start with the first message, and likewise that if the start time (or sequence) is later than the last message, we set the start time/sequence to 1ns or 1 seqno after the last message (i.e. default to `StartPosition.NewOnly`).

_Copied from original issue: nats-io/stan#24_

**Comment by mcqueary** [comment]
Evidence, regarding start time:
https://github.com/nats-io/java-nats-streaming/issues/22

**Comment by sfrooster** [comment]
+1 - we are/were going to open an issue similar to this against either csharp, or the server.

**Comment by bkim54** [comment]
+1  seeing this issue as well in csharp and node clients with an error from the server. "invalid startAt"

**Comment by sfrooster** [comment]
I really thing this should be marked as a bug since knowing the *exact* time of a message is nearly impossible unless you already have the message, in which case why do you need the message?

**Comment by kozlovic** [comment]
@sfrooster @bkim54 @mcqueary Check if proposed PR fits your needs. Basically, these calls will no longer fail and subscriber will receive first avail message is given sequence is smaller or time is before first message's timestamp, or will behave as "new only". That is, the subscriber won't receive the last message, but only new messages if given sequence is higher than last sequence or time is in the future relative to last message's timestamp.

**Comment by bkim54** [comment]
@kozlovic works for us! thanks for the fix!
