### ISSUE TITLE
Timed Delayed Messages

### ISSUE THREAD

**Issue by unisqu** [nats-io/nats-streaming-server#702]
Would like to "slot in" / influence the time for the message queue before, after or within the queue list.

other than timed delayed messages, can force insert time based msg because the backend processing was slow but the msg info is supposingly queued as so.

Related to this: any solutions / third party plugins yet? Coz that was 2017.
https://github.com/nats-io/nats-streaming-server/issues/324

**Comment by firrae** [comment]
This seems to be still an outlying feature request. I haven't had time to look at trying to find a way to plug it into the greater nats platform, we just did it in a hacky way in our code on our side.

At this point, to my knowledge, the answer to your question is no. Most have worked around it or, presumably, moved to other tools that offer it.

**Comment by kozlovic** [comment]
Sorry for the delay. There is no plan to implement this in the streaming server. I would be the opinion to close the issue #324 (and therefore this one too) so that people don't assume that this is going to be implemented. I am cc'in @ColinSullivan1 to have his feedback on that.

**Comment by ColinSullivan1** [comment]
While certainly a useful feature, in the context of messaging this doesn't fall into the NATS streaming system.  A feature like this would break the semantics of a log (essentially changing the order of messages).  #324 was about expiring messages, which makes sense in a queue, but not for a log.

I do think use cases these speak to the need of a queue, but that is an entirely different conversation.... 

Would you mind sharing your high level use case?   ...maybe there's another approach.

**Comment by kozlovic** [comment]
We have no plan to implement this feature at this time. Closing so that people don't assume it is in the works.
