### ISSUE TITLE
nats-streaming-server startup time and virtual memory usage

### ISSUE THREAD

**Issue by wrightleft** [nats-io/nats-streaming-server#706]
I'm using the nats-streaming-server in an embedded environment, and I've noticed that it allocates 897 MB of memory (VmData) immediately on startup, and consumes 100% of the available CPU for a few seconds.

I've tried to adjust my configuration file; limiting the number of connections, subscriptions, and how many messages can be saved, but this only seems to adjust the memory usage by a few MB one way or the other (895 MB to 907 MB). The nats-streaming-server doesn't actually use all that memory. It only uses around 40 MB (VmRSS).

I'm hoping there is some tweak I'm missing to reduce the memory allocation, and potentially the startup time as a result. Thoughts?

**Comment by kozlovic** [comment]
Are you using file store? Is there state being recovered when you start? As you say, the actual memory usage is 40MB, so rest could be due to system paging the files being recovered?

**Comment by wrightleft** [comment]
There is no file store. Here's the example configuration file I'm using:
```
host: localhost,
port: 4222,

max_connections: 5
max_payload: 64 

syslog: true,
syslog_name: "NATS Streaming Server",

streaming: {
   cluster_id: "testing",

   # We'll use memory as our store because we do not want the persistence that
   # a file or a database would supply.
   store: "memory",

   store_limits: {
      max_channels: 5,
      max_subs: 5,
      max_msgs: 5,
      max_bytes: 320,
      max_age: "1h"
   }
}
```
This configuration is ridiculously constrained (in my mind?), but the VmData for the nats-streaming-server is 895 MB. VmRSS is only 37 MB.

I bring this up for two reasons, startup is slow, and because the device only has 512 MB of RAM, and I worry that if left on for a long time, nats-streaming-server may decide to actually use all of the VmData it allocated, which would render my device unusable.

I've been researching Golang and the concept of arena allocators, but I can't explain 895 MB. I've tried messing around with the GOGC environment variable, but that only made it wiggle a bit, so I assume that nats-streaming-server is actually allocating that memory, in preparation for using it in the future, which scares me.

**Comment by wrightleft** [comment]
This actually seems to be a problem with gccgo. A simple hello world executable uses over 800 MB. Sorry for the noise.

**Comment by kozlovic** [comment]
No worries.. and good to know that this is not specific to NATS Streaming Server. I do believe that the process is not using that much memory but simply that it is available to it.

**Comment by wrightleft** [comment]
Yeah, from what I know about virtual memory, a large VmData shouldn't be causing problems, but the kernel starts to complain about not being able to kalloc (get memory) when a go executable (with 800-900 MB of VmData) is running. So our first step of debugging is to figure out why go executables are allocating so much.
