### ISSUE TITLE
Can 'user' and 'password' used by streaming server be specified in the configuration file?

### ISSUE THREAD

**Issue by guce** [nats-io/nats-streaming-server#707]
[Authorization](https://github.com/nats-io/nats-streaming-server#authorization)
`nats-streaming-server -config server.cfg -user alice -pass foo`

Can I write the above 'alice' and 'foo' in the configuration file?

`nats-streaming-server --config server.cfg -stan_config streaming-server.cfg`

**Comment by kozlovic** [comment]
We never get to do this (see #399). If you are not embedding the NATS Server but connect remotely, then you could specify it in the `nats_server_url` such as `nats_server_url: "nats://alice:foo@<host>:<port>"`.

**Comment by guce** [comment]
thank you for your response.
