### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by kethan** [nats-io/nats-streaming-server#716]
From streaming server i am getting this error in plain aws server

 [1] 2018/12/28 17:01:12.894583 [ERR] 49.207.183.211:46008 - cid:5 - Client parser ERROR, state=0, i=0: proto='"quit\r"...'

In client I am getting this error

NatsError: Could not connect to server: Error: read ECONNRESET

Any help will be useful. Thank you.

**Comment by kozlovic** [comment]
What client are you using? If you look at the parsing error in the server log, it looks like the "client" is trying to send `quit`, which is not a valid verb, unless this was supposed to be content of a message payload, in which case we would still need a way to reproduce.

**Comment by kethan** [comment]
I am using Nats node streaming. I have Nats streaming server running on aws Ubuntu server and trying to connect that aws server ip from my local machine

**Comment by kethan** [comment]
If I use telnet ip 4222 I am getting this error

 2018/12/28 17:01:12.894583 [ERR] 49.207.183.211:46008 - cid:5 - Client parser ERROR, state=0, i=0: proto='"quit\r"...'

From nodejs this
NatsError: Could not connect to server: Error: read ECONNRESET

**Comment by kethan** [comment]
Thank you. I have resolved the issue it was in my firewall.
