### ISSUE TITLE
Message retention (store limits) and durable subscription

### ISSUE THREAD

**Issue by plaisted** [nats-io/nats-streaming-server#717]
Is there any way to take durable subscriptions into account when creating message retention store limits?

For some of our queues we'd like to use a topic as a traditional queue with no concern for replayability. For these queues we want to retain unack'd messages a long time but allow ack'd messages to be purged from the queue/store quickly. Is there a way to apply this sort of setup? Currently we set the max_age to something larger than we'd expect a durable subscription to take to process including failures etc but this results in much higher memory/storage requirements for busy topics than we really need.

**Comment by kozlovic** [comment]
Sorry for the delay. The answer is no: in streaming, there is no way to control removal of individual messages. As you have found out, the only way messages are removed is based on the channel limits and only older messages are removed, regardless of their acknowledgment status.

**Comment by kozlovic** [comment]
Yes they can, hence: `regardless of their acknowledgment status.` in the last sentence.
If a message that is supposed to be redelivered is no longer found, then its redelivery will obviously stop. Here are few places where this occurs in the code:
https://github.com/nats-io/nats-streaming-server/blob/79944fa0744c3e3d9a2dfe8c9c0f316f96fc1abd/server/server.go#L3336
https://github.com/nats-io/nats-streaming-server/blob/79944fa0744c3e3d9a2dfe8c9c0f316f96fc1abd/server/server.go#L3172

**Comment by plaisted** [comment]
thanks, reading comprehension not my strength today.

**Comment by kozlovic** [comment]
No worries.. and you should not have to read the code to have this info anyway ;-)
