### ISSUE TITLE
manual ack of messages in queue

### ISSUE THREAD

**Issue by vtolstov** [nats-io/nats-streaming-server#722]
i have some question about acking of messages, for example i have 3 services
account, contact and billing
when i'm create account i'm fire event to nats about it. contact and billing services subscribed to topic account.
If contact service ack message, does it mean that message for billing acked too, or this is two separate messages and ack one of them not mean ack of another?

**Comment by kozlovic** [comment]
Not really clear on what "contact" and "billing" are in respect to NATS Streaming. Are you suggesting that these are just consumers on the same "account" channel?
Each consumer ack its own messages. Messages are not removed from the message log when they are ack'ed (instead, server removes old messages when channel limits are reached). An ACK sent to the server simply means that the server will not attempt to redeliver this message.
Have a look at this whole ["chapter"](https://github.com/nats-io/nats-streaming-server#channels).
Also, you can look at the client library's README for more information (not sure which language you would be using, but here is the Go one: https://github.com/nats-io/go-nats-streaming#subscription-start-ie-replay-options - this also covers durables and queues)

**Comment by vtolstov** [comment]
thanks
