### ISSUE TITLE
Durability: Messages never get delivered if sender gets disconnected

### ISSUE THREAD

**Issue by vasicvuk** [nats-io/nats-streaming-server#726]
If there is a sender that sends 100 messages and it disconnects after that when subscriber (durable) tries to consume messages it does not get this 100 messages at all.

On the other hand if the sender remains active while the consumer subscribes, consumer will get all the messages.

Is there a way that we can make durable consumer gets the message anyway?

**Comment by vasicvuk** [comment]
After doing more checks. It seems that the messages are delivered but after some time. Is this time configurable? Still in queue groups all messages are delivered to only subscriber (There is no round-robin). I opened new issue for that.

**Comment by kozlovic** [comment]
Please provide a test case that reproduces this issue. As for the "delivered to only subscriber" I explained why this is the expected behavior. Thanks!

**Comment by vasicvuk** [comment]
Messages are getting delivered but after some time. I don't know if that is an issue or by design?

I looked at your answer for "deliver to only one subscriber" but settings MaxInflight to 1 didn't help. Is there a way to make round robin works for durable messages?

Also i noticed that when settings MaxInflight to 1 and after receiving durable messages, messages published after that are also delivered to only one consumer.

**Comment by kozlovic** [comment]
Please, keep the discussion here related to the producer issue. I am answering to you about the round-robin delivery on the other issue.
Provide a test case that reproduces the issue listed in the subject (Durability: Messages never get delivered if sender gets disconnected).

**Comment by vasicvuk** [comment]
I will close this issue since they are delivered but after some time. You can use the example from other issue too see that sometimes durable messages are sent to consumer 10 seconds after it is connected sometimes, but they are always delivered which is fine by me.
