### ISSUE TITLE
queue with single leader

### ISSUE THREAD

**Issue by vtolstov** [nats-io/nats-streaming-server#727]
I need to have only one worker that dequeue nats durable queue, and other workers simply wait when first is died. So something like leader. Does it possible to use nats streaming for this case?
(i have tasks that puts on queue, and only one leader need to dequeue it and run execution).

**Comment by kozlovic** [comment]
This is not possible directly with NATS Streaming. There was a similar issue filed last month: https://github.com/nats-io/nats-streaming-server/issues/710
See if what is described there can help.

**Comment by vtolstov** [comment]
thanks
