### ISSUE TITLE
Publish message

### ISSUE THREAD

**Issue by deji04** [nats-io/nats-streaming-server#730]
Hi,

Question: Can I publish "sample.data" in nats-streaming-server and download it as I subscribe?

Thank you!

**Comment by kozlovic** [comment]
Yes you can. Since I think you opened an issue yesterday in the cnats repo, here are some basic usage of the NATS Streaming C API: https://github.com/nats-io/cnats#nats-streaming-client
You may also want to have a look at the basic examples to send/receive messages: https://github.com/nats-io/cnats/tree/master/examples/stan

**Comment by deji04** [comment]
Hi @kozlovic 

Thank you for your fast response. I appreciate it and enjoyed testing cnats.

However, when I am compiling the .c under /examples/stan, I am getting plenty of errors. I am thinking that this may be because of wrong linkers. Should I use the same linkers I've used for /examples/getstarted or the test.c under /test?
And I just want to confirm if protobuf-c is the one used for the streaming APIs or I can use Google's Protocol Buffer? This is based from my understanding on what I've read in protobuf-c.h that protobuf-c is used instead of Google's Protobuf.

Sorry for too many questions. I am in a tight schedule for testing this.

Thank you!!

**Comment by deji04** [comment]
Hi @kozlovic 

Thank you for the quick responses for my questions. (I enjoyed testing the examples/getstarted folder)

However, when compiling examples/stan folder, it successfully produced .o files but when I try to run the command:
![image](https://user-images.githubusercontent.com/43259911/51590417-c7083b80-1f24-11e9-946d-a68a55ecd094.png)
It produces these. Can you please point out to me what I am missing during compilation or debugging?

Sorry to bother you again.

**Comment by kozlovic** [comment]
You need to use cmake to build the project, and yes, the C Streaming library will use the protobuf library that is included in the cnats tree. Follow instructions [here](https://github.com/nats-io/cnats#building)
(also, would be best to open this issue in cnats repo directly. I cannot spend too much time on this at the moment, but for build issues, there is a reason I have decided to use cmake, is to be cross platform and not have to deal with all the make issues directly).
