### ISSUE TITLE
Nats streaming memory usage

### ISSUE THREAD

**Issue by ivanperez-mb** [nats-io/nats-streaming-server#731]
I'm using nats-streaming in FT mode and with persistent messages with unlimited size and limit of messages by subject. This is possible because the number of messages that is published in my usage case is very low, something between 3 and 5MM messages with less than 1k per messages. Also I have a small number of consumers and publisher in this case.

But even with this, in my case the memory usage of nats streaming are just getting peck every day till the 100% percent of memory usage and then this pod get restarted and a new POD on FT mode assumes the control and this process memory consume starts again. 

In my understanding and I dont know if I right here in my observation here It seems that nats-streaming maintain all messages that I'm receiving also in memory and not only on disk, it is kind of cache to improve performance of delivering of this messages. 

So, is there any configuration that can I use unlimited size on my subject and I also can prevent this weird scenario of memory usage? 

<img width="386" alt="screen shot 2019-01-18 at 23 19 17" src="https://user-images.githubusercontent.com/45392904/51420489-910c3580-1b79-11e9-870e-a375add1fd6e.png">

PS: this chart title is Nats % Memory, but there is only nats-streaming here and all stand-by nodes are showed in the base line.

**Comment by ivanperez-mb** [comment]
Thanks for the answer, maybe  this thread on slack it could give some information of how to tune my docker for that not to happen.

Bu I'm not in your slack channel. So, could give me access on this?

**Comment by kozlovic** [comment]
@ivanperez-mb Follow this link for the registration process: https://join.slack.com/t/natsio/shared_invite/enQtMzE2NDkxNDI2NTE1LTc5ZDEzYTkwYWZkYWQ5YjY1MzBjMWZmYzA5OGQxMzlkMGQzMjYxNGM3MWYxMjNiYmNjNzIwMTVjMWE2ZDgxZGM

**Comment by ivanperez-mb** [comment]
@kozlovic thanks!

**Comment by jbibro** [comment]
Hi, did you manage to solve your problem @ivanperez-mb ? I checked slack link but it looks like it disappeared because of 10k message limit. Thanks!

**Comment by AaronFriel** [comment]
@jbibro @kozlovic I'm seeing the same rate of memory growth with many, many fewer messages sent - on the order of 10-50k messages/day. I haven't yet stood up a Prometheus/Grafana instance to monitor the working set bytes, so I can't say what the source of the memory usage is.

Is NATS Streaming Server mmaping in the file slices and not releasing them?

![image](https://user-images.githubusercontent.com/788800/64043646-d0d8c980-cb19-11e9-87cc-96c4ca0642da.png)

**Comment by kozlovic** [comment]
@AaronFriel No, Streaming is not mmaping its own file stores, but the RAFT backend store (using etcd.io/bbolt) is. Check the size of the raft log to see if you can correlate to the above graph.

**Comment by AaronFriel** [comment]
@kozlovic Why would the raft log grow to such enormous sizes with a low throughput?

**Comment by kozlovic** [comment]
I did not say that it was RAFT log. Did you check? Assuming that you did and that the raft log is indeed being several GB big, and assuming that your messages are not big:
the RAFT log won't shrink but when there is a snapshot, the log entries can be removed and space be reused. Remember that messages go in the log, but also any action such as connection create/close, subscription create/close, message assigned to a sub, message ack'ed, etc..
Any specific raft params that you may have set that prevent snapshots from happening? Any error reported?

**Comment by AaronFriel** [comment]
The total size of the data folder (raft log + messages) is less than 2GiB, the raft log is about 100MiB.

It looks like Kubernetes is attributing most of this to "evictable" memory usage. This looks much more reasonable, and it looks like the gradual increases are between compactions - which makes sense.

**Comment by kozlovic** [comment]
So to be clear, NATS Streaming is not holding as much memory. So far, this was always the case that the actual memory usage was not high but docker or now k8s is reporting it as being attributed to NATS streaming. Do you agree or are you saying that the server is consuming that much memory?

**Comment by AaronFriel** [comment]
I agree, it looks like it's evictable page cache memory being attributed to the files open by NATS Streaming, not likely a memory leak.
