### ISSUE TITLE
panic: Unable to flush sub store: pq: duplicate key value violates unique constraint "pk_msgpendingkey"

### ISSUE THREAD

**Issue by LafonteFull** [nats-io/nats-streaming-server#741]
Got this error yesterday and today, and it's fixed after deleting the table contents by myself.

```
panic: Unable to flush sub store: pq: duplicate key value violates unique constraint "pk_msgpendingkey"
goroutine 22 [running]:
github.com/nats-io/nats-streaming-server/server.(*StanServer).ioLoop(0xc0001e6000, 0xc000146630)
    /home/admin/nats/src/github.com/nats-io/nats-streaming-server/server/server.go:3782 +0xb4d
created by github.com/nats-io/nats-streaming-server/server.(*StanServer).startIOLoop
    /home/admin/nats/src/github.com/nats-io/nats-streaming-server/server/server.go:3611 +0xcc
```

Version :
version | 1.3.0
proto | 1
go | go1.11.4
Postgres : 10 on AWS RDS

**Comment by kozlovic** [comment]
You did not actually print the NATS Streaming version. Could you please let me know which one is it?

**Comment by kozlovic** [comment]
Also, you would not point 2 (or more) NATS Streaming server to the same database by any chance?

**Comment by kozlovic** [comment]
Any news on that? Closing for now, will re-open if you provide some updates.

**Comment by TipDev** [comment]
I also have the same problem.

`Unable to flush sub store: pq: duplicate key value violates unique constraint" pk_msgpendingkey "`

nats-streaming-server version 0.11.2, nats-server version 1.3.0
postgres 10.7

I configure a fail-tolerance cluster (2 nats-streaming servers) that run from one database(postgres sql-store).
I assume on that when the current leader becomes unavailable, stand by will capture the storlock in postgres and be promoted to leader.

**Comment by TipDev** [comment]
@kozlovic, please re-open this issue

**Comment by kozlovic** [comment]
@LafonteFull @TipDev Sorry for the delay in getting back to you. I finally figure out what the problem was. I have pushed a PR if you want to try it out PR #828

**Comment by TipDev** [comment]
@kozlovic  Sorry for the delay. This is grate news! Thank you!
