### ISSUE TITLE
NATS Streaming reconnect logs expose password

### ISSUE THREAD

**Issue by Will2817** [nats-io/nats-streaming-server#746]
NATS Streaming version: 0.11.2
NATS Streaming was configured using the `-ns`, `--user` and `--pass` flags.

In my current setup I have a NATS Streaming cluster pointed to an external NATS cluster. While rolling the NATS cluster I noticed these reconnect logs in NATS Streaming, at the INFO level, expose the password used to authenticate NATS Streaming to NATS.

![image](https://user-images.githubusercontent.com/1437540/52888030-128abf80-3148-11e9-8b80-66edd03a7c8b.png)

**Comment by kozlovic** [comment]
@Will2817 Thanks! We will definitively have to address that. It looks like we build the URL based on the provided user name and password, so when we print the connected URL on reconnect event, this gets exposed. We also print the connection options on startup when running with `-SDV`..

**Comment by Will2817** [comment]
Thanks @kozlovic for the fix!
