### ISSUE TITLE
How to get all messages from partitioned stream in sequential order?

### ISSUE THREAD

**Issue by belevtsev** [nats-io/nats-streaming-server#751]

**Comment by aricart** [comment]
The streaming server's `partitioning` option is not related to the layout of the data. But rather means that a specific server is responsible for all data for that channel. Starting a subscription on the channel will always deliver messages in sequential order provided you don't have too many messages in flight (see `MaxInFlight` in [https://nats.io/documentation/streaming/nats-streaming-intro/](https://nats.io/documentation/streaming/nats-streaming-intro/)

**Comment by aricart** [comment]
Also note that if you create a queue subscription (see [https://nats.io/documentation/streaming/nats-streaming-intro/](https://nats.io/documentation/streaming/nats-streaming-intro/)) the streaming server will distribute messages between clients (not all clients will see all messages).

**Comment by belevtsev** [comment]
@aricart Thanks for your response!
I'am trying to use nats-streaming-server for event sourcing.
Each channel is so called aggregate ID. I have service that responsible for orders.

channel partition looks like:
```
{
  partitioning: true,
  store_limits: {
    channels: {
      "order.>": {},
    }
  }
}
```

Service produce events like: `order.created`, `order.updated`, `order.deleted`
Everything is ok until I need to build service state from scratch. I cannot find how can I receive all persisted messages from `order.>` channel as a single ordered stream of events.

**Comment by aricart** [comment]
@belevtsev there's no ordering across channels.

The configuration you are specifying above is simply saying that this server (in an environment where multiple servers share the same `cluster-id` and nats cluster) will only record messages that match the subject filter `order.>`

In NATS (nats-streaming) a wildcard is simply a mechanism to avoid duplicating channel configuration (which you have defaulted with `{}`). Each message will save to a subject channel that matches the subject on which it was published (see the dir specified by -dir). Subscribers have to specify actual concrete subjects (no wildcards).

You could possibly recreate the ordering by creating multiple subscriptions to each channel with only a single message in flight and then examine the timestamp for each subscription's messages, visiting messages by order of the timestamp assigned by the server to the message.

For streaming applications where you want to process messages in order regardless of subject, you should publish on the same subject and then add structure to your streaming payload that indicates the condition you wanted to signal via different subject segments.

**Comment by belevtsev** [comment]
@aricart Thank you! Closing this issue.
