### ISSUE TITLE
docs: missing for raft timeout configuration

### ISSUE THREAD

**Issue by stuart-warren** [nats-io/nats-streaming-server#760]
There doesn't appear to be any documentation for the raft tweaking settings:
```
raft_heartbeat_timeout
raft_election_timeout
raft_lease_timeout
raft_commit_timeout
```
This was discovered through looking through the code https://github.com/nats-io/nats-streaming-server/blob/2b200fa8f1daa1f54edb507b4567315ad91c5d25/server/conf.go#L276-L299

Local testing seems to take about 8 seconds to re-elect a leader after losing them and during that time messages stop flowing.

**Comment by kozlovic** [comment]
Right. These were added after the fact, more as a backdoor. The default values were bumped since otherwise several users would have problems especially with containers, etc..
Did you tune them? What values did you set them to and does that work well for you?
