### ISSUE TITLE
Closed clients shown as still active

### ISSUE THREAD

**Issue by anjmao** [nats-io/nats-streaming-server#775]
### Env
Go:

- go1.12 darwin/amd64

Stan go client: 
- github.com/nats-io/go-nats v1.7.2
- github.com/nats-io/go-nats-streaming v0.4.2

Os:

- Streaming NATS with docker
- Go client for testing on macOS Mojave (10.14.3)

### Steps to reproduce
Initially there are no clients
http://localhost:8222/streaming/clientsz?subs=1
```json
{
  "cluster_id": "test-cluster",
  "server_id": "SYU1nY8rrZ8FOl59GLlQHk",
  "now": "2019-03-15T07:56:02.801106364Z",
  "offset": 0,
  "limit": 1024,
  "count": 0,
  "total": 0,
  "clients": []
}
```

Create client with subscription.
```go
package main

import (
	"flag"
	"fmt"
	"log"
	"os"

	stan "github.com/nats-io/go-nats-streaming"
)

var (
	natsURL       = flag.String("url", "nats://localhost:4222", "Nats connection URL")
	natsClusterID = flag.String("cluster", "test-cluster", "Nats cluster ID")
)

func main() {
	flag.Parse()

	conn, err := stan.Connect(*natsClusterID, "test-client", stan.NatsURL(*natsURL))
	if err != nil {
		log.Fatalf("cannot connect: %s", err)
	}
	defer conn.Close()

	sub, _ := conn.Subscribe("test-subject", func(m *stan.Msg) {
		fmt.Printf("msg: %s", m.Data)
	})
	defer sub.Close()

	fmt.Fscanln(os.Stdin)
}
```

New client is shown.
http://localhost:8222/streaming/clientsz?subs=1
```json
{
  "cluster_id": "test-cluster",
  "server_id": "SYU1nY8rrZ8FOl59GLlQHk",
  "now": "2019-03-15T07:57:31.364595982Z",
  "offset": 0,
  "limit": 1024,
  "count": 1,
  "total": 1,
  "clients": [
    {
      "id": "test-client",
      "hb_inbox": "_INBOX.8RybFKv3bp5s7CWB8H1VE1",
      "subscriptions": {
        "test-subject": [
          {
            "client_id": "test-client",
            "inbox": "_INBOX.8RybFKv3bp5s7CWB8H1VV3",
            "ack_inbox": "_INBOX.SYU1nY8rrZ8FOl59GLlQUZ",
            "is_durable": false,
            "is_offline": false,
            "max_inflight": 1024,
            "ack_wait": 30,
            "last_sent": 0,
            "pending_count": 0,
            "is_stalled": false
          }
        ]
      }
    }
  ]
}
```

Now if I kill the client (cmd +c) and check client stats I still see this client as active. Even if I wait for 15 seconds (DefaultPingInterval = 5, DefaultPingMaxOut = 3) I still see this active client. It looks that go defer close statement is not working and If I modify the code to handle shutdown gracefully I don't see active clients any more.

```go
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"

	stan "github.com/nats-io/go-nats-streaming"
)

var (
	natsURL       = flag.String("url", "nats://localhost:4222", "Nats connection URL")
	natsClusterID = flag.String("cluster", "test-cluster", "Nats cluster ID")
)

func main() {
	flag.Parse()

	conn, err := stan.Connect(*natsClusterID, "test-client", stan.NatsURL(*natsURL))
	if err != nil {
		log.Fatalf("cannot connect: %s", err)
	}

	sub, _ := conn.Subscribe("test-subject", func(m *stan.Msg) {
		fmt.Printf("msg: %s", m.Data)
	})

	var gracefulStop = make(chan os.Signal)
	signal.Notify(gracefulStop, syscall.SIGTERM)
	signal.Notify(gracefulStop, syscall.SIGINT)
	go func() {
		<-gracefulStop
		conn.Close()
		sub.Close()
		os.Exit(0)
	}()

	fmt.Fscanln(os.Stdin)
}
```

**Comment by kozlovic** [comment]
This is expected because of the way clients and server(s) interact. Please have a look at https://github.com/nats-io/nats-streaming-server#concepts and specifically https://github.com/nats-io/nats-streaming-server#client-connections.

The ping settings that you refer to have no bearing in that issue. The Streaming client does have streaming options for pings but again, in the case it does not help since the client is stopped, not the server. The Streaming server has default hearbeat values to detect the client health that are much higher. You can configure them though: check the `hb_interval`, `hb_timeout` and `hb_failcount` (or their equivalent on the command line `-hbi`, `-hbt`, `-hbf`) in the https://github.com/nats-io/nats-streaming-server#configuration-file table.
