### ISSUE TITLE
v0.11.2 Panic in file store removeFirstMsg

### ISSUE THREAD

**Issue by dkishere** [nats-io/nats-streaming-server#778]
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x84ddf4]

goroutine 33 [running]:
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).removeFirstMsg(0xc00001e4e0, 0x0, 0xa70000)
        E:/GoProjs/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2928 +0x64
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).enforceLimits(0xc00001e4e0, 0xf0001, 0xc000ce47e0, 0xc001fd6101)
        E:/GoProjs/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2870 +0x95
github.com/nats-io/nats-streaming-server/stores.(*FileMsgStore).Store(0xc00001e4e0, 0xc000ce47e0, 0x0, 0x0, 0x0)
        E:/GoProjs/src/github.com/nats-io/nats-streaming-server/stores/filestore.go:2713 +0xaf2
github.com/nats-io/nats-streaming-server/server.(*StanServer).ioLoop.func1(0xc000278000, 0x1, 0x400)
        E:/GoProjs/src/github.com/nats-io/nats-streaming-server/server/server.go:3674 +0x23d
github.com/nats-io/nats-streaming-server/server.(*StanServer).ioLoop(0xc0001e4000, 0xc00012e2c0)
        E:/GoProjs/src/github.com/nats-io/nats-streaming-server/server/server.go:3762 +0x3ba
created by github.com/nats-io/nats-streaming-server/server.(*StanServer).startIOLoop
        E:/GoProjs/src/github.com/nats-io/nats-streaming-server/server/server.go:3603 +0xcc`

we start with command:
`nohup ./nats-streaming-server --store FILE --dir /tmp/nats --user foo --pass bar -m 8222 &`
it's ok after reboot the server

**Comment by kozlovic** [comment]
@dkishere I have made a chance to avoid the panic, but that being said, the panic was due to the fact that the first message in the log that was meant to be removed can't because the server is unable to read the index for that message. Not sure what caused it in your env.
