### ISSUE TITLE
ack_wait of over 30 seconds

### ISSUE THREAD

**Issue by juandiegopalomino** [nats-io/nats-streaming-server#780]
Any reason why setting ack_wait to over 30 seconds might reset it to a lower value? Seeing some unexpected retries w/ the async (python 3) client for messages whose acknowledgments took between 30 seconds and a minute (the ack_wait we provided).

**Comment by kozlovic** [comment]
Not clear on what is the issue you are experiencing. Do you have some tracing that shows the issue? What is unexpected, sooner or later than expected? Are you using queue subs or plain subs? Durables or not? Are the subscriptions restarted?

**Comment by juandiegopalomino** [comment]
Hi Ivan! To answer your questions, we're running a subscriber on a durable queue (only one subscriber though, and it doesn't seem to have been restarted), and we got some bugs that makes our handler take code that makes the handler take a lot longer than what it used to (< 10 seconds). To accommodate for that (and get rid of all the retry messages that we where getting b/c we did not acknowledge in time), we bumped up the ack_wait to 60 seconds. For the most part, that solved our issue, but every now and then we'd get repeated messages, which took less than the 60 seconds max. It could be a bug on our side, but we just wanted to cover all the bases and ensure there wasn't a special case w/ nats streaming

**Comment by kozlovic** [comment]
If a message is acknowledged, and assuming that the server received that acknowledgement, it should stop being redelivered. Depending on the message rate, you could run the server with debug/trace and see if you can capture such unexpected redelivery.
It could also be an issue in your application and/or the client library. I am not familiar with the python client. Pinging @wallyqs to know if he is aware of such issue in the library.

**Comment by wallyqs** [comment]
thanks, will see if I can reproduce in the python3 library

**Comment by wallyqs** [comment]
Some updated conversation about this issue can be found here: https://github.com/nats-io/asyncio-nats-streaming/issues/5#issuecomment-479808625
Looks like what could have happened in this case is that the many redeliveries were being buffered by the client, so even though the server had already received the ack, the client library still causes the consumer to process the redelivered messages that were buffering.  @juandiegopalomino updated to a decreased value of `max_inflight` messages for a subscription and this seems to have mitigated the issue https://github.com/nats-io/asyncio-nats-streaming/issues/5#issuecomment-480348392

**Comment by juandiegopalomino** [comment]
thank you again!
