### ISSUE TITLE
Document --cluster_peers is comma separated

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats-streaming-server#784]
`./nats-streaming-server --help` yields

```
...
    --cluster_peers <string>             List of cluster peer node IDs to bootstrap cluster state.
...
```
However, it doesn't really say if `--cluster_peers` should be given multiple times or comma separated. I had a look in the code and it should comma-separated so I propose https://github.com/nats-io/nats-streaming-server/blob/2b200fa8f1daa1f54edb507b4567315ad91c5d25/server/conf.go#L607 is changed to "Comma-separated list...". Also, are there other flags that are comma separated and this should be documented for?

**Comment by kozlovic** [comment]
We can definitively add this to the `-help` output, and I am sorry that you had to look at the code. You should try first the README to see if you can find the info you are looking for. There are examples here that show how to specify the peers in the command line and also in the config file: https://github.com/nats-io/nats-streaming-server#clustering-configuration.

> Also, are there other flags that are comma separated and this should be documented for?

Not that I can think of. The one I have in mind is `routes`, but it appears to be documented as such:
```
--routes <string, ...>       Routes to solicit and connect
```
