### ISSUE TITLE
Client heartbeats get started before leadership acquisition completes

### ISSUE THREAD

**Issue by def1oyd** [nats-io/nats-streaming-server#791]
I am running a 3-node NATS Streaming v0.12.2 cluster, and I am testing it by creating chaos manually.
For example, I would create many clients (random UUID as client ID) and many durable subscriptions, then `kill -9` everything and restart.

At a point my servers were crashing because of OOM, and I found that at that time there were 18k+ clients and 470k+ subscriptions. However I did not have any client running at that moment.

I waited for a while and I thought the clients would be removed when the heartbeats fail, unfortunately it didn't, the heartbeat configurations I had was `hbi=5s`, `hbt=30s`, `hbf=2`.

I modified `server/server.go`, added more loggings in client heartbeat related parts, restart the nodes and observe.

I found that this line in `server/server.go`
https://github.com/nats-io/nats-streaming-server/blob/4489c46ab3c1380d2ac44fc4412abcfdd012d6bb/server/server.go#L2848
got called even the node was elected as the leader, thus the heartbeat timer got stopped and hence no heartbeat failure => no removal for stalling clients.

This `checkClientHealth()` is called in
https://github.com/nats-io/nats-streaming-server/blob/4489c46ab3c1380d2ac44fc4412abcfdd012d6bb/server/server.go#L1982
during leadership acquisition. `&s.raft.leader` will only become `1` at the end of the function, but `checkClientHealth()` is called before it, causing `s.isLeader()` inside `checkClientHealth()` to be `false`, and triggered `removeClientHB()`.

Should this
https://github.com/nats-io/nats-streaming-server/blob/4489c46ab3c1380d2ac44fc4412abcfdd012d6bb/server/server.go#L1982-L1984
become the following?
```go
		defer s.clients.setClientHB(cID, s.opts.ClientHBInterval, func() {
			s.checkClientHealth(cID)
		})
```

I've done the above modifications and got all the stalling clients and subscriptions removed, and I'm sharing my thoughts here 😄, appreciate if you have any feedback.

Cheers,
Floyd

**Comment by kozlovic** [comment]
@def1oyd Very good catch!!! I would like to add a test to demonstrate the issue and prevent from resurface in the future. I am not entirely sure of the defer (as if there are really lots of clients, would that become a problem to have that many defer calls?). Regardless, yes, the fix looks like it is to do that after the atomic is set.
