### ISSUE TITLE
Use `:` in configuration file sections or not?

### ISSUE THREAD

**Issue by JensRantil** [nats-io/nats-streaming-server#798]
I notice that the NATS Streaming README has sections like this:
```
cluster: {
   ...
}
```
while NATS example configuration (in README) like this:
```
cluster {
   ...
}
```
. Assuming that both projects are using the same parser, how about standardizing on one format?

Background: I'm currently debugging why a configuration setting isn't kicking in. Whether not using `:` is yet another tiny thing I need to think about because I don't know if I can use the NATS format or not.

**Comment by wallyqs** [comment]
both are ok to use, can use even JSON

**Comment by wallyqs** [comment]
also gnatsd in master has a -t flag that could help find unused values and basic config issues in case might help with debugging a bit

**Comment by kozlovic** [comment]
Yes, Streaming and core NATS use the same parser so both are allowed.

I am sorry that you are having difficulty. Maybe, to address your immediate concern, you could post here (or open a new issue) the actual setting that does not seem to be taking effect?

**Comment by JensRantil** [comment]
Fixed my issue. Thanks, though! That said, standardizing on single format would reduce complexity/confusion for newcomers.

**Comment by kozlovic** [comment]
Thanks for the feedback!
