### ISSUE TITLE
at 1,000,000 messages in a queue, new messages are dropped.

### ISSUE THREAD

**Issue by ssoroka** [nats-io/nats-streaming-server#799]
Scenario:
When a queue has 1 million messages in it, new messages are dropped.

Expectation:
The correct behavior here would be to apply back-pressure on the clients and reject incoming messages. This was hinted at in #418. Without this, you have no reliability in message delivery, and you'll need to drop the "At-Least-Once Delivery model, giving reliable message delivery" claim, as this is _at-most-once_ behavior.

**Comment by kozlovic** [comment]
@ssoroka and as stated in #418, this is something that cannot be done with Streaming:
```
Keep in mind that in streaming, a message is never removed because it has been "processed" by a consumer. Messages are appended, regardless of subscription interest.

If we were to reject the incoming messages because the channel is full, then effectively, the channel would never be able to accept any new message since messages are not removed from the channel due to subscriptions, but only when limits are reached.
```
You are thinking message queue (like JMS), not event stream with replay capabilities.
