### ISSUE TITLE
Durable queue messages stuck in dead clients

### ISSUE THREAD

**Issue by juandiegopalomino** [nats-io/nats-streaming-server#816]
Hi guys, so I'm getting this weird error when trying to fetch messages from durable queues. The code works by creating short lived subscriptions to a durable queue from a set of connections to fetch the messages one at a time. Sometimes, like in the following example, some messages get lost and we do not know how to recover them. Take for example the following channel data from http://localhost:8222/streaming/channelsz?subs=1
```
    {
      "name": "QUEUE.710c4778-721d-4784-bf82-8378bf4cbbe9.a50a32c5-2e17-41de-adcc-57e1a0382bcc",
      "msgs": 287,
      "bytes": 1171295,
      "first_seq": 1,
      "last_seq": 287,
      "subscriptions": [
        {
          "client_id": "QUEUE_SVC---d5d97e96-2714-43e3-88cf-45299df49b30",
          "inbox": "8f94ee36a08a7f6550c37f",
          "ack_inbox": "_INBOX.XEuTFhUvRxdedrMDFzZgNh",
          "queue_name": "durable:QUEUE.710c4778-721d-4784-bf82-8378bf4cbbe9.a50a32c5-2e17-41de-adcc-57e1a0382bcc",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1,
          "ack_wait": 5,
          "last_sent": 287,
          "pending_count": 46,
          "is_stalled": true
        },
        {
          "client_id": "QUEUE_SVC---d5d97e96-2714-43e3-88cf-45299df49b30",
          "inbox": "3c389327a527e4a98ab1e2",
          "ack_inbox": "_INBOX.XEuTFhUvRxdedrMDFzZgST",
          "queue_name": "durable:QUEUE.710c4778-721d-4784-bf82-8378bf4cbbe9.a50a32c5-2e17-41de-adcc-57e1a0382bcc",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1,
          "ack_wait": 5,
          "last_sent": 193,
          "pending_count": 1,
          "is_stalled": true
        },
        {
          "client_id": "QUEUE_SVC---06dadd49-8bef-4f68-842e-fd099aa12cea",
          "inbox": "6eb968eb491344f043a00e",
          "ack_inbox": "_INBOX.dEib7JD1iPZDxY8sjm9HlT",
          "queue_name": "durable:QUEUE.710c4778-721d-4784-bf82-8378bf4cbbe9.a50a32c5-2e17-41de-adcc-57e1a0382bcc",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1,
          "ack_wait": 5,
          "last_sent": 0,
          "pending_count": 0,
          "is_stalled": false
        },
        {
          "client_id": "QUEUE_SVC---dd90346d-7d4c-48f4-8e88-bb5868b83aa5",
          "inbox": "b77bc6465b6b16a66d7e3a",
          "ack_inbox": "_INBOX.dEib7JD1iPZDxY8sjm9Hmm",
          "queue_name": "durable:QUEUE.710c4778-721d-4784-bf82-8378bf4cbbe9.a50a32c5-2e17-41de-adcc-57e1a0382bcc",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1,
          "ack_wait": 5,
          "last_sent": 0,
          "pending_count": 0,
          "is_stalled": false
        },
        {
          "client_id": "QUEUE_SVC---06dadd49-8bef-4f68-842e-fd099aa12cea",
          "inbox": "3a3791a8e6b7e9d54de587",
          "ack_inbox": "_INBOX.dEib7JD1iPZDxY8sjm9Ho5",
          "queue_name": "durable:QUEUE.710c4778-721d-4784-bf82-8378bf4cbbe9.a50a32c5-2e17-41de-adcc-57e1a0382bcc",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1,
          "ack_wait": 5,
          "last_sent": 0,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    }
```
We expected to handle 287 messages, but only 240 where done so. The first 2 subscriptions there ostensibly went rogue and are holding the remaining 47 messages as pending (this is an hour or so into the incident).  The remaining subscriptions are from the other connections still attempting to rescue the 47 missing messages. This error coincides with a couple `nats.aio.errors.ErrTimeout: nats: Timeout` from some of the connections (we are using the python3/asyncio client)-- as these where the only reported errors in the system, and also are directly linked to failed subscriptions, I suspect that this caused the rogue subscriptions. What also adds to the mystery is 1) I thought that by specifying the max inflight of one, it couldn't possibly accumulate more than 1 message in the subscription and 2) as we're hours ahead of the 5 second timeout, wouldn't the messages be put back in the channel?

The final odd thing I noticed is that one day later (once all rescue attempts stopped and the system forgot about the channel and restarted everything due to new deployments), the rogue subscriptions consolidated into 1:
```
{
      "name": "QUEUE.710c4778-721d-4784-bf82-8378bf4cbbe9.a50a32c5-2e17-41de-adcc-57e1a0382bcc",
      "msgs": 287,
      "bytes": 1171295,
      "first_seq": 1,
      "last_seq": 287,
      "subscriptions": [
        {
          "client_id": "QUEUE_SVC---d5d97e96-2714-43e3-88cf-45299df49b30",
          "inbox": "3c389327a527e4a98ab1e2",
          "ack_inbox": "_INBOX.XEuTFhUvRxdedrMDFzZgST",
          "queue_name": "durable:QUEUE.710c4778-721d-4784-bf82-8378bf4cbbe9.a50a32c5-2e17-41de-adcc-57e1a0382bcc",
          "is_durable": true,
          "is_offline": true,
          "max_inflight": 1,
          "ack_wait": 5,
          "last_sent": 287,
          "pending_count": 47,
          "is_stalled": true
        }
      ]
    }
```

Any insight on what is going on or how to stop these errors from happening in the future would be greatly appreciated!

**Comment by kozlovic** [comment]
Few things: all 287 messages were delivered. It shows that the channel last sequence is 287 and one of the queue member's `last_sent` is 287.

It also shows that some of the queue subscriptions are not acknowledging their messages (see `pending_count` > 0).

Yes you are using `max_inflight` of `1` but when a queue member has unacknowledged message(s) and is closed, the server reassigns those to existing active members. 

In cluster mode (not the case in standalone), a message that is assigned to a queue member is redelivered to that queue member (as long as the member is running). If this member is not able to process/ack those messages, your best course of action is to close this member so that messages are reassigned to able members.

**Comment by juandiegopalomino** [comment]
@kozlovic You are correct, the 287 messages where "delivered", but the first two subscriptions I mentioned are stuck and are not handling its pending messages correctly. Furthermore, I thought that because `"is_offline": false` the subscriptions where not closed (not sure how they're not closed). I still don't understand why the unacknowledged messages weren't place back on the queue for other subscriptions to try to handle. Perhaps then the right thing is to close the connection entirely when we see the errors I mentioned and thereby "flush" the pending messages? 
Also, would setting the pending limit to 1 be of help?

**Comment by kozlovic** [comment]
>  I still don't understand why the unacknowledged messages weren't place back on the queue for other subscriptions to try to handle.

When a message is assigned to a queue member and needs to be redelivered to another, the server needs to persist the information about which new member the message is assigned to and process an implicit ACK for the queue member it is removed from. To avoid the replication of those 2 events, early in the clustering implementation we decided to keep redelivering to the same queue member. I am exploring - as I type - possibly removing this restriction.

> Perhaps then the right thing is to close the connection entirely when we see the errors I mentioned and thereby "flush" the pending messages?

If your application is not able to process a message, then yes, closing the connection (assuming you don't share with other well behaving subscriptions) is a good way to go.

> Also, would setting the pending limit to 1 be of help?

You are already setting MaxInflight to 1. I am not sure which pending limit you are referring to, but if it is the low level NATS subscription used internally by the streaming subscription, then DON'T do that!

I will keep you posted shortly if I decide to remove the restriction of redeliveries for queue subs in cluster mode.

**Comment by juandiegopalomino** [comment]
@kozlovic ok, thank you
We'll be restarting the connection upon the issues then and hopefully clear this issue

**Comment by juandiegopalomino** [comment]
@kozlovic should there by a difference between gracefully closing a connection and ungracefully destroying the container the connection was on? It looks like when destroying the container the subscription (with the stuck "pending" messages) is still around and moreover `"is_offline": false` and `"is_stalled": false`.

**Comment by kozlovic** [comment]
Yes there is. If you don't explicitly close the connection, the server does not know about it until it will fail getting heartbeats from it and decide to close it. See those two links:
https://github.com/nats-io/nats-streaming-server#relation-to-nats
https://github.com/nats-io/nats-streaming-server#client-connections

**Comment by juandiegopalomino** [comment]
@kozlovic thank you! We're toning down the heartbeat failed count (which was ridiculously high due to oversight)
