### ISSUE TITLE
Incorrect number of subscriptions in `streaming/serverz` when durables are resumed

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats-streaming-server#819]
The reported number of subscriptions increases every time a durable (queue or not) is restarted.

**Comment by selstam** [comment]
@kozlovic Is it just the reported number or the actual number of subscriptions? Do you still need the debug information?

**Comment by kozlovic** [comment]
> Is it just the reported number or the actual number of subscriptions?

Just the reported number. You can verify with `/streaming/channelsz?channel=<name>&subs=1` and you should see just the subscriptions you have restarted.

> Do you still need the debug information?

No thanks!

**Comment by kozlovic** [comment]
@selstam If you can try to build from the PR and test, it would be great.
