### ISSUE TITLE
max_payload isn't being accepted by nats-streamer-server

### ISSUE THREAD

**Issue by mmanna-sapfgl** [nats-io/nats-streaming-server#829]
[streamer_conf.txt](https://github.com/nats-io/nats-streaming-server/files/3166308/streamer_conf.txt)

As per issue [502](https://github.com/nats-io/nats-streaming-server/issues/502), max_payload isn't being accepted when I start streaming server.

Attached is my conf file for streaming server. When the server is up and running, I tried telnet and the response shows max_payload is still the default value ~1MB

`INFO {"server_id":"Yw0yRzRvCZcliGjdJio1kn","version":"1.4.1","proto":1,"git_commit":"3e64f0b","go":"go1.11.9","host":"0.0.0.0","port":4223,"max_payload":1048576,"client_id":6}`

Is there something missing in my configuration?

**Comment by mmanna-sapfgl** [comment]
Okay again, My mistake.

After having a conversation on Slack# with @kozlovic  It appears that `max_payload` was placed under `streaming` JSON object. Once I placed it outside, it worked. 

Closing this ticket.

**Comment by kozlovic** [comment]
@mmanna-sapfgl Some settings are NATS related, some are NATS Streaming related. Only the ones that you find in the README of this repo in the configuration table should be under streaming. If you are using configuration properties name that are not in that table they should be outside of the `streaming{}` section. For instance your provided config file should be:
```
max_payload: 5000000

streaming: {
  id: "streamer1"
  store: "file"
  dir: "/streamer1"
  sd: true
  sv: true
  secure: false
  hb_interval: "10s"
  hb_timeout: "120s"
  hb_fail_count: 2
  ft_group: "ft"
  partitioning: true
  syslog_name: "myservice"

  store_limits: {
  ...
}
```
It seems to me that you took this from the `test_parse.conf` file in `test/configs` directory. This is to test internal parsing and make sure parsing works ok. You should review each property that you use and ask yourself if you really need them.
