### ISSUE TITLE
Filestore-persisted channel not cleaned up

### ISSUE THREAD

**Issue by juandiegopalomino** [nats-io/nats-streaming-server#836]
Hi guys,

This may be part of a larger bug I mentioned in issue #759, but in this current instance I think another bug has surfaced. We have deployed a nats streaming cluster with file store. Here is an example of the yaml of one of the pods in the replica set:

```
➜  nats git:(master) kubectl get pods -n nats-io nats-streaming-file-nats-streaming-cluster-1 -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-05-15T15:30:04Z"
  generateName: nats-streaming-file-nats-streaming-cluster-
  labels:
    app: nats-streaming-cluster
    chart: nats-streaming-cluster-0.2.0
    controller-revision-hash: nats-streaming-file-nats-streaming-cluster-545586d86
    heritage: Tiller
    name: nats-streaming-cluster
    release: nats-streaming-file
    statefulset.kubernetes.io/pod-name: nats-streaming-file-nats-streaming-cluster-1
  name: nats-streaming-file-nats-streaming-cluster-1
  namespace: nats-io
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: nats-streaming-file-nats-streaming-cluster
    uid: 75fa0053-63cb-11e9-8317-06f01e480742
  resourceVersion: "92484253"
  selfLink: /api/v1/namespaces/nats-io/pods/nats-streaming-file-nats-streaming-cluster-1
  uid: 501f0aaf-7726-11e9-a70e-06ca08d4d2fc
spec:
  containers:
  - args:
    - -varz
    - -channelz
    - -serverz
    - http://localhost:8222
    image: synadia/prometheus-nats-exporter:0.2.2
    imagePullPolicy: IfNotPresent
    name: metrics
    ports:
    - containerPort: 7777
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-lrtwr
      readOnly: true
  - args:
    - -clustered
    - -cid
    - test-cluster
    - -m
    - "8222"
    - -ns
    - nats://simple-nats-1.nats-io.svc.cluster.local:4222
    - -mc
    - "0"
    - -msu
    - "0"
    - -mm
    - "10000000"
    - -mb
    - 9gb
    - -ma
    - 168h
    - -mi
    - 168h
    - -hbi
    - 10s
    - -hbt
    - 10s
    - -hbf
    - "10"
    - --store
    - file
    - --dir
    - /nats/nss/store
    - --cluster_log_path
    - /nats/nss/log
    - --file_compact_enabled
    - --file_compact_frag
    - "50"
    - --file_compact_interval
    - "300"
    - --file_compact_min_size
    - "1048576"
    - --file_buffer_size
    - "2097152"
    - --file_crc
    - --file_crc_poly
    - "3988292384"
    - --file_sync
    - --file_slice_max_msgs
    - "0"
    - --file_slice_max_bytes
    - "67108931"
    - --file_slice_max_age
    - "0"
    - --file_fds_limit
    - "0"
    - --file_parallel_recovery
    - "1"
    - -SD
    - -D
    - -SV
    - -V
    image: nats-streaming:0.14.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 8222
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: nats-streaming-cluster
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 8222
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /nats/nss
      name: file-store
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-lrtwr
      readOnly: true
  dnsPolicy: ClusterFirst
  hostname: nats-streaming-file-nats-streaming-cluster-1
  nodeName: ip-10-128-118-57.us-west-2.compute.internal
  nodeSelector:
    igname: services
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: file-store
    persistentVolumeClaim:
      claimName: file-store-nats-streaming-file-nats-streaming-cluster-1
  - name: default-token-lrtwr
    secret:
      defaultMode: 420
      secretName: default-token-lrtwr
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-05-15T15:30:04Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-05-15T15:30:36Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-05-15T15:30:04Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://719761d43449415faa787e2be4b8fd14279002ac0f0f725d45f40918e5a5f55f
    image: synadia/prometheus-nats-exporter:0.2.2
    imageID: docker-pullable://synadia/prometheus-nats-exporter@sha256:65c2878b23295c72d6e265c3ebad307ddfad8e027de403c0a4e3939378b97c91
    lastState: {}
    name: metrics
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-05-15T15:30:25Z"
  - containerID: docker://49544b54247f21789872355d5710767f76f0ad57ffb1667a193af6b60d8a645a
    image: nats-streaming:0.14.1
    imageID: docker-pullable://nats-streaming@sha256:7fd164a5da4025ae97f07731e3a15025ab87062928e9379fc247e32cf55a66d1
    lastState: {}
    name: nats-streaming-cluster
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-05-15T15:30:27Z"
  hostIP: 10.128.118.57
  phase: Running
  podIP: 100.96.49.23
  qosClass: BestEffort
  startTime: "2019-05-15T15:30:04Z"
```

We've had this cluster running via a helm chart for a few months now, and over the last week we've been upgrading the chart a bit w/ new image tags and such. What struck me odd is that now we do not even see the debug logs of https://github.com/nats-io/nats-streaming-server/blob/6689b0b55650c0313c499742d6db9e8bbaabaede/server/server.go#L2731 even though we got thousands of old channels and more reaching their lifespan of 1 week every hour and the debug logs are turned on and we're seeing the other debug logs just fine. What's even more puzzling is that the message deletion seems to be progressing smoothly, as reported by the nss_server_msgs_total metric. As in the previous issue I mentioned we were getting the channel deletion log message, I think this is a new issue. Seeing that this coincided with the chart upgrade, I was wondering if it could be due to some state loss.

**Comment by kozlovic** [comment]
There has been an issue resolved since 0.14.1 (https://github.com/nats-io/nats-streaming-server/pull/824). It is in master but not in published release yet. I should be having a release soon (end of week, early next). That being said, the bug fixed would manifest only when a subscription was started and failed to be registered, so not that common.

I see from your config that the max inactivity is set to `168h` which is 7 days. Are you sure that in those 7 days there is no new published message or start (or start/stop) of a subscription on these channels?

**Comment by juandiegopalomino** [comment]
I got the following from http://localhost:8222/streaming/channelsz?subs=1&limit=5000

```
    {
      "name": "QUEUE.cc1bd0a8-e192-4e70-aba4-fb46654fd2ff.80237c44-8d26-4ac2-ae3c-03de391d4760",
      "msgs": 0,
      "bytes": 0,
      "first_seq": 3,
      "last_seq": 2,
      "subscriptions": [
        {
          "client_id": "",
          "inbox": "a1e263bde1334e73b88a8",
          "ack_inbox": "_INBOX.dEib7JD1iPZDxY8sjmDnO5",
          "queue_name": "durable:QUEUE.cc1bd0a8-e192-4e70-aba4-fb46654fd2ff.80237c44-8d26-4ac2-ae3c-03de391d4760",
          "is_durable": true,
          "is_offline": true,
          "max_inflight": 1,
          "ack_wait": 5,
          "last_sent": 2,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    }
```

I know the channel name seems random, but what it is used for is a pipeline executor, and those two uuids have a very specific meaning. This channel belongs to a pipeline run as one of many in a deployment test on the 30th of April--no one has ever even bother to look at it since. Since that time there has been several deployments, hundreds of new channels, and thousands of new messages and I promise that not a single one was for that forgotten channel. Ditto with subscriptions.

**Comment by kozlovic** [comment]
Ok thanks, I will have another look. But keep in mind that a channel delete timer is set when a server becomes leadership and has a duration set my `-mi`, which means that the timer is reset and will run the whole duration anytime a leadership change occurs. Could that be that?

**Comment by juandiegopalomino** [comment]
@kozlovic would a leadership change occur if I bounced all the servers?

**Comment by kozlovic** [comment]
if leader is restarted, it will be a leader election. If more than the quorum of followers are shutdown, when followers are restarted it will cause a leader election (gaining back quorum). If a follower is restarted (even with quorum maintained while this node was stopped), it may or may not cause a leader election.

**Comment by kozlovic** [comment]
Not to say that these are the only events that can cause leader election, but previous comments were related to server restarts.

**Comment by mmanna-sapfgl** [comment]
Is it safe ( or correct) to assume that for production it’s always better to have 3 or any higher odd number of servers to form a cluster ? Since <3 isn’t suitable for a quorum ?



Sent from my iPhone

On 15 May 2019, at 19:23, Ivan Kozlovic <notifications@github.com<mailto:notifications@github.com>> wrote:


if leader is restarted, it will be a leader election. If more than the quorum of followers are shutdown, when followers are restarted it will cause a leader election (gaining back quorum). If a follower is restarted (even with quorum maintained while this node was stopped), it may or may not cause a leader election.

**Comment by juandiegopalomino** [comment]
@kozlovic ok, so this is why I was mentioning the helm upgrades in the beginning. By updating the docker image tags (and also the args) we did a full cluster restart, as there's no way around getting such changes into the system. I'm sorry if I did not make it clear. When this happened, all the pods, including the leader, did at some point go down temporarily, so from your explanation a leader election did happen. Which would explain why the max inactivity was reset.

**Comment by kozlovic** [comment]
Yes, but even without a full restart, as I described. I will look into if there is a way to not reset the timer from scratch and somehow deduct what was the last activity, but that may not be possible.

**Comment by kozlovic** [comment]
to @mmanna-sapfgl comment, yes, you should have at least 3 and indeed an odd number.

**Comment by juandiegopalomino** [comment]
@kozlovic ok, I will close this issue now unless there's something else.
