### ISSUE TITLE
server performance

### ISSUE THREAD

**Issue by guangbaowan** [nats-io/nats-streaming-server#837]
hi, i'm reading the code and found all msgs are only delivered by the master under clustering mode, do we have plan to make msg delivered by all the nodes    ?  i'm new to msg queue , so sorry for this.

**Comment by kozlovic** [comment]
Probably not as part of this product. There are plans to have a new streaming project that will be different in term of design/tech involved.
Have you experienced performance issues or just concerned that only the leader delivers messages?

**Comment by guangbaowan** [comment]
i'm just  concerned that only the leader delivers messages. because i think if more nodes are dilivering msgs, then where will be better performance, but  the system will be more complicated. 
thank you for your answer .

**Comment by kozlovic** [comment]
As you said, with the current design, it would be very difficult to have any server serve clients, especially without client library changes. As I said, hopefully new project does not suffer from that. Closing this for now.

**Comment by guangbaowan** [comment]
and , could you please paste your new project link ? i wanna learn from that . thank you .
and my english is poor, hope you can understand  ^_^
