### ISSUE TITLE
go test now has hard database requirement

### ISSUE THREAD

**Issue by nathanejohnson** [nats-io/nats-streaming-server#845]
I'm maintaining a Centos 7 SPEC file for use internally at our company, and in the past I perform the go test step as follows:

go test ./... -args -sql=false

this means we don't have to stand up a database during build time, but we also aren't skipping all of the other tests.

as of this commit:

https://github.com/nats-io/nats-streaming-server/commit/312742a4e76a844c3a99c367a68174346c47f347

even passing -sql=false has a requirement on a database being present.

**Comment by kozlovic** [comment]
Sorry for the inconvenience, I will look into that as soon as I get a chance. For now, if this is blocking you, just add `t.Skip()` at the top of the test so that this test is entirely skipped.
