### ISSUE TITLE
Memory Usage increasing not going down

### ISSUE THREAD

**Issue by ferdianr** [nats-io/nats-streaming-server#846]
I am using nats streaming cluster in production, for store I am using mysql, but the memory that being used by nats its never decreasing, even though I have limited using max_bytes and max_msgs.
when its OOM the cluster is failure, can not contacted by the client
is there a way to decreasing it automatically?
the only way to free it up is by restarting nats.
is it normal, I have activate -sql_no_caching=true but its still increasing.

thanks before

<img width="779" alt="Screen Shot 2019-05-24 at 00 52 42" src="https://user-images.githubusercontent.com/17398383/58278205-b332f000-7dc5-11e9-9e18-ffbf1b1b5c6e.png">

**Comment by kozlovic** [comment]
Are you running this in a container? Lots of report of abnormal memory usage were just due to how docker would report mem usage, the process was actually not using it.

**Comment by ferdianr** [comment]
nope, I am running on non containers, with ram 4GB with 5 instance into 1 clusters

**Comment by ferdianr** [comment]
Correct @kozlovic , for db, I am using 1 mysql RDS instance. But as of DB its being setup per node inside the cluster.
Thanks before

**Comment by kozlovic** [comment]
@ferdianr Yes, I have identified this as a defect impacting SQLStore in clustering mode. You may notice that no message is actually stored in the database in the followers, they are all accumulating in the store's cache layer. If a follower becomes leader, it will probably take a long time (depending on number of messages) when trying to flush all those messages in the DB.
I will need to issue a 0.14.3 release this week. In the meantime, I would recommend not using SQLStore in cluster mode. Sorry about the inconvenience.

**Comment by kozlovic** [comment]
@ferdianr Actually, as described in Slack, the issue I have found is related to the cache, so when using `-sql_no_caching` I am not experiencing the memory growth. 
Would it be possible for you to run one of the node with `-profile 6060` and then when you see the memory growing to say few hundreds MBs, do this:
```
wget -q http://localhost:6060/debug/pprof/heap
go tool pprof -inuse_space ./heap 
```
and send me the output for review?

**Comment by ferdianr** [comment]
`Entering interactive mode (type “help” for commands, “o” for options)
(pprof) top
Showing nodes accounting for 1866.66kB, 100% of 1866.66kB total
Showing top 10 nodes out of 15
     flat  flat%   sum%        cum   cum%
 809.97kB 43.39% 43.39%   809.97kB 43.39%  github.com/nats-io/nats-streaming-server/server.(*StanServer).startIOLoop
 544.67kB 29.18% 72.57%   544.67kB 29.18%  github.com/nats-io/nats-streaming-server/vendor/github.com/nats-io/gnatsd/server.(*client).queueOutbound
 512.02kB 27.43%   100%   512.02kB 27.43%  github.com/nats-io/nats-streaming-server/vendor/github.com/nats-io/gnatsd/server.newNode (inline)
        0     0%   100%   809.97kB 43.39%  github.com/nats-io/nats-streaming-server/server.Run
        0     0%   100%   809.97kB 43.39%  github.com/nats-io/nats-streaming-server/server.RunServerWithOpts
        0     0%   100%   512.02kB 27.43%  github.com/nats-io/nats-streaming-server/vendor/github.com/nats-io/gnatsd/server.(*Server).createRoute.func2
        0     0%   100%   512.02kB 27.43%  github.com/nats-io/nats-streaming-server/vendor/github.com/nats-io/gnatsd/server.(*Sublist).Insert
        0     0%   100%   544.67kB 29.18%  github.com/nats-io/nats-streaming-server/vendor/github.com/nats-io/gnatsd/server.(*client).deliverMsg
        0     0%   100%  1056.69kB 56.61%  github.com/nats-io/nats-streaming-server/vendor/github.com/nats-io/gnatsd/server.(*client).parse
        0     0%   100%   544.67kB 29.18%  github.com/nats-io/nats-streaming-server/vendor/github.com/nats-io/gnatsd/server.(*client).processMsg`

**Comment by kozlovic** [comment]
Yes, but that's nothing (810KB). When you used `-sql_no_caching`, did you use it on all 3 nodes? If not, then that would explain why you said it still did grow. Also, in the issue I have found, only the follower nodes would have increased memory.
I will try to have a branch/PR for the issue I have found and you could try it. But if the issue still persists after that, then I would ask that you provide similar capture that shows the memory in-use growth. Thanks!

**Comment by kozlovic** [comment]
@ferdianr Could you try with master? I have merged PR #849 that addresses the issue with clustering and not flushing the msg store, which for SQLStore would result in memory growth on followers when using caching (default).
Again, if you still have the issue with that build, please try to provide information requested earlier so I can see what is reported in inuse_space. Thanks!

**Comment by ferdianr** [comment]
sure, will try that soon.

after a 24 hours its not decreasing from last bench that I do yesterday.

<img width="769" alt="Screen Shot 2019-05-30 at 17 20 18" src="https://user-images.githubusercontent.com/17398383/58626668-8750c680-82ff-11e9-877f-f4a3ef9deb42.png">

its increasing to 200mb and stable for 1 node

**Comment by kozlovic** [comment]
So graph above is from server without fix but with `sql_no_caching`? Again, you need to use this setting on all nodes if you want them all to not use caching.
Memory not going down is different from memory continuously growing. This is why I asked the output from profile and checking with `go tool pprof --inuse_space` which shows the currently used memory. With the bug (fixed in #849), you would see that command show memory used in the sql write cache. If you were to continue publishing and get another capture, you would see this value going up.

**Comment by ferdianr** [comment]
already use `sql_no_caching` to all nodes,
ok @kozlovic I will try the master and get back to you later.
thanks

**Comment by ferdianr** [comment]
After we upgrade the version, the memory is up and down, most of memory that use only for ~300mb.

I will close the ticket and will reopened it later if the problem is exists.

thanks @kozlovic
