### ISSUE TITLE
Details monitoring of Channel is not giving full information 

### ISSUE THREAD

**Issue by gauravpp** [nats-io/nats-streaming-server#847]
I am using following two url to get details about a channel but both of them returning same details.
 curl http://localhost:8222/streaming/channelsz?channel=foo
 curl   http://localhost:8222/streaming/channelsz?channel=foo&subs=1

![image](https://user-images.githubusercontent.com/13290556/58378160-94428280-7fac-11e9-8165-9183cfd7f2c2.png)

As per sample , Output should like below.

![image](https://user-images.githubusercontent.com/13290556/58378210-e59f4180-7fad-11e9-965b-149401546486.png)

**Comment by gauravpp** [comment]
Issue may be in s.handleOneChannel(w, r, channelName, subsOption) in monitor.go file because following url works.
curl http://localhost:8222/streaming/channelsz?subs=1

Following url does not work.

curl http://localhost:8222/streaming/channelsz?channel=foo&subs=1


![image](https://user-images.githubusercontent.com/13290556/58380936-89501800-7fd5-11e9-906b-8585360d6ff4.png)

**Comment by kozlovic** [comment]
No, it's likely because you need to surround the command with double quotes `"` because of the use of symbol `&` if you use it with `curl`.
The references in the README.md were given to use in your browser.
