### ISSUE TITLE
Messages are not removed from store even after reaching size limit

### ISSUE THREAD

**Issue by gauravpp** [nats-io/nats-streaming-server#848]
For Nats store testing purpose, I created a server with store size 20 KB and messages expiry as 1 min.
I published 5  messages of size 8KB each. In channel only 2 messages are visible since next message was reaching store limit. after 1 min even those 2 messages disappeared. But when I checked the store size it shows 40 KB . None of the messages were removed from file. 

**I have few questions:** 
1) These messages will be deleted from file store?
2) Is there a way to reduce file size manually?

Requirement is to calculate disk size on cloud for persistent storage.

Please refer screenshot below

**Store** 
![image](https://user-images.githubusercontent.com/13290556/58383318-d8f10c80-7ff2-11e9-863a-28208880b7d0.png)

**Monitoring API Response**
![image](https://user-images.githubusercontent.com/13290556/58383319-ddb5c080-7ff2-11e9-8817-53368803e191.png)

**Store size on disk**

![image](https://user-images.githubusercontent.com/13290556/58383325-ee663680-7ff2-11e9-9886-570729ff36e0.png)

**Comment by kozlovic** [comment]
The FileStore implementation uses a concept of slices to be able to remove older messages efficiently (performance wise). But it means that it can hold more messages that the limit set in the channel. Please review this chapter: https://github.com/nats-io/nats-streaming-server#file-store and specifically for more information about file slices configuration: https://github.com/nats-io/nats-streaming-server#file-store-options.
