### ISSUE TITLE
What kind of use cases the starting from n-th message are intended for?

### ISSUE THREAD

**Issue by Manuri** [nats-io/nats-streaming-server#865]
I can see that, with NATS streaming it is possible for a consumer to mention starting from which message in the stream it needs the messages to be sent. 

Is this intended for cases where consumer,

1. Doesn't care when he starts receiving exactly
2. But needs to start receiving messages starting from a certain time window
?

**Comment by kozlovic** [comment]
Starting at a specific sequence number can be used by applications that keep track of the last sequence they have seen and want to recreate the subscription (say after failure) to that specific position.

**Comment by Manuri** [comment]
So this is for kind of a durable subscription where consumer keeps track of where he stopped?

Is that practical when the rate of messages is very very high and message limit can be reached easily?

**Comment by kozlovic** [comment]
No, for a durable subscription you don't need the start position when you restart the durable subscription (the start position is actually ignored). This is more for non durables or after unsubscribing a durable subscription.

**Comment by Manuri** [comment]
Yeah. I mean, with durable subscriptions, server makes sure that consumer starts at where he left off.

With the possibility of starting at n-th position, when consumer disconnects and connects back, if he remembers where he left off he can start from there, right?
That is why I thought this is more like providing the capability for the non-durable consumer to keep a durable-like subscription.

Just for my knowledge, have you got any examples for NATS users using this feature in huge scalable systems?

**Comment by kozlovic** [comment]
For non durable subscription when the subscription is closed it is removed from the server. So "restarting" the subscription means that you need to specify a starting position. 

Also, having the ability does not mean that you have to use that. You can use ask to get all messages or starting at the last or only the new ones, or based on timestamp, but know that at the end this translates to a sequence in the message log.

As for use cases, I don't have one. You may want to as that to our community in our Slack channels. If you are not there, you should [join](https://join.slack.com/t/natsio/shared_invite/enQtMzE2NDkxNDI2NTE1LTc5ZDEzYTkwYWZkYWQ5YjY1MzBjMWZmYzA5OGQxMzlkMGQzMjYxNGM3MWYxMjNiYmNjNzIwMTVjMWE2ZDgxZGM).

**Comment by Manuri** [comment]
Cool, I just joined the slack channel.
I'm doing some improvements to the NATS client we are writing for [Ballerina](https://github.com/ballerina-platform/ballerina-lang). I'm trying to understand the concepts and the use cases. Thanks for the quick responses!
