### ISSUE TITLE
telnet connect to auth_required nats server

### ISSUE THREAD

**Issue by vietthang207** [nats-io/nats-streaming-server#866]
When I try to telnet to a auth_required nats server I've received this error:

INFO {"server_id":"56aEAuhN63YKzkEICM8AcD","version":"1.4.1","proto":1,"git_commit":"3e64f0b","go":"go1.11.5","host":"0.0.0.0","port":4222,"auth_required":true,"max_payload":1048576,"client_id":46} 
-ERR 'authorization timeout'
Connection closed by foreign host.

How can I supply the username and password to telnet? I tried telnet -l but it didn't work.
Is there alternative to telnet for debugging nats.

Thanks in advance!

**Comment by ripienaar** [comment]
You need to send a `CONNECT` line with the `user` and `pass` set - it's text that must be entered into the telnet session.

**Comment by ripienaar** [comment]
https://nats.io/doc/internals/nats-protocol/#CONNECT

**Comment by kozlovic** [comment]
@vietthang207 As @ripienaar mentioned, if the server requires authorization, you need to be able to send the CONNECT protocol with proper user/password before the configured timeout (default is 0.5s I believe).

**Comment by vietthang207** [comment]
Thanks you guys for your help! I am able to connect now. Previously, I don't think I can enter anything because of 0.5s timeout, now I know that I need to type them before hand and then copy/paste to the terminal.

**Comment by Cingulara** [comment]
https://docs.nats.io/nats-protocol/nats-protocol#connect now

**Comment by kozlovic** [comment]
@Cingulara Not sure of the meaning of your post...
