### ISSUE TITLE
about nats log

### ISSUE THREAD

**Issue by zhaodanwjk** [nats-io/nats-streaming-server#868]
We found that when nats is configured with log path and trace log level is turned on by default, the log is very large, and using supervisor to make nats process hang in the background log cannot be split. When the log is too large to fill up the disk, we emptied the nats log without stopping the nats process, and at the same time found that the online business was affected and delayed. why is this? The nats log is about 100G. After vim is used to open it, the nats process takes up 10G of system memory and usually only about 60M.

**Comment by zhaodanwjk** [comment]
Can the configuration of nats not specify the configuration information about log

**Comment by ripienaar** [comment]
trace and debug is certainly not on by default, how do you deploy NATS?

copytruncate in logrotate works fine and you can also signal it to reopen log files

**Comment by zhaodanwjk** [comment]
Hi，we have encountered two problems in using nats now.
1. When the log fills up the disk, there is a delay in service when the log is emptied online。
2. When the log is too large (about 100 G) and vim is used to open the log for viewing, the system memory occupied by nats process will soar to 10 G.

**Comment by ripienaar** [comment]
How do you empty the log? The log should not ever get that big, you need to set up operating system appropriate log rotation and configure NATS not to log in trace mode (which isnt the default). Log rotation isn't a function of the software but of your OS.

`vim` is not for viewing files, use `less`.

**Comment by zhaodanwjk** [comment]
Thank you very much.  why open log can cause nats service mem rise violently？

**Comment by zhaodanwjk** [comment]
“echo > nats.log ” Log was cleared using this command. And why empty log will cause nats service timeout？

**Comment by ripienaar** [comment]
Not sure why NATS server specifically would grow then - but the pause could well be your VM being under heavy IO at the time.

**Comment by kozlovic** [comment]
@zhaodanwjk Would be curious to know what is filling up your log if you don't have debug/trace enabled. As @ripienaar mentioned, you should make a copy of the log and then you can issue a signal to server to re-open the log file.
