### ISSUE TITLE
Message not replaying if subscriber is registered after message is published

### ISSUE THREAD

**Issue by rjdp** [nats-io/nats-streaming-server#874]
# Producer

```
var stan = require('node-nats-streaming').connect('nats', 'test', {url: 'nats://nats-streaming:4222'});
stan.on('connect', function() {

  stan.publish('foo', 'Hello node-nats-streaming!', function(err, guid) {
    if (err) {
      console.log('publish failed: ' + err);
    } else {
      console.log('published message with guid: ' + guid);
    }
  });
})
```

# Consumer
```
var stan = require('node-nats-streaming').connect('nats', 'tes', {
  url: 'nats://nats-streaming:4222'
});
var opts = stan.subscriptionOptions();
opts.setDeliverAllAvailable();
opts.setDurableName('my-durable');
var subscription = stan.subscribe('foo', opts);

subscription.on('message', function(msg) {
  console.log('Received a message [' + msg.getSequence() + '] ' + msg.getData());
});
```

**Comment by acro5piano** [comment]
I tested your code and got an error:

```
            throw (new NatsError(BAD_SUBJECT_MSG, BAD_SUBJECT));
            ^
NatsError: Subject must be supplied
```

It seems that you must add a connection handler like

```js
var stan = require('node-nats-streaming').connect('nats', 'tes', {
  url: 'nats://nats-streaming:4222'
});

stan.on('connect', function() {
  stan.publish('foo', 'Hello node-nats-streaming!', function(err, guid) {
    if (err) {
      console.log('publish failed: ' + err)
    } else {
      console.log('published message with guid: ' + guid)
    }
  })
})
```

**Comment by rjdp** [comment]
thanks @acro5piano  for replying,   i was running this in node repl so I used to copy paste line by line maybe thats why I did not get the error (which I suspect will happen when its runs as script), nonetheless what I intended to achieve is that even if there are no subscriber when a message was published on a subject (probably subscriber crashed somehow or is just offline) wbut when it comes online it should be able to get those messages , My usecase is inspite of point of failures in subscriber the message must eventually be processed

**Comment by acro5piano** [comment]
> nonetheless what I intended to achieve is that even if there are no subscriber when a message was published on a subject (probably subscriber crashed somehow or is just offline) wbut when it comes online it should be able to get those messages

Yes, NATS should do that.
Please test it not REPL but saved files.

**Comment by aricart** [comment]
The subscriber code needs to make a subscription after the connect event is sent. See https://github.com/nats-io/stan.js/blob/master/README.md#durable-subscriptions
