### ISSUE TITLE
Is there transaction/distributed transaction support in NATS?

### ISSUE THREAD

**Issue by Manuri** [nats-io/nats-streaming-server#876]

**Comment by vtolstov** [comment]
No, but you can do that by self.

**Comment by Manuri** [comment]
@vtolstov Can you please elaborate further? When you say "No", what sort of missing features are you implying?

I'm thinking of following scenarios.

1. Assume that I need to implement a transaction scenario where only one Streaming NATS server is involved in. I'm doing a set of publishing subscribing operations and that I need to happen as a transaction i.e. if one of those actions fails, I need the complete set of operations to be rolled-back.

2. Assume that I need to implement an XA transaction scenario having NATS server as one of the resource managers. So there should be 2 phase commit support

**Comment by vtolstov** [comment]
Distribution transaction is hard in microservice world. Do you read about saga pattern? Nats is more useful for saga pattern systems. But with own app you can use and distributed transaction too (manually send rollback events if one event failed)

**Comment by Manuri** [comment]
Yes, I'm familiar with saga. Seems we have to go for a compensation based model if we need transactions with NATS, I suppose.

**Comment by kozlovic** [comment]
@Manuri There is no distributed transaction support in NATS.
