### ISSUE TITLE
ack questions

### ISSUE THREAD

**Issue by YoninL** [nats-io/nats-streaming-server#878]
in readme there is "The streaming server is expected to send ACKs back to producers and receive ACKs from consumers." Can streaming server forward ACKs from consumers to producers or the two ACKs are handled separately?

**Comment by kozlovic** [comment]
> Can streaming server forward ACKs from consumers to producers or the two ACKs are handled separately?

No.. and you don't need NATS Streaming for that, just NATS core and request/reply. Here is more information: https://nats-io.github.io/docs/developer/concepts/reqreply.html
