### ISSUE TITLE
Can I use the nats-server inside nats-streaming-server independently?

### ISSUE THREAD

**Issue by didip** [nats-io/nats-streaming-server#879]
Seeing that nats-streaming-server embed nats-server, can I use it independently from nats-server?

I have 2 use-cases, one requires the durability of nats-streaming-server, however the other use-case is very ephemeral (in-memory).

Or should I install nats-server separately?

**Comment by kozlovic** [comment]
Yes, you can use the embedded nats-server for normal NATS communication.

**Comment by didip** [comment]
Is it running on a different port? Any docs on how to use it?

**Comment by kozlovic** [comment]
The streaming server embeds the NATS Server. When you run NATS Streaming, the streaming code starts a NATS Server as a go routine. NATS Streaming is a client to NATS Server (https://nats-io.github.io/docs/nats_streaming/relation-to-nats.html). So there is no different port, the port is the one used by NATS Server.
