### ISSUE TITLE
messages lost / no delivery / stall

### ISSUE THREAD

**Issue by biskit** [nats-io/nats-streaming-server#890]
i have a standalone server 
```
{
  "cluster_id": "test-cluster",
  "server_id": "gvPFAMs40rG0R0Wso55Tuu",
  "version": "0.15.1",
  "go": "go1.11.10",
  "state": "STANDALONE",
  "now": "2019-07-27T15:19:56.751293947-05:00",
  "start_time": "2019-07-27T14:21:56.195447876-05:00",
  "uptime": "58m0s",
  "clients": 1,
  "subscriptions": 4,
  "channels": 4,
  "total_msgs": 13390,
  "total_bytes": 27107825,
  "open_fds": 29,
  "max_fds": 1024
}
```
that after a few hours (say 6-8) hours of being subscribed to a durable queue stops delivering messages.
my launch setup is
```
nohup ./nats-streaming-server -st file -dir ./data -m 8222 -mi 5m -ma 1h > /dev/null 2>&1 &
```

i have no way to know its hung to disconnect and re-subscribe. 
i have seen #604 that address it but seems not. 

the way i observe is i stop getting messages in my app and searching for it in certain time ranges fail (because data was not updated).

i have monitoring turned on, but hard to check for stalls. how does one proceed?

**Comment by kozlovic** [comment]
You can inspect a given channel and get the list of subscriptions. Check [this](https://github.com/nats-io/nats-streaming-server#channelsz) for more details.

For example, for channel named `foo`: you would look at: `http://<host>:8222/streaming/channelsz?channel=foo&subs=1`

If you could provide us with such output for the channel and subscription(s) in question, that may help. Thanks!

**Comment by biskit** [comment]
I have and been looking at the link provided above as well... and the stats.

Will setup a SetConnectionLostHandler() as well to see if connection is lost.

In the meantime here's the current status:
```
{
  "cluster_id": "test-cluster",
  "server_id": "gvPFAMs40rG0R0Wso55Tuu",
  "now": "2019-07-27T15:44:06.129972317-05:00",
  "offset": 0,
  "limit": 1024,
  "count": 4,
  "total": 4,
  "channels": [
    {
      "name": "1",
      "msgs": 397,
      "bytes": 297973,
      "first_seq": 220,
      "last_seq": 616,
      "subscriptions": [
        {
          "client_id": "3fdaa6b92d754bfd853cb45a6c96e667_8161",
          "inbox": "_INBOX.WLalSKCj3XMeJaJr1xbX6D",
          "ack_inbox": "_INBOX.gvPFAMs40rG0R0Wso55Uf6",
          "durable_name": "3fdaa6b92d754bfd853cb45a6c96e667_8161_1_durable",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 616,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    },
    {
      "name": "2",
      "msgs": 9608,
      "bytes": 6486411,
      "first_seq": 3341,
      "last_seq": 12948,
      "subscriptions": [
        {
          "client_id": "3fdaa6b92d754bfd853cb45a6c96e667_8161",
          "inbox": "_INBOX.WLalSKCj3XMeJaJr1xbXDF",
          "ack_inbox": "_INBOX.gvPFAMs40rG0R0Wso55Uks",
          "durable_name": "3fdaa6b92d754bfd853cb45a6c96e667_8161_2_durable",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 12948,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    },
    {
      "name": "3",
      "msgs": 3601,
      "bytes": 21442134,
      "first_seq": 1235,
      "last_seq": 4835,
      "subscriptions": [
        {
          "client_id": "3fdaa6b92d754bfd853cb45a6c96e667_8161",
          "inbox": "_INBOX.WLalSKCj3XMeJaJr1xbX9j",
          "ack_inbox": "_INBOX.gvPFAMs40rG0R0Wso55Uhz",
          "durable_name": "3fdaa6b92d754bfd853cb45a6c96e667_8161_3_durable",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 4835,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    },
    {
      "name": "4",
      "msgs": 397,
      "bytes": 373244,
      "first_seq": 220,
      "last_seq": 616,
      "subscriptions": [
        {
          "client_id": "3fdaa6b92d754bfd853cb45a6c96e667_8161",
          "inbox": "_INBOX.WLalSKCj3XMeJaJr1xbXGl",
          "ack_inbox": "_INBOX.gvPFAMs40rG0R0Wso55Unl",
          "durable_name": "3fdaa6b92d754bfd853cb45a6c96e667_8161_4_durable",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 616,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    }
  ]
}
```

**Comment by kozlovic** [comment]
Yes, do set that callback because it is possible that the connection was lost and if you simply consume, you would not know otherwise. (the server logs if it discards a client due to failed HB, but only in debug mode).
From above output, all consumers have been receiving the last message from each channel, so nothing wrong yet.

**Comment by biskit** [comment]
i will monitor.

if an automatic reconnect happens and i dont resubscribe will publish continue successfully? ie does publish survive reconnects?

**Comment by kozlovic** [comment]
It's complicated ;-) Here is more background info: https://github.com/nats-io/stan.go#connection-status

**Comment by biskit** [comment]
i think the situation may be a little more than that :)

1. i have async publish and assume a reconnect happened to the streaming server. 
2. i'm receiving messages from a source and dumping it in the async publish channel. 
3. i believe, the channel either buffers it somewhere or drops it.
4. i'm not seeing any errors (or did not look in my logs for it and dont have them anymore till my situation happens again).
5. my subscribers just sit connected to a lost connection as they don't have any callback for disconnect status.
6. overall there's an eery stall

not sure if such a case is explained in the "Connection Status" section or is even possible without any kind of errors being thrown up.

**Comment by kozlovic** [comment]
Do you check/report the possible error that you get in the async publish callback? If you did not set the SetConnectionLostHandler and don't check publish error, then application could continue to publish messages that would simply be dropped by the server if the server had disconnected the client.

**Comment by biskit** [comment]
Yes I do check for errors ;-) in the PublishAsync call and log them. I blew away the files after looking for my usual suspects.
I will look for them now, knowing what to look. 
It takes a few hours but happens consistently.

I don't understand how the server can drop the messages knowing well its the same client that reconnected... (i'm using stan v0.5.0 that supports auto reconnect).

**Comment by kozlovic** [comment]
There is no auto-reconnect, at all. Not sure where you got that from. If the server drops the client, the connection is lost (hence the name: SetConnectionLostHandler).

**Comment by biskit** [comment]
> When no NATS connection is provided to the Connect() call, the library creates its own NATS connection and will now set the reconnect attempts to "infinite", which was not the case before. It should therefore be possible for the library to always **reconnec**t, but this does not mean that the streaming connection will not be closed, even if you set a very high threshold for the PINGs max out value.


am i misreading this?

**Comment by kozlovic** [comment]
> When no NATS connection is provided to the Connect() call ... now set the reconnect attempts to "infinite" .. be possible for the library to always reconnect, but this does not mean that the *streaming connection* will not be closed

What this says is that if you don't provide a NATS connection to the stan.Connect() call, the library creates its own NATS Connection and can set the reconnect attempts to -1, which means infinite. But this is the low level NATS Connection, not the Streaming connection. There could be a valid NATS connection, but the streaming connection (see that at a session between the Streaming server and client) could be lost forever. 

https://github.com/nats-io/nats-streaming-server#relation-to-nats
https://github.com/nats-io/nats-streaming-server#client-connections

**Comment by biskit** [comment]
so, i see that a particular channel has stalled...
how to unstall this without stop start my app or resubscribe? 
no connections have been lost, just stall.

the app still continues to receive messages and push to nats.

i understand this is the fast producer/slow consumer problem, so is it just me tuning it on my side?

```
{
  "cluster_id": "test-cluster",
  "server_id": "gvPFAMs40rG0R0Wso55Tuu",
  "now": "2019-07-29T11:44:46.282582387-05:00",
  "offset": 0,
  "limit": 1024,
  "count": 4,
  "total": 4,
  "channels": [
    {
      "name": "1",
      "msgs": 342,
      "bytes": 253394,
      "first_seq": 4157,
      "last_seq": 4498,
      "subscriptions": [
        {
          "client_id": "3fdaa6b92d754bfd853cb45a6c96e667_8161",
          "inbox": "_INBOX.c2jstiII0TmQ2ZPj0EkSpo",
          "ack_inbox": "_INBOX.gvPFAMs40rG0R0Wso55WQo",
          "durable_name": "3fdaa6b92d754bfd853cb45a6c96e667_8161_1_durable",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 4498,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    },
    {
      "name": "2",
      "msgs": 4083,
      "bytes": 2703051,
      "first_seq": 77444,
      "last_seq": 81526,
      "subscriptions": [
        {
          "client_id": "3fdaa6b92d754bfd853cb45a6c96e667_8161",
          "inbox": "_INBOX.c2jstiII0TmQ2ZPj0EkSwo",
          "ack_inbox": "_INBOX.gvPFAMs40rG0R0Wso55WWa",
          "durable_name": "3fdaa6b92d754bfd853cb45a6c96e667_8161_2_durable",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 81526,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    },
    {
      "name": "3",
      "msgs": 3600,
      "bytes": 21422140,
      "first_seq": 38243,
      "last_seq": 41842,
      "subscriptions": [
        {
          "client_id": "3fdaa6b92d754bfd853cb45a6c96e667_8161",
          "inbox": "_INBOX.c2jstiII0TmQ2ZPj0EkStJ",
          "ack_inbox": "_INBOX.gvPFAMs40rG0R0Wso55WTh",
          "durable_name": "3fdaa6b92d754bfd853cb45a6c96e667_8161_3_durable",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 39242,
          "pending_count": 1024,
          "is_stalled": true
        }
      ]
    },
    {
      "name": "4",
      "msgs": 342,
      "bytes": 315174,
      "first_seq": 4157,
      "last_seq": 4498,
      "subscriptions": [
        {
          "client_id": "3fdaa6b92d754bfd853cb45a6c96e667_8161",
          "inbox": "_INBOX.c2jstiII0TmQ2ZPj0EkT0J",
          "ack_inbox": "_INBOX.gvPFAMs40rG0R0Wso55WZT",
          "durable_name": "3fdaa6b92d754bfd853cb45a6c96e667_8161_4_durable",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 4498,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    }
  ]
}
```

**Comment by kozlovic** [comment]
The channel of interest is this one:
```
{
      "name": "3",
      "msgs": 3600,
      "bytes": 21422140,
      "first_seq": 38243,
      "last_seq": 41842,
      "subscriptions": [
        {
          "client_id": "3fdaa6b92d754bfd853cb45a6c96e667_8161",
          "inbox": "_INBOX.c2jstiII0TmQ2ZPj0EkStJ",
          "ack_inbox": "_INBOX.gvPFAMs40rG0R0Wso55WTh",
          "durable_name": "3fdaa6b92d754bfd853cb45a6c96e667_8161_3_durable",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 39242,
          "pending_count": 1024,
          "is_stalled": true
        }
      ]
    },
```
it shows that the server has sent up to the MaxInflight (1024) messages to that consumer which did not ack any of those messages, causing the server to mark this consumer as stalled. 
If that same application is able to ping/send messages to the server, it is unlikely to be a network issue, although you could have a half-duplex connection issue, but then I would assume that the application would miss the server ping responses and at one point report the connection lost (assuming you set the connection lost handler).

You need to add some logging to your application, at the top of the message callback, and make sure to log that message are received, prior to any of processing of this message. If those messages have not been received by the library, the server will resend them every 30sec (AckWait), unless it has also missed heartbeats responses  from the client. If that is the case, after a while the server will close this connection due to lack of heartbeats.

**Comment by biskit** [comment]
I have been doing that and I think its case of slow consumer. I see the `last_sent` number steadily increasing, so the processing/ack is all happening. Is it just the slow pace causing this stall?
should changing to `SetManualAckMode()` make a difference? (or) I need to figure out how to process faster? :-)

**Comment by kozlovic** [comment]
Well, if you know that it is just slow, then I would not be considering that a message lost/no delivery. Changing the ack mode will not change anything. Since message are delivered to the message callback serially, then doing an explicit ack say at top of function won't help, since the rest of the processing will be slow and delay that much the processing of next message.

Once you have determined that messages are not lost but simply that the consumer is slow, then you have to ask yourself: is that ok or not? Speeding processing of a message is on you ;-). You can obviously divert those messages to separate internal queue so that callback acks/returns quickly, but that defeats the point of a consumer ack since if your application were to crash with say 100s of messages in that queue waiting to be processed, the server would not redeliver them on restart since it would have received an ack for those.

**Comment by biskit** [comment]
Thanks for all the explanations Ivan. It's been super helpful in figuring out some of my issues that were tangential to this as well as knowing the right way to talk to nats streaming.
