### ISSUE TITLE
Caching not acked message when server is down?

### ISSUE THREAD

**Issue by alanyeung95** [nats-io/nats-streaming-server#893]
My first time to open an issue in the community, be gentle with me ;)

Hello, I have study and try the NATS streaming with filestore, but there are somethings that I still not understand.

### What I did
I start a NATS streaming server, a publisher and a subscriber, with the following setting:

```
    nc, err := nats.Connect(URL, nats.MaxReconnects(-1), nats.ReconnectHandler(func(_ *nats.Conn) {
        fmt.Println("reconnect")
    }))
...
    sc, err := stan.Connect(clusterID, clientID, stan.NatsConn(nc), stan.PubAckWait(time.Second*5), stan.Pings(10, 1000), stan.SetConnectionLostHandler(func(_ stan.Conn, reason error) {
        log.Fatalf("Connection lost, reason: %v", reason)
    }))
```

Then I stop the NATS server for around 5 mins and keep publishing. Then every published message get a blocking error, which is expected.
```
stan: publish ack timeout
```
And the Stan connection is not closed due to high PINGs threshold, which is expected also. 

But what I didn’t expect is that, after I restarting NATS streaming server, the subscriber can still receive the not acked message sent by the publisher before when the server is down.

I check the files store directory, and it seems that there is no write operation to the data file when the server is down, which match my finding on those issues: https://github.com/nats-io/nats-streaming-server/issues/613#issuecomment-403533665, https://github.com/nats-io/nats-streaming-server/issues/183#issuecomment-255840498 .  Caching message is server’s responsibility

### Questions
**So I get a kind of confused, how the messages are cached when the server is down? Is the publisher caching the not acked message also?**

I also tried another experiment, second time I just extended the server down duration to 30 mins. Although the reconnect was still alive and the subscriber can receive upcoming messages, **this time the subscriber just lost all the not acked messages. Any idea (memory issue?) that what brings this inconsistency of outcome?**

**Comment by kozlovic** [comment]
The problem is that you provide a NATS connection and you did not set the ReconnectBufSize() to -1 to disable it. Therefore, the low level publish protocols are saved in the NATS core library and resent on reconnect. Some of those pubs may make it to the server, some won't.

It was a mistake to allow user to pass a NATS connection. Instead, we should have accepted options, but have STAN create the NATS connection based on those options, but then be able to override the values we wanted.

**Comment by vtolstov** [comment]
@kozlovic can you add new method for stan?

**Comment by kozlovic** [comment]
I think that yes we should, and deprecate the current Connect(). Unfortunately Connect() is a better name than any we would add now ;-)

**Comment by alanyeung95** [comment]
Nice! Thank for the help! The `ReconnectBufSize` is the key!

Although it will throw the error ``` nats: outbound buffer limit exceeded``` during publishing, it is expected in my case.

Closing this issue as I don't have any further concern.

**Comment by vtolstov** [comment]
@kozlovic follow go naming you can use Dial name too =)

**Comment by kozlovic** [comment]
@vtolstov Good idea!
