### ISSUE TITLE
[Question]: can I use single NATS cluster in fault tolerant setup

### ISSUE THREAD

**Issue by shamil** [nats-io/nats-streaming-server#894]
Hi,

In the examples I see fault tolerance configured using embedded NATS with routing. Can I have single (non-embedded) NATS cluster instead, and avoid using routes?

**Comment by ripienaar** [comment]
NATS clusters use routes, your non embedded one would also use routes.  You can use it yes, but it will end up being the same underlying structure

**Comment by shamil** [comment]
Thanks for the inf @ripienaar 

So assuming I've external NATS cluster (`nats.internal`) the following start commands will work, or I still need to pass routes?

First `stan` server

```shell
nats-streaming-server -store file -dir datastore -ft_group "ft" -nats_server nats://nats.internal:4222
```

Second `stan` server

```shell
nats-streaming-server -store file -dir datastore -ft_group "ft" -nats_server nats://nats.internal:4222
```

**Comment by ripienaar** [comment]
yes that will work - but i think that implies you then have only 1 nats server? so if that one is down all is down

**Comment by kozlovic** [comment]
@shamil As @ripienaar mentioned this would work. Also note that you can pass a list of URLs to `-`-nats_server` if need be.
