### ISSUE TITLE
Getting messages without Subscribe from a Stan connection

### ISSUE THREAD

**Issue by biskit** [nats-io/nats-streaming-server#900]
is there a way to get messages if any in a durable queue and exit? 

i want to be able to set a timer and look/get messages when timer fires.

thanks

**Comment by kozlovic** [comment]
Sorry I am not sure I fully understand the question. All subscriptions in streaming are asynchronous, meaning that their callback is invoked when a message is available.
What you could do is start the subscription and then start a timer that if no message is received by the time the timer fires, then you can close the subscription and exit.

**Comment by biskit** [comment]
Thanks, that's what I decided to do. 

I just went looking to see if there was an analog to nc.SubscribeSync() / nc.NextMsg().
