### ISSUE TITLE
How to selectively delete data in NATS Streaming Server to comply with European GDPR?

### ISSUE THREAD

**Issue by CarloWakefield** [nats-io/nats-streaming-server#903]
To comply with [European GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) it is sometimes necessary to delete data selectively (for example user related data). Is there any way to selectively delete messages from a subject with NATS Streaming Server?

**Comment by kozlovic** [comment]
In NATS Streaming you cannot remove specific messages from a channel (message log). Older messages may be dropped only based on administrative limits set globally or per channel. But even with FileStore implementation for instance, there is no guarantee that an old message that is not available for delivery is actually physically removed from disk. It will when all messages in a file slice (configurable) have been dropped (https://github.com/nats-io/nats-streaming-server#file-store-options).
