### ISSUE TITLE
Message statistics of durable subscription group

### ISSUE THREAD

**Issue by chunytan** [nats-io/nats-streaming-server#907]
Assume that I have a durable subscription group to a certain channel, and that there are multiple subscribers in that group:

At any point in time, is it possible to know the messagestatistics about, e.g. what is the newest message (or with maximum SEQ) published to and acknowledged by that particular subscription group?

I am very interested as well in how NATS streaming server handles this information internally. I could, for example, use "SELECT max(lastsent) FROM subscriptions WHERE id = $1" directly in the database, assuming that there is always only one sub-group to that channel. However, this is only an estimation, and when all subscribers in the group are disconnected, the max(lastsent) is 0 for newly-created subscribers.

Thanks in advance!

**Comment by kozlovic** [comment]
Using monitoring (https://nats-io.github.io/docs/nats_streaming/monitoring/endpoints.html) you may be able to gather from all subscriptions of the same group for a given channel (https://nats-io.github.io/docs/nats_streaming/monitoring/endpoints.html#channelsz), the member with the higher `last_sent`, and the channel's `last_seq`

**Comment by chunytan** [comment]
Thanks for your help! The monitoring endpoint indeed contains more useful information.
