### ISSUE TITLE
proto is missing in client table when using mysql as backend

### ISSUE THREAD

**Issue by MartinForReal** [nats-io/nats-streaming-server#912]
https://github.com/nats-io/nats-streaming-server/blob/b81b02610a2625588233666829c0c1e921aacdf4/stores/sqlstore.go#L1241

got a field called proto
but no proto is defined in https://github.com/nats-io/nats-streaming-server/blob/b81b02610a2625588233666829c0c1e921aacdf4/scripts/mysql.db.sql#L2

**Comment by kozlovic** [comment]
@MartinForReal As you can see, I added the alter at the end of this file (https://github.com/nats-io/nats-streaming-server/blob/b81b02610a2625588233666829c0c1e921aacdf4/scripts/mysql.db.sql#L9). The reason was that I wanted to have people be able to update their DB schema using this script.
