### ISSUE TITLE
Add "NATS Streaming Server is ready" message to log

### ISSUE THREAD

**Issue by CarloWakefield** [nats-io/nats-streaming-server#917]
With the NATS server there is the log message `Server is ready` when the NATS server is ready to receive messages.

However for NATS Streaming Server there is no such log message. Such a message would be **very** useful for testing or monitoring purposes. (In my current case I would like to use it for a [testcontainer](https://github.com/testcontainers/testcontainers-java).)

Please add such a message to the log.

**Comment by kozlovic** [comment]
@CarloWakefield I have added the message "Streaming Server is ready" to the server log. Note that this is "Streaming Server" as opposed to "NATS Streaming Server" simply to be consistent with the NATS Server logging that prints "Server is ready" and not "NATS Server is ready"..

**Comment by CarloWakefield** [comment]
> @CarloWakefield I have added the message "Streaming Server is ready" to the server log. Note that this is "Streaming Server" as opposed to "NATS Streaming Server" simply to be consistent with the NATS Server logging that prints "Server is ready" and not "NATS Server is ready"..

Thank you very much. :-)
