### ISSUE TITLE
Feature: Add NATS account feature to Streaming

### ISSUE THREAD

**Issue by donovansolms** [nats-io/nats-streaming-server#933]
Are there any plans to add [Accounts](https://nats-io.github.io/docs/nats_server/accounts.html) to NATS Streaming?

This is probably loosely tied to the discussion in #772 as well as #788, especially around the comment

> We need to add some form of authentication/authorization at the NATS Streaming level since one cannot fully leverage the provided low level NATS ones

_Note: I've added this as a separate request because the other requests are close, but not quite the same._

**Comment by kozlovic** [comment]
Not directly. But the workaround we suggest now is to use the leafnode capabilities. See https://github.com/nats-io/nats-streaming-server/issues/926#issuecomment-526266123 for some details.
