### ISSUE TITLE
how to use redis replace ReconnectBufSize?

### ISSUE THREAD

**Issue by peng-w** [nats-io/nats-streaming-server#938]
Hello:
    I want to save messages to redis when the network is down, instead of using ReconnectBufSize?
    When the network recovers, the data in redis will continue to be sent to the nats.
    Whether the corresponding interface is provided? Can you give me some guidance?
    Thank you!

**Comment by sasbury** [comment]
Streaming uses the underlying nats buffer. There isn't a separate buffer at
the streaming level, beyond the maximum acks that can be out .

**Comment by peng-w** [comment]
Thank you.
