### ISSUE TITLE
Go 1.13 modules: go get errors with "invalid pseudo-version" for golang.org/x/sys

### ISSUE THREAD

**Issue by blixt** [nats-io/nats-streaming-server#939]
With [the new `+incompatible` Go module verification](https://tip.golang.org/doc/go1.13#version-validation), the golang.org/x/sys dependency currently in the `go.mod` of version 0.16.0 of this package causes an error.

I think all that is needed to fix this is to either remove the pseudo-version from the dependency, or bumping the version to the latest.

```
▶ go version
go version go1.13 darwin/amd64
▶ mkdir test
▶ cd test
▶ go mod init example.com/test
go: creating new go.mod: module example.com/test
▶ go get github.com/nats-io/nats-streaming-server
go: downloading github.com/nats-io/nats-streaming-server v0.16.0
go: extracting github.com/nats-io/nats-streaming-server v0.16.0
go get: github.com/nats-io/nats-streaming-server@v0.16.0 requires
	golang.org/x/sys@v0.0.0-20190726091711-fde4db37ae7a: invalid pseudo-version: does not match version-control timestamp (2019-08-13T06:44:41Z)
```

**Comment by blixt** [comment]
I just tested with the unpublished version of this package and it works fine, so really all that's needed to close this issue is to add another tag, even if it's just `v0.16.1`.

**Comment by kozlovic** [comment]
Yes, I think this was solved in PR: https://github.com/nats-io/nats-streaming-server/pull/924. I am going to issue a new release very soon (was waiting on few things to land to master).
