### ISSUE TITLE
Jetstream

### ISSUE THREAD

**Issue by alifpay** [nats-io/nats-streaming-server#944]
I saw a jetstream in your slideshows and webinars. What is this? Jetstream is different then nats streaming server?

**Comment by ColinSullivan1** [comment]
@alifpay, Project JetStream is a new persistence offering, separate from NATS streaming.  NATS streaming has been great for many deployments, but as we've looked into the massive scale of IoT and big data, and have received input from the community we've decided to expand our streaming offerings to include JetStream, a new generation of persistence to securely handle billions of messages.  We didn't want to glue together multiple persistent clusters - it's the natural next step and most messaging projects do that to achieve expand the scale that they can operate - but that only gets you so far.

Like NATS Streaming, JetStream will support at least once delivery with durable subscribers and message replay.

JetStream will also:
- Support Wildcard Subscriptions
- Be tightly coupled with core NATS through API, deployment, and operations.
- Support Horizontal Scaling (without client indexes)
- Optimize for extremely large data sets

We know many are using NATS Streaming in production (40+ million docker downloads!) and that JetStream will overlap functionality.  We will continue to support NATS Streaming as a first class component of NATS, and Synadia will continue to support NATS streaming in their commercial support.  We'll also make it as easy as we can for users to migrate from NATS Streaming if they want to use new features found in JetStream.

If you haven't already, I encourage you to join [NATS slack](http://slack.nats.io), and check out the #jetstream channel.
