### ISSUE TITLE
question about sequence numbers

### ISSUE THREAD

**Issue by biskit** [nats-io/nats-streaming-server#945]
I have the following setup:

standalone NATS streaming server `STREAM: Starting nats-streaming-server[test-cluster] version 0.12.0`

and `Starting nats-server version 1.4.1`

and I start it like this: `./nats-streaming-server -st file -dir . -mi 5m -ma 1h -m 8222`

When I monitor the queues, the sequence number seems to sometimes go to 0. I thought the numbers never looped as I start my app with the last sequence number I retain.

For eg:
```
    {
      "name": "q1",
      "msgs": 169,
      "bytes": 3026271,
      "first_seq": 1,
      "last_seq": 169,
      "subscriptions": [
        {
          "client_id": "B6ECF42E28E954C39B4893240B2E870D_8161",
          "inbox": "_INBOX.eNuIfNNPnvhSGmYEU7SS47",
          "ack_inbox": "_INBOX.UhFI7O49QYeWsJQk0qgke3",
          "durable_name": "B6ECF42E28E954C39B4893240B2E870D_8161_q1_durable",
          "is_durable": true,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 169,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    }
```

I assumed the `first_seq`, `last_seq` will always be increasing till i delete my store?
My restarts depend on continuous increasing sequence numbers.

Or, is this sequence number different from `Msg.sequence`?

**Comment by aricart** [comment]
From the usage and the doc, the `-mi,  --max_inactivity <duration>    Max inactivity (no new message, no subscription) after which a channel can be garbage collected (0 for unlimited)` implies that the channel itself is garbage collected. That means that the channel actually goes away if there are no subscriptions or new messages arriving - in your case this is set to 5 minutes.

Also if you are manually keeping track of the last sequence you saw, likely in this case where the channel is destroyed, I would expect that `StartAtTimeDelta` or `StartAtTime` would probably be safer.

**Comment by kozlovic** [comment]
> I assumed the first_seq, last_seq will always be increasing till i delete my store?

And they are. But that's the key point, as @aricart mentioned, you are using max inactivity which causes the server to delete the channel store after that amount of time without new message and active consumers. I suspect that you have stopped your consumer application at one point, long enough for the server to decide to delete the channel.
If you want to keep message sequence numbers, and since you are already using message expiration, you should remove the `-mi` setting.

**Comment by biskit** [comment]
Makes sense. I also have a lot of temporary channels created that may last a varied duration. The idea was using the -mi to trim those. I've not seen an explicit way to delete channels. What would you suggest for it. (I can open a new issue if you like).

**Comment by kozlovic** [comment]
There is no way of forcing the deletion of a channel at the moment. The blocking part is how this command would be send to the server. We don't have CLI and have resisted so far to send POST commands to the monitoring endpoint.

Note that you can set channel limits (max inactivity is a channel limit) per channel and use wildcards for that. For instance you should have your temporary channels have a well know prefix for which you would set max inactivity, but not set that for other channels.
Have a look at this:
https://nats-io.github.io/docs/nats_streaming/configuring/storelimits.html
https://nats-io.github.io/docs/nats_streaming/configuring/storelimits.html#limits-inheritance
https://nats-io.github.io/docs/nats_streaming/configuring/storelimits.html#wildcards

**Comment by biskit** [comment]
Thanks Ivan. A wildcarded channel with max inactivity would work just fine!

**Comment by biskit** [comment]
More like a request... would be great if -sc can take a `here` file.
ie:
```
./nats-streaming-server -st file -dir . -ma 1h -sc <<EOF
channels : {
    query_>: {
      max_inactivity: "5m"
    }
}
EOF
```

**Comment by kozlovic** [comment]
Understood. But that wildcard is illegal. In NATS, wildcards work only as token replacement, not within a token. So this is valid wildcard: `foo.>`, and would match `foo.bar`, `foo.bar.baz` but not `foo`. However, `query_>` would match only a channel named `query_>`, that is, taken as a literal. So you may have to alter your channel names if you want to use the channel inheritance limit trick.

**Comment by biskit** [comment]
Thanks for pointing it out, instead of me scratching my head. I'll rework my naming convention for dynamic channels.
