### ISSUE TITLE
NATS streaming queue

### ISSUE THREAD

**Issue by frolad** [nats-io/nats-streaming-server#948]
Hi,

My company recently decided to use NATS server and now we are trying to implement NATS Streaming for other needs. My goal is to achieve queue in processing messages per-subject. Basically I have to be sure that while I'm processing first message second won't be sent to subscribers. With one sync subscriber on one container it works like expected, but once I'm adding second, third etc container (e.c. when AutoScalling works) all containers receives messages w/o waiting. 

I'm using QueueSubscribe to ensure that I'm processing one message only once  but it's not enough for my needs :(

Can you please advice, am I missing something or my only option is to implement cross-containers queue (e.c. on top of redis)?

thank you so much :)

**Comment by kozlovic** [comment]
Thank you for your interest. Unfortunately, in NATS Streaming, limiting the server to send a single message at a time is only possible with a single consumer, as you have seen. As soon as you use a queue group, each member will have its own MaxInflight, which means that even if you lower this to 1, it will be one per member.
In JetStream (the new streaming project), we will have work queues that should address this issue. Copying @derekcollison here.

**Comment by frolad** [comment]
Hi Ivan,
thank you so much! 
Looking forward for JetStream to be publicly available :)
I'll implement simple redis queue on top for now (we def don't wanna switch from NATS, it's so lovely to use :) ) and once JetStream released we will switch to it.
