### ISSUE TITLE
The pod of nats-streaming will change status to “Completed”  after k8s node reboot

### ISSUE THREAD

**Issue by wanjunlei** [nats-io/nats-streaming-server#954]
After the k8s node which the pod of nats-streaming in rebooted，the status of nats-streaming pod will change to “Completed” for ever。The nats-streaming cluster is not ready for ever 

![image](https://user-images.githubusercontent.com/53003665/67190169-0e731800-f422-11e9-9a70-9499a062268b.png)

/kind bug

**Comment by kozlovic** [comment]
Closed by #957
