### ISSUE TITLE
question about duplicate messages？

### ISSUE THREAD

**Issue by cjg1990** [nats-io/nats-streaming-server#964]
when subscription data in the snapshot file is not the latest, which means the last sent message sequence and the sequence list of unconfirmed messages are not the latest, Is it possible for subscribers to receive duplicate messages after server failures？

**Comment by kozlovic** [comment]
What you have to understand is that NATS Streaming is "at least once" delivery, so you ALWAYS have to expect that a message could be redelivered.
Replication of information about messages being sent to consumers and acks from consumers are replicated by batch (for performance reasons), so even without snapshots there is always a risk of redelivery of a message.
Even the simple fact that your subscription may have processed a message then is about to ACK and crash, or sends the ACK but connection is broken. That ack is lost, so from a server perspective the message will be redelivered.
