### ISSUE TITLE
Invitation to Slack is no longer active

### ISSUE THREAD

**Issue by Barmaglot123** [nats-io/nats-streaming-server#966]
The invitation to Slack is no longer active. When I try to go to chat using the link from the README.md I get this message: 
![image](https://user-images.githubusercontent.com/26883681/68779759-3d0d9880-0646-11ea-8ee3-7194c4bb57dd.png)

**Comment by kozlovic** [comment]
@gcolliso Can you help? We have this link in the README:
```
https://join.slack.com/t/natsio/shared_invite/enQtMzE2NDkxNDI2NTE1LTc5ZDEzYTkwYWZkYWQ5YjY1MzBjMWZmYzA5OGQxMzlkMGQzMjYxNGM3MWYxMjNiYmNjNzIwMTVjMWE2ZDgxZGM
```
Has it changed?

**Comment by gcolliso** [comment]
we now have the shortened version at https://slack.nats.io

**Comment by kozlovic** [comment]
@gcolliso Ok, thanks, I will update the README.md then.
