### ISSUE TITLE
"credentials" config option not documented

### ISSUE THREAD

**Issue by LaurensVergote** [nats-io/nats-streaming-server#984]
The "credentials" option added by #941 does not seem to be documented in the -h of nats-streaming-server nor in the documentation over at docs.nats.io (https://docs.nats.io/nats-streaming-server/configuring/cfgfile)

It took me quite a while to figure out the option exists. Is this something that was forgotten or is this already being looked at?

**Comment by kozlovic** [comment]
@LaurensVergote Apologies for the trouble. It is normal that it is not in the `-h` because this cannot be set from command line (at least at the moment). But yes, it is missing from docs.nats.io, I will create a PR for that. Thanks!

**Comment by kozlovic** [comment]
Done, PR is up: https://github.com/nats-io/nats.docs/pull/15

**Comment by kozlovic** [comment]
The PR has been merged and update is already live on the docs' site. Thanks!
