### ISSUE TITLE
Nats cluster - nodes are talking, but election is not happening

### ISSUE THREAD

**Issue by tharrold** [nats-io/nats-streaming-server#990]
I have a 3 node NATS cluster.  fairly basic configuration.  The nodes seem to communicate, as the routing detail (for all 3 nodes) is visible when connecting to an individual node's web server.

However, I have enabled cluster_raft_logging at startup, and it clearly shows that the raft election is not happening.

what am I missing?  I have compared these configurations to some other dev/test clusters, and I can see no obvious differences.   appropriate firewall ports are opened on all 3 nodes,

[nss-node-a.txt](https://github.com/nats-io/nats-streaming-server/files/3952811/nss-node-a.txt)
[nss-node-b.txt](https://github.com/nats-io/nats-streaming-server/files/3952813/nss-node-b.txt)
[nss-node-c.txt](https://github.com/nats-io/nats-streaming-server/files/3952815/nss-node-c.txt)

**Comment by kozlovic** [comment]
Based on what I see in your configs and the description of the issue, the first thing that comes to mind is that you are pointing the streaming store and raft logs (cluster_log_path) to the same location/files on each node, which is not good. Each node needs to have its own stores. Could you please verify that you are not pointing to the same files?
If that is not it, please send me the log files for review.

**Comment by tharrold** [comment]
Here is what I see in the logs (this is from node b, but others show exact same):

> [24487] 2019/12/11 17:10:03.484693 [INF] STREAM: raft: Node at test-cluster.b.test-cluster [Candidate] entering Candidate state in term 2481
[24487] 2019/12/11 17:10:03.484884 [TRC] STREAM: raft: Votes needed: 2
[24487] 2019/12/11 17:10:03.484905 [TRC] STREAM: raft: Vote granted from b in term 2481. Tally: 1
[24487] 2019/12/11 17:10:05.485461 [ERR] STREAM: raft: Failed to make RequestVote RPC to {Voter a,c test-cluster.a,c.test-cluster}: nats: timeout
[24487] 2019/12/11 17:10:06.615345 [WRN] STREAM: raft: Election timeout reached, restarting election
[24487] 2019/12/11 17:10:06.615395 [INF] STREAM: raft: Node at test-cluster.b.test-cluster [Candidate] entering Candidate state in term 2482
[24487] 2019/12/11 17:10:06.615573 [TRC] STREAM: raft: Votes needed: 2
[24487] 2019/12/11 17:10:06.615591 [TRC] STREAM: raft: Vote granted from b in term 2482. Tally: 1
[24487] 2019/12/11 17:10:08.616155 [ERR] STREAM: raft: Failed to make RequestVote RPC to {Voter a,c test-cluster.a,c.test-cluster}: nats: timeout

**Comment by tharrold** [comment]
I made a change, stopped all 3 nodes, removed the store from each node, and restarted.
It now seems to be working. 

The change was:

> <     peers: ["a,c"]
---
>     peers: ["a","c"]

Is there anywhere I should have looked to find a typo like this, if in fact this was the reason for the cluster election not happening?

Thanks,

-Tom

**Comment by kozlovic** [comment]
It was the reason. The peers in your case should have been an array of two strings "a" and "b", while you indeed had an array of 1 string "a,c". The config cannot presume how many nodes you want, and there is no restriction on the peer name having or not a ",". 

But to be honest I got caught myself in the past I think. Maybe I could add a warning if the peer's array has only 1 element and/or contain a comment (just a warning, but not fail the start). What do you think?

**Comment by tharrold** [comment]
Thanks for the quick response.  How about a "summary" of the cluster peers?  (each node can log it's own, of course)

Something like "Found the following peers: 
peer 1: b
peer 2: c"

This way, we could easily identify a mistake if we see: "found the following peers:  peer 1: "b,c"

Could this be queried from the built-in web server?  I was able to see the status of the cluster node (Clustered, Candidate), but not the cluster nodes prospective peers.   

And honestly, I'd consider making the "," a non-valid character in a peer name.  There has to be a delimiter, and that seems to make sense.

Thank you,

-Tom
